Repository elastic/apm-agent-dotnet, pull requests merged in 2019-09, with the labels that each got.

#468 ci(jenkins): Set GitHub notification context to apm-ci
  .ci/jobs/defaults.yml
Labels: automation, ci

#511 [docs] Fix heading ID
  docs/configuration.asciidoc
Labels: docs

#509 Implement automatically tracing exception escaping from a Full Framework ASP.NET transaction
  src/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/CaptureHeadersConfigDisabledTest.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/CustomEnvironmentViaSettings.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/CustomFlushInterval.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/CustomServiceNameSetViaSettings.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/DistributedTracingTests.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/ErrorsTests.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/MetadataTests.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/MetricsTestsBase.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/SampleRate0Tests.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/TestWithDefaultSettings.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/TestsBase.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/TestsWithSampleAppLogDisabled.cs
Labels: [zube]: In Review
