Repository elastic/apm-agent-dotnet, pull requests merged in 2019-07, with the labels that each got.

#334 Fix TrimToLength and move it to SerializationUtils
  src/Elastic.Apm/Helpers/StringExtensions.cs
  src/Elastic.Apm/Report/Serialization/SerializationUtils.cs
  src/Elastic.Apm/Report/Serialization/TagsJsonConverter.cs
  src/Elastic.Apm/Report/Serialization/TrimmedStringJsonConverter.cs
  test/Elastic.Apm.Tests/SerializationTests.cs
Labels: [zube]: In Review, bug

#331 Fix Error timestamp after Span end bug
  src/Elastic.Apm.EntityFrameworkCore/EfCoreDiagnosticListener.cs
  src/Elastic.Apm/Api/IExecutionSegment.cs
  src/Elastic.Apm/Helpers/TimeExtensions.cs
  src/Elastic.Apm/Helpers/TimeUtils.cs
  src/Elastic.Apm/Metrics/MetricsCollector.cs
  src/Elastic.Apm/Model/Error.cs
  src/Elastic.Apm/Model/ExecutionSegmentCommon.cs
  src/Elastic.Apm/Model/Span.cs
  src/Elastic.Apm/Model/Transaction.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/TestsBase.cs
  test/Elastic.Apm.Tests.MockApmServer/FluentAssertionsExtensions.cs
  test/Elastic.Apm.Tests/HelpersTests/ContractExtensionsTests.cs
  test/Elastic.Apm.Tests/HelpersTests/StringExtensionsTests.cs
  test/Elastic.Apm.Tests/HelpersTests/TimeExtensionsTests.cs
  test/Elastic.Apm.Tests/HelpersTests/TimeUtilsTests.cs
  test/Elastic.Apm.Tests/SerializationTests.cs
  test/Elastic.Apm.Tests/TestHelpers/FluentAssertionsUtils.cs
  test/Elastic.Apm.Tests/TestHelpers/TimeUtils.cs
Labels: [zube]: In Review, bug

#371 Renaming the Elastic.Apm.All pacakge and the UseElasticApm method
  ElasticApmAgent.sln
  README.md
  docs/setup.asciidoc
  sample/SampleAspNetCoreApp/SampleAspNetCoreApp.csproj
  sample/SampleAspNetCoreApp/Startup.cs
  sample/WebApiSample/Startup.cs
  sample/WebApiSample/WebApiSample.csproj
  src/Elastic.Apm.AspNetCore/ApmMiddlewareExtension.cs
  src/Elastic.Apm.NetCoreAll/ApmMiddlewareExtension.cs
  src/Elastic.Apm.NetCoreAll/Elastic.Apm.NetCoreAll.csproj
  src/Elastic.Apm/Agent.cs
  test/Elastic.Apm.AspNetCore.Tests/Helper.cs
Labels: [zube]: In Review, breaking change

#249 use logger created from logger factory instead of console logger
  docs/configuration.asciidoc
  sample/SampleAspNetCoreApp/appsettings.json
  sample/WebApiSample/appsettings.json
  src/Elastic.Apm.AspNetCore/ApmMiddlewareExtension.cs
  src/Elastic.Apm.AspNetCore/AspNetCoreLogger.cs
  src/Elastic.Apm.AspNetCore/Elastic.Apm.AspNetCore.csproj
  src/Elastic.Apm.AspNetCore/Extensions/LoggerExtensions.cs
  test/Elastic.Apm.AspNetCore.Tests/ApmMiddlewareExtensionTest.cs
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreLoggerTests.cs
  test/Elastic.Apm.AspNetCore.Tests/Elastic.Apm.AspNetCore.Tests.csproj
  test/Elastic.Apm.AspNetCore.Tests/LoggerExtensionsTests.cs
Labels: [zube]: In Review

#374 Add StackTraceLimit and SpanFramesMinDurationInMilliseconds configs
  Jenkinsfile
  src/Elastic.Apm.AspNetCore/Config/MicrosoftExtensionsConfig.cs
  src/Elastic.Apm/Api/Tracer.cs
  src/Elastic.Apm/Config/AbstractConfigurationReader.cs
  src/Elastic.Apm/Config/ConfigConsts.cs
  src/Elastic.Apm/Config/EnvironmentConfigurationReader.cs
  src/Elastic.Apm/Config/IAgentConfigReader.cs
  src/Elastic.Apm/Helpers/StacktraceHelper.cs
  src/Elastic.Apm/Logging/IApmLoggingExtensions.cs
  src/Elastic.Apm/Metrics/MetricsCollector.cs
  src/Elastic.Apm/Model/CapturedException.cs
  src/Elastic.Apm/Model/ExecutionSegmentCommon.cs
  src/Elastic.Apm/Model/Span.cs
  src/Elastic.Apm/Model/Transaction.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/ErrorsTests.cs
  test/Elastic.Apm.PerfTests/Program.cs
  test/Elastic.Apm.Tests.MockApmServer/AssertValidExtensions.cs
  test/Elastic.Apm.Tests/ApiTests/ApiTests.cs
  test/Elastic.Apm.Tests/BasicAgentTests.cs
  test/Elastic.Apm.Tests/ConfigTests.cs
  test/Elastic.Apm.Tests/ConstructorTests.cs
  test/Elastic.Apm.Tests/HttpDiagnosticListenerTest.cs
  test/Elastic.Apm.Tests/MetricsTests.cs
  test/Elastic.Apm.Tests/Mocks/TestAgentComponents.cs
  test/Elastic.Apm.Tests/Mocks/TestAgentConfigurationReader.cs
  test/Elastic.Apm.Tests/SamplerTests.cs
  test/Elastic.Apm.Tests/SerializationTests.cs
  test/Elastic.Apm.Tests/StackTraceTests.cs
Labels: [zube]: In Review

#404 ci: docs stage is handled within the elasticsearch-ci/docs
  Jenkinsfile
Labels: [zube]: In Review, automation, ci

#389 Change Level property of IApmLogger to IsEnabled method
  src/Elastic.Apm.AspNetCore/AspNetCoreLogger.cs
  src/Elastic.Apm.AspNetCore/Extensions/LoggerExtensions.cs
  src/Elastic.Apm/Logging/ConsoleLogger.cs
  src/Elastic.Apm/Logging/IApmLogger.cs
  src/Elastic.Apm/Logging/IApmLoggingExtensions.cs
  src/Elastic.Apm/Logging/ScopedLogger.cs
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreLoggerTests.cs
  test/Elastic.Apm.AspNetCore.Tests/LoggerExtensionsTests.cs
  test/Elastic.Apm.Tests/ConfigTests.cs
  test/Elastic.Apm.Tests/ConstructorTests.cs
  test/Elastic.Apm.Tests/Mocks/NoopLogger.cs
  test/Elastic.Apm.Tests/TestHelpers/LineWriterToLoggerAdaptor.cs
Labels: [zube]: In Review, breaking change

#372 ci: test windows immutable workers
  .ci/windows/dotnet.bat
  .ci/windows/msbuild.bat
  .ci/windows/tools.ps1
  Jenkinsfile
Labels: [zube]: Inbox, automation, ci, enhancement

#415 feat: add IIS test support
  .ci/docker/iis/Dockerfile
  .ci/docker/iis/README.md
  .ci/docker/iis/content/index.html
  .ci/windows/msbuild.bat
  .ci/windows/test-iis.bat
  .ci/windows/tools.ps1
  .editorconfig
  Jenkinsfile
Labels: automation, ci, test
