Repository elastic/apm-agent-dotnet, pull requests merged in 2019-06, with the labels that each got.

#240 feat: real stack #239
  src/Elastic.Apm/Helpers/StacktraceHelper.cs
  test/Elastic.Apm.Tests/StackTraceTests.cs
Labels: [zube]: In Review

#255 fix(jenkins): use both windows workers
  Jenkinsfile
Labels: [zube]: In Review, automation

#254 feat(jenkins): new notifications and reports to Elasticsearch
  Jenkinsfile
Labels: [zube]: In Review, automation

#256 feat(jenkins): run linux build inside a container
  Jenkinsfile
Labels: [zube]: In Review, automation

#223 [APM-CI][All] Make the trigger by comment case-insensitive
  Jenkinsfile
Labels: automation

#262 fix: fix release stages
  Jenkinsfile
Labels: automation

#250 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: [zube]: In Review

#253 Fix stacktrace
  src/Elastic.Apm/Helpers/StacktraceHelper.cs
  test/Elastic.Apm.Tests/StackTraceTests.cs
Labels: [zube]: In Review

#252 Implement sending docker container id
  ElasticApmAgent.sln
  src/Elastic.Apm/Agent.cs
  src/Elastic.Apm/AgentComponents.cs
  src/Elastic.Apm/Api/Container.cs
  src/Elastic.Apm/Api/System.cs
  src/Elastic.Apm/Helpers/SystemInfoHelper.cs
  src/Elastic.Apm/Report/PayloadSenderV2.cs
  test/Elastic.Apm.DockerTests/BasicDockerTests.cs
  test/Elastic.Apm.DockerTests/ContainerIdCalculationTests.cs
  test/Elastic.Apm.DockerTests/Elastic.Apm.DockerTests.csproj
  test/Elastic.Apm.Tests/BasicAgentTests.cs
Labels: [zube]: In Review

#270 fix: grab error info in case of fail
  Jenkinsfile
Labels: automation

#246 [APM-CI][.NET] GH Checks for the PR
  Jenkinsfile
Labels: automation

#301 [docs] update to beta
  docs/index.asciidoc
  docs/intro.asciidoc
  docs/page_header.html
Labels: docs

#294 ci(jenkins): trigger async ITs and update github check for the pull request
  Jenkinsfile
Labels: automation

#314 Implement service.runtime.{name and version}
  sample/AspNetFullFrameworkSampleApp/Controllers/HomeController.cs
  src/Elastic.Apm.AspNetFullFramework/Elastic.Apm.AspNetFullFramework.csproj
  src/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs
  src/Elastic.Apm.AspNetFullFramework/InternalsVisibleTo.cs
  src/Elastic.Apm/AgentComponents.cs
  src/Elastic.Apm/Api/Service.cs
  src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListener.cs
  src/Elastic.Apm/Helpers/PlatformDetection.cs
  src/Elastic.Apm/Helpers/SystemInfoHelper.cs
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreMiddlewareTests.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/MetadataTests.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/TestsBase.cs
  test/Elastic.Apm.Tests.MockApmServer/AssertValidExtensions.cs
  test/Elastic.Apm.Tests/BasicAgentTests.cs
Labels: [zube]: In Review

#325 ci(jenkins): notify first time contributor github check
  Jenkinsfile
Labels: automation

#323 ci: notify on cleanup stage
  Jenkinsfile
Labels: [zube]: In Review, automation
