Repository elastic/apm-agent-dotnet, pull requests merged in 2019-12, with the labels that each got.

#631 ci(jenkins): cancel previous running builds
  Jenkinsfile
Labels: automation, ci

#630 ci(jenkins): trigger opbeans release process
  Jenkinsfile
Labels: automation, ci

#648 Add assembly name to <add name="ElasticApmModule" type=
  docs/setup.asciidoc
  sample/AspNetFullFrameworkSampleApp/Web.config
Labels: bug, from a real user

#649 Add assembly name to <add name="ElasticApmModule" type= (1.x)
  docs/setup.asciidoc
  sample/AspNetFullFrameworkSampleApp/Web.config
Labels: bug, from a real user

#646 ci(jenkins): support different targets
  .ci/docker/buildtools-windows/Dockerfile
  .ci/docker/buildtools-windows/README.md
  .ci/docker/sdk-linux/Dockerfile
  .ci/docker/sdk-linux/README.md
  .ci/linux/test-tools.sh
  .ci/linux/test.sh
  .ci/linux/tools.sh
  .ci/packer_cache.sh
  .ci/windows/msbuild-tools.ps1
  .ci/windows/msbuild.bat
  .ci/windows/prepare-test.bat
  .ci/windows/test-tools.ps1
  .ci/windows/test.bat
  .ci/windows/tools.ps1
  Jenkinsfile
Labels: automation, ci

#672 ci(jenkins): hide sensitive data
  Jenkinsfile
Labels: automation, bug, ci

#673 ci(jenkins): exclude the cached .nuget folder
  .ci/linux/deploy.sh
Labels: automation, bug, ci

#674 ci(jenkins): fix the exclude in the deploy
  .ci/linux/deploy.sh
Labels: automation, bug, ci
