Repository elastic/apm-agent-dotnet, pull requests merged in 2019-04, with the labels that each got.

#167 [docs] Add release notes
  docs/index.asciidoc
  docs/release-notes.asciidoc
Labels: docs

#172 [APM-CI] Release snapshots to AppVeyor
  Jenkinsfile
Labels: automation

#173 [APM-CI] fix stages conditions
  Jenkinsfile
Labels: automation

#168 Distributed tracing - implement traceparent from w3c Trace Context
  ElasticApmAgent.sln
  sample/SampleAspNetCoreApp/Controllers/HomeController.cs
  sample/SampleAspNetCoreApp/README.md
  sample/SampleAspNetCoreApp/SampleAspNetCoreApp.csproj
  sample/SampleAspNetCoreApp/Startup.cs
  sample/SampleAspNetCoreApp/Views/Home/DistributedTracingMiniSample.cshtml
  sample/SampleAspNetCoreApp/Views/Home/SimplePage.cshtml
  sample/SampleAspNetCoreApp/Views/Shared/_Layout.cshtml
  sample/SampleAspNetCoreApp/appsettings.json
  sample/WebApiSample/Controllers/ValuesController.cs
  sample/WebApiSample/Program.cs
  sample/WebApiSample/README.md
  sample/WebApiSample/Startup.cs
  sample/WebApiSample/WebApiSample.csproj
  sample/WebApiSample/appsettings.Development.json
  sample/WebApiSample/appsettings.json
  src/Elastic.Apm.AspNetCore/ApmMiddleware.cs
  src/Elastic.Apm.AspNetCore/ApmMiddlewareExtension.cs
  src/Elastic.Apm/Api/Tracer.cs
  src/Elastic.Apm/Consts.cs
  src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListener.cs
  src/Elastic.Apm/DistributedTracing/TraceParent.cs
  src/Elastic.Apm/Helpers/RandomGenerator.cs
  src/Elastic.Apm/Model/Payload/Transaction.cs
  test/Elastic.Apm.AspNetCore.Tests/DistributedTracingAspNetCoreTests.cs
  test/Elastic.Apm.AspNetCore.Tests/Elastic.Apm.AspNetCore.Tests.csproj
  test/Elastic.Apm.AspNetCore.Tests/Helper.cs
  test/Elastic.Apm.AspNetCore.Tests/MicrosoftExtensionsConfigTests.cs
  test/Elastic.Apm.PerfTests/Program.cs
  test/Elastic.Apm.Tests/DistributedTracingTests.cs
Labels: [zube]: In Review

#175 [APM-CI] update codecov step
  Jenkinsfile
Labels: automation

#179 Public Agent API Update - Create sub spans and add optional parameter to pass a trace context
  sample/ApiSamples/Program.cs
  sample/AspNetFullFrameworkSampleApp/Controllers/HomeController.cs
  src/Elastic.Apm.AspNetCore/ApmMiddleware.cs
  src/Elastic.Apm.EntityFrameworkCore/EfCoreDiagnosticListener.cs
  src/Elastic.Apm/Agent.cs
  src/Elastic.Apm/AgentComponents.cs
  src/Elastic.Apm/Api/IError.cs
  src/Elastic.Apm/Api/IExecutionSegment.cs
  src/Elastic.Apm/Api/ISpan.cs
  src/Elastic.Apm/Api/ITracer.cs
  src/Elastic.Apm/Api/ITransaction.cs
  src/Elastic.Apm/Api/Tracer.cs
  src/Elastic.Apm/Config/AbstractConfigurationReader.cs
  src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListener.cs
  src/Elastic.Apm/DistributedTracing/TraceParent.cs
  src/Elastic.Apm/Helpers/StacktraceHelper.cs
  src/Elastic.Apm/Model/CapturedException.cs
  src/Elastic.Apm/Model/CapturedStackFrame.cs
  src/Elastic.Apm/Model/Error.cs
  src/Elastic.Apm/Model/ExecutionSegmentCommon.cs
  src/Elastic.Apm/Model/Payload/Span.cs
  src/Elastic.Apm/Model/Span.cs
  src/Elastic.Apm/Model/SpanCount.cs
  src/Elastic.Apm/Model/Transaction.cs
  src/Elastic.Apm/Report/IPayloadSender.cs
  src/Elastic.Apm/Report/PayloadSenderV2.cs
  src/Elastic.Apm/TransactionContainer.cs
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreDiagnosticListenerTest.cs
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreMiddlewareTests.cs
  test/Elastic.Apm.AspNetCore.Tests/CaptureUserTest.cs
  test/Elastic.Apm.Tests/ApiTests/ApiTests.cs
  test/Elastic.Apm.Tests/ApiTests/ConvenientApiSpanTests.cs
  test/Elastic.Apm.Tests/ApiTests/ConvenientApiTransactionTests.cs
  test/Elastic.Apm.Tests/ApiTests/TraceContextTests.cs
  test/Elastic.Apm.Tests/BasicAgentTests.cs
  test/Elastic.Apm.Tests/HttpDiagnosticListenerTest.cs
  test/Elastic.Apm.Tests/Mocks/MockPayloadSender.cs
  test/Elastic.Apm.Tests/Mocks/TestAgentComponents.cs
  test/Elastic.Apm.Tests/SerializationTests.cs
  test/Elastic.Apm.Tests/StackTraceTests.cs
Labels: [zube]: In Progress

#187 [APM-CI] msbuild testing
  Jenkinsfile
Labels: [zube]: In Review

#188 Implement sampling
  docs/configuration.asciidoc
  sample/ApiSamples/Program.cs
  sample/SampleAspNetCoreApp/appsettings.json
  src/Elastic.Apm.AspNetCore/ApmMiddleware.cs
  src/Elastic.Apm.AspNetCore/Config/MicrosoftExtensionsConfig.cs
  src/Elastic.Apm/AgentComponents.cs
  src/Elastic.Apm/Api/DistributedTracingData.cs
  src/Elastic.Apm/Api/IExecutionSegment.cs
  src/Elastic.Apm/Api/ITracer.cs
  src/Elastic.Apm/Api/Tracer.cs
  src/Elastic.Apm/Config/AbstractConfigurationReader.cs
  src/Elastic.Apm/Config/ConfigConsts.cs
  src/Elastic.Apm/Config/EnvironmentConfigurationReader.cs
  src/Elastic.Apm/Config/IAgentConfigReader.cs
  src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListener.cs
  src/Elastic.Apm/DistributedTracing/TraceParent.cs
  src/Elastic.Apm/Helpers/IntExtensions.cs
  src/Elastic.Apm/Helpers/ObjectExtensions.cs
  src/Elastic.Apm/Helpers/RandomGenerator.cs
  src/Elastic.Apm/Helpers/ToStringBuilder.cs
  src/Elastic.Apm/Logging/IApmLogger.cs
  src/Elastic.Apm/Logging/IApmLoggingExtensions.cs
  src/Elastic.Apm/Model/Error.cs
  src/Elastic.Apm/Model/ExecutionSegmentCommon.cs
  src/Elastic.Apm/Model/Span.cs
  src/Elastic.Apm/Model/Transaction.cs
  src/Elastic.Apm/Report/PayloadSenderV2.cs
  src/Elastic.Apm/Report/Serialization/PayloadItemSerializer.cs
  src/Elastic.Apm/Sampler.cs
  test/Elastic.Apm.AspNetCore.Tests/DistributedTracingAspNetCoreTests.cs
  test/Elastic.Apm.AspNetCore.Tests/MicrosoftExtensionsConfigTests.cs
  test/Elastic.Apm.AspNetCore.Tests/TestConfigs/appsettings_invalid.json
  test/Elastic.Apm.AspNetCore.Tests/TestConfigs/appsettings_valid.json
  test/Elastic.Apm.PerfTests/Program.cs
  test/Elastic.Apm.Tests/ApiTests/ApiTests.cs
  test/Elastic.Apm.Tests/ApiTests/ConvenientApiTransactionTests.cs
  test/Elastic.Apm.Tests/ApiTests/DistributedTracingDataTests.cs
  test/Elastic.Apm.Tests/ApiTests/TraceContextTests.cs
  test/Elastic.Apm.Tests/ConfigTest.cs
  test/Elastic.Apm.Tests/ConstructorTests.cs
  test/Elastic.Apm.Tests/DistributedTracingTests.cs
  test/Elastic.Apm.Tests/HelpersTests/IntExtensionsTests.cs
  test/Elastic.Apm.Tests/HelpersTests/ObjectExtensionsTests.cs
  test/Elastic.Apm.Tests/HelpersTests/ToStringBuilderTests.cs
  test/Elastic.Apm.Tests/Mocks/NoopLogger.cs
  test/Elastic.Apm.Tests/Mocks/NoopPayloadSender.cs
  test/Elastic.Apm.Tests/Mocks/TestAgentConfigurationReader.cs
  test/Elastic.Apm.Tests/SamplerTests.cs
  test/Elastic.Apm.Tests/SerializationTests.cs
  test/Elastic.Apm.Tests/TransactionSamplingTests.cs
Labels: [zube]: In Review

#197 docs: clarify tags
  docs/public-api.asciidoc
Labels: docs

#195 Implement tracing transaction start/end for ASP.NET .NET Framework
  ElasticApmAgent.sln
  Jenkinsfile
  build/elasticapmsample.snk
  sample/AspNetFullFrameworkSampleApp/AspNetFullFrameworkSampleApp.csproj
  sample/AspNetFullFrameworkSampleApp/Controllers/HomeController.cs
  sample/AspNetFullFrameworkSampleApp/ElasticApmModule.cs
  sample/AspNetFullFrameworkSampleApp/Web.config
  sample/SampleAspNetCoreApp/SampleAspNetCoreApp.csproj
  sample/WebApiSample/WebApiSample.csproj
  src/Elastic.Apm.AspNetCore/ApmMiddleware.cs
  src/Elastic.Apm.AspNetCore/DiagnosticListener/AspNetCoreDiagnosticsSubscriber.cs
  src/Elastic.Apm.AspNetCore/Elastic.Apm.AspNetCore.csproj
  src/Elastic.Apm.AspNetFullFramework/Elastic.Apm.AspNetFullFramework.csproj
  src/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs
  src/Elastic.Apm.AspNetFullFramework/FullFrameworkConfigReader.cs
  src/Elastic.Apm.AspNetFullFramework/Properties/AssemblyInfo.cs
  src/Elastic.Apm.EntityFrameworkCore/EfCoreDiagnosticsSubscriber.cs
  src/Elastic.Apm/Agent.cs
  src/Elastic.Apm/Config/AbstractConfigurationReader.cs
  src/Elastic.Apm/Config/ConfigConsts.cs
  src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListener.cs
  src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListenerCoreImpl.cs
  src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListenerFullFrameworkImpl.cs
  src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListenerImplBase.cs
  src/Elastic.Apm/DiagnosticSource/DiagnosticInitializer.cs
  src/Elastic.Apm/DiagnosticSource/HttpDiagnosticsSubscriber.cs
  src/Elastic.Apm/Helpers/PlatformDetection.cs
  src/Elastic.Apm/Helpers/StringBuilderExtensions.cs
  src/Elastic.Apm/Model/Transaction.cs
  src/Elastic.Apm/Sampler.cs
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreDiagnosticListenerTest.cs
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreMiddlewareTests.cs
  test/Elastic.Apm.AspNetCore.Tests/CaptureUserTest.cs
  test/Elastic.Apm.AspNetCore.Tests/TransactionNameTests.cs
  test/Elastic.Apm.Tests/HelpersTests/StringBuilderExtensionsTests.cs
  test/Elastic.Apm.Tests/HttpDiagnosticListenerTest.cs
Labels: [zube]: In Review
