Repository elastic/apm-agent-dotnet, pull requests merged in 2019-03, with the labels that each got.

#133 move assertions over to fluent assertions
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreDiagnosticListenerTest.cs
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreMiddlewareTests.cs
  test/Elastic.Apm.AspNetCore.Tests/DiagnosticListenerTests.cs
  test/Elastic.Apm.AspNetCore.Tests/Elastic.Apm.AspNetCore.Tests.csproj
  test/Elastic.Apm.AspNetCore.Tests/MicrosoftExtensionsConfigTests.cs
  test/Elastic.Apm.Tests/ApiTests/ApiTests.cs
  test/Elastic.Apm.Tests/ApiTests/ConvenientApiSpanTests.cs
  test/Elastic.Apm.Tests/ApiTests/ConvenientApiTransactionTests.cs
  test/Elastic.Apm.Tests/BasicAgentTests.cs
  test/Elastic.Apm.Tests/ConfigTest.cs
  test/Elastic.Apm.Tests/Elastic.Apm.Tests.csproj
  test/Elastic.Apm.Tests/Extensions/ShouldWaitDurationExtensions.cs
  test/Elastic.Apm.Tests/Extensions/WaitExtensions.cs
  test/Elastic.Apm.Tests/HttpDiagnosticListenerTest.cs
  test/Elastic.Apm.Tests/LoggerTest.cs
  test/Elastic.Apm.Tests/StackTraceTests.cs
Labels: [zube]: In Review

#128 Fix #121 ConsoleLogger should pick up configuration
  src/Elastic.Apm.AspNetCore/ApmMiddlewareExtension.cs
  src/Elastic.Apm/Agent.cs
  src/Elastic.Apm/AgentComponents.cs
  src/Elastic.Apm/Config/AbstractConfigurationReader.cs
  src/Elastic.Apm/Logging/ConsoleLogger.cs
  src/Elastic.Apm/Logging/IApmLogger.cs
  src/Elastic.Apm/Logging/ScopedLogger.cs
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreMiddlewareTests.cs
  test/Elastic.Apm.AspNetCore.Tests/MicrosoftExtensionsConfigTests.cs
  test/Elastic.Apm.Tests/ConfigTest.cs
  test/Elastic.Apm.Tests/ConstructorTests.cs
  test/Elastic.Apm.Tests/HttpDiagnosticListenerTest.cs
  test/Elastic.Apm.Tests/LoggerTest.cs
  test/Elastic.Apm.Tests/Mocks/TestAgentComponents.cs
  test/Elastic.Apm.Tests/Mocks/TestAgentConfigurationReader.cs
  test/Elastic.Apm.Tests/Mocks/TestLogger.cs
Labels: [zube]: In Review

#136 Intake v2
  src/Elastic.Apm.AspNetCore/ApmMiddlewareExtension.cs
  src/Elastic.Apm/Agent.cs
  src/Elastic.Apm/AgentComponents.cs
  src/Elastic.Apm/Api/IError.cs
  src/Elastic.Apm/Api/ISpan.cs
  src/Elastic.Apm/Api/ITransaction.cs
  src/Elastic.Apm/Api/Request.cs
  src/Elastic.Apm/Api/Response.cs
  src/Elastic.Apm/Api/Service.cs
  src/Elastic.Apm/Api/Tracer.cs
  src/Elastic.Apm/Consts.cs
  src/Elastic.Apm/Helpers/RandomGenerator.cs
  src/Elastic.Apm/Helpers/StacktraceHelper.cs
  src/Elastic.Apm/Model/Payload/CapturedException.cs
  src/Elastic.Apm/Model/Payload/CapturedStackFrame.cs
  src/Elastic.Apm/Model/Payload/Error.cs
  src/Elastic.Apm/Model/Payload/IPayload.cs
  src/Elastic.Apm/Model/Payload/Payload.cs
  src/Elastic.Apm/Model/Payload/Span.cs
  src/Elastic.Apm/Model/Payload/SpanCount.cs
  src/Elastic.Apm/Model/Payload/Stacktrace.cs
  src/Elastic.Apm/Model/Payload/Transaction.cs
  src/Elastic.Apm/Report/IPayloadSender.cs
  src/Elastic.Apm/Report/PayloadSender.cs
  src/Elastic.Apm/Report/PayloadSenderV2.cs
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreDiagnosticListenerTest.cs
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreMiddlewareTests.cs
  test/Elastic.Apm.AspNetCore.Tests/DiagnosticListenerTests.cs
  test/Elastic.Apm.Tests/ApiTests/ApiTests.cs
  test/Elastic.Apm.Tests/ApiTests/ConvenientApiSpanTests.cs
  test/Elastic.Apm.Tests/ApiTests/ConvenientApiTransactionTests.cs
  test/Elastic.Apm.Tests/BasicAgentTests.cs
  test/Elastic.Apm.Tests/ConfigTest.cs
  test/Elastic.Apm.Tests/ConstructorTests.cs
  test/Elastic.Apm.Tests/HttpDiagnosticListenerTest.cs
  test/Elastic.Apm.Tests/Mocks/MockPayloadSender.cs
  test/Elastic.Apm.Tests/StackTraceTests.cs
Labels: [zube]: In Review

#147 [APM-CI] use current as pipeline shared library version
  Jenkinsfile
Labels: automation

#151 [docs] Add CaptureHeaders and SecretToken settings docs and setup
  docs/configuration.asciidoc
  docs/index.asciidoc
  docs/setup.asciidoc
Labels: [zube]: In Review, docs

#156 [APM-CI] improves on .Net SDK install process
  Jenkinsfile
Labels: automation

#152 Add ToStringBuilder helper to support uniform ToString format
  src/Elastic.Apm/Helpers/ToStringBuilder.cs
  src/Elastic.Apm/Model/Payload/Error.cs
  src/Elastic.Apm/Model/Payload/Span.cs
  src/Elastic.Apm/Model/Payload/Transaction.cs
  test/Elastic.Apm.Tests/Elastic.Apm.Tests.csproj
  test/Elastic.Apm.Tests/HelpersTests/ToStringBuilderTests.cs
Labels: [zube]: In Review
