Repository elastic/apm-agent-dotnet, pull requests merged in 2019-02, with the labels that each got.

#92 [docs] Add release banner and prototype warning
  docs/intro.asciidoc
  docs/page_header.html
Labels: docs

#95 [APM-CI] windows build
  .editorconfig
  Jenkinsfile
Labels: automation

#96 [APM-CI] Refactor
  Jenkinsfile
Labels: automation

#97 [APM-CI] run builDocs inside the BASE_DIR
  Jenkinsfile
Labels: automation

#105 [APM-CI] pass Threshold parameter to coverlet
  Jenkinsfile
Labels: [zube]: In Review, automation

#120 fixes #119 max span name + handle result
  src/Elastic.Apm/Consts.cs
  src/Elastic.Apm/Model/Payload/Span.cs
  src/Elastic.Apm/Report/PayloadSender.cs
  test/Elastic.Apm.Tests/BasicAgentTests.cs
Labels: [zube]: In Review

#87 Initial stab at structured logging without dependencies
  src/Elastic.Apm.AspNetCore/Config/MicrosoftExtensionsConfig.cs
  src/Elastic.Apm.AspNetCore/DiagnosticListener/AspNetCoreDiagnosticListener.cs
  src/Elastic.Apm.EntityFrameworkCore/EfCoreDiagnosticListener.cs
  src/Elastic.Apm/Agent.cs
  src/Elastic.Apm/AgentComponents.cs
  src/Elastic.Apm/Api/Tracer.cs
  src/Elastic.Apm/Config/AbstractConfigurationReader.cs
  src/Elastic.Apm/Config/EnvironmentConfigurationReader.cs
  src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListener.cs
  src/Elastic.Apm/Elastic.Apm.csproj
  src/Elastic.Apm/Helpers/StacktraceHelper.cs
  src/Elastic.Apm/Logging/AbstractLogger.cs
  src/Elastic.Apm/Logging/ConsoleLogger.cs
  src/Elastic.Apm/Logging/IApmLogger.cs
  src/Elastic.Apm/Logging/IApmLoggingExtensions.cs
  src/Elastic.Apm/Logging/LogLevel.cs
  src/Elastic.Apm/Logging/LogValuesFormatter.cs
  src/Elastic.Apm/Logging/ScopedLogger.cs
  src/Elastic.Apm/Model/Payload/Transaction.cs
  src/Elastic.Apm/Report/PayloadSender.cs
  test/Elastic.Apm.AspNetCore.Tests/MicrosoftExtensionsConfigTests.cs
  test/Elastic.Apm.Tests/ConfigTest.cs
  test/Elastic.Apm.Tests/HttpDiagnosticListenerTest.cs
  test/Elastic.Apm.Tests/LoggerTest.cs
  test/Elastic.Apm.Tests/Mocks/TestAgentComponents.cs
  test/Elastic.Apm.Tests/Mocks/TestAgentConfigurationReader.cs
  test/Elastic.Apm.Tests/Mocks/TestLogger.cs
Labels: [zube]: In Review
