Repository elastic/apm-agent-dotnet, pull requests merged in 2020-02, with the labels that each got.

#465 Add support for Server certificate verification
  docs/configuration.asciidoc
  src/Elastic.Apm/BackendComm/BackendCommUtils.cs
  src/Elastic.Apm/BackendComm/CentralConfigFetcher.cs
  src/Elastic.Apm/Config/AbstractConfigurationReader.cs
  src/Elastic.Apm/Config/AbstractConfigurationWithEnvFallbackReader.cs
  src/Elastic.Apm/Config/ConfigConsts.cs
  src/Elastic.Apm/Config/ConfigSnapshotFromReader.cs
  src/Elastic.Apm/Config/EnvironmentConfigurationReader.cs
  src/Elastic.Apm/Config/IConfigurationReader.cs
  test/Elastic.Apm.Tests/ConfigTests.cs
  test/Elastic.Apm.Tests/ConstructorTests.cs
  test/Elastic.Apm.Tests/Mocks/MockConfigSnapshot.cs
Labels: [zube]: In Progress

#731 [docs] Add EOL table
  RELEASING.md
  docs/index.asciidoc
  docs/upgrading.asciidoc
Labels: docs

#732 ci(jenkins): run opbeans validation per PR
  Jenkinsfile
Labels: automation, ci, enhancement

#743 ci(jenkins): apm-its-downstream params has changed
  Jenkinsfile
Labels: automation
