Repository elastic/apm-agent-dotnet, pull requests merged in 2020-11, with the labels that each got.

#1004 docs: add ifeval for 7.10 release
  docs/log-correlation.asciidoc
Labels: docs

#1005 [1.x] docs: add ifeval for 7.10 release #1004
  docs/log-correlation.asciidoc
Labels: docs

#1020 Add SampleRate to spans and transactions
  src/Elastic.Apm/Model/Span.cs
  src/Elastic.Apm/Model/Transaction.cs
  src/Elastic.Apm/Sampler.cs
  test/Elastic.Apm.Tests/SamplerTests.cs
  test/Elastic.Apm.Tests/TransactionSamplingTests.cs
Labels: v1.7.0

#1026 Adapt GcMetricsProvider to work on .NET5
  src/Elastic.Apm/Metrics/MetricsProvider/GcMetricsProvider.cs
  test/Elastic.Apm.Tests/ConfigTests.cs
  test/Elastic.Apm.Tests/MetricsTests.cs
Labels: v1.7.0

#1022 Bump System.Diagnostics.DiagnosticSource to newer version.
  sample/AspNetFullFrameworkSampleApp/AspNetFullFrameworkSampleApp.csproj
  sample/AspNetFullFrameworkSampleApp/Web.config
  src/Elastic.Apm/Elastic.Apm.csproj
  test/Elastic.Apm.Tests/HttpDiagnosticListenerTests.cs
Labels: v1.7.0

#1023 Fix cloud metadata
  docs/configuration.asciidoc
  sample/AspNetFullFrameworkSampleApp/Web.config
  sample/GrpcServiceSample/appsettings.json
  sample/SampleAspNetCoreApp/appsettings.json
  sample/WebApiSample/appsettings.json
  src/Elastic.Apm/Cloud/AwsCloudMetadataProvider.cs
  src/Elastic.Apm/Cloud/CloudMetadataProviderCollection.cs
  src/Elastic.Apm/Cloud/GcpCloudMetadataProvider.cs
  src/Elastic.Apm/Config/ConfigConsts.cs
  test/Elastic.Apm.Tests/Cloud/CloudMetadataProviderCollectionTests.cs
  test/Elastic.Apm.Tests/Cloud/GcpCloudMetadataProviderTests.cs
  test/Elastic.Apm.Tests/Mocks/MockConfigSnapshot.cs
Labels: v1.7.0

#848 Add CapturedStackFrame.ClassName
  src/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs
  src/Elastic.Apm/AgentComponents.cs
  src/Elastic.Apm/Api/CapturedStackFrame.cs
  src/Elastic.Apm/Api/Tracer.cs
  src/Elastic.Apm/Helpers/StacktraceHelper.cs
  src/Elastic.Apm/Model/ExecutionSegmentCommon.cs
  src/Elastic.Apm/Model/Span.cs
  src/Elastic.Apm/Model/Transaction.cs
  src/Elastic.Apm/Report/PayloadSenderV2.cs
  src/Elastic.Apm/ServerInfo/ApmServerInfo.cs
  src/Elastic.Apm/ServerInfo/ApmServerInfoProvider.cs
  src/Elastic.Apm/ServerInfo/ElasticVersion.cs
  src/Elastic.Apm/ServerInfo/IApmServerInfo.cs
  test/Elastic.Apm.Feature.Tests/FeatureContexts/ApiKeyFeatureContext.cs
  test/Elastic.Apm.Tests/BackendCommTests/CentralConfig/CentralConfigFetcherTests.cs
  test/Elastic.Apm.Tests/BackendCommTests/PayloadSenderTests.cs
  test/Elastic.Apm.Tests/ConstructorTests.cs
  test/Elastic.Apm.Tests/FilterTests.cs
  test/Elastic.Apm.Tests/LoggerTests.cs
  test/Elastic.Apm.Tests/Mocks/MockApmServerInfo.cs
  test/Elastic.Apm.Tests/Mocks/TestAgentComponents.cs
  test/Elastic.Apm.Tests/SamplerTests.cs
  test/Elastic.Apm.Tests/SerializationTests.cs
  test/Elastic.Apm.Tests/StackTraceTests.cs
Labels: v1.7.0

#1036 docs: fix links in changelog
  CHANGELOG.asciidoc
Labels: bug, docs, v1.7.0

#1037 [1.x] docs: fix links in changelog #1036
  CHANGELOG.asciidoc
Labels: docs, v1.7.0

#1046 Fetch APM server version only when not null
  src/Elastic.Apm/Report/PayloadSenderV2.cs
  test/Elastic.Apm.Tests/BackendCommTests/CentralConfig/CentralConfigFetcherTests.cs
  test/Elastic.Apm.Tests/BackendCommTests/PayloadSenderTests.cs
  test/Elastic.Apm.Tests/FilterTests.cs
  test/Elastic.Apm.Tests/LoggerTests.cs
  test/Elastic.Apm.Tests/Mocks/MockApmServerInfo.cs
  test/Elastic.Apm.Tests/Mocks/TestAgentComponents.cs
  test/Elastic.Apm.Tests/SamplerTests.cs
  test/Elastic.Apm.Tests/SerializationTests.cs
Labels: automated testing, bug

#1042 Add SqlClient diagnostic listeners for .NET 5.0
  src/Elastic.Apm.SqlClient/SqlClientDiagnosticSubscriber.cs
Labels: bug, v1.7.1

#1054 docs: clean up conditional code
  docs/log-correlation.asciidoc
Labels: agent-dotnet

#1053 AllowSynchronousIO when capturing request body
  docs/configuration.asciidoc
  src/Elastic.Apm.AspNetCore/Extensions/RequestExtentions.cs
  test/Elastic.Apm.AspNetCore.Tests/BodyCapturingTests.cs
  test/Elastic.Apm.AspNetCore.Tests/Helper.cs
Labels: agent-dotnet, bug, v1.7.1

#1060 HostBuilderExtensions.UseElasticApm: subscribe to `subscribers` params
  src/Elastic.Apm.Extensions.Hosting/Elastic.Apm.Extensions.Hosting.csproj
  src/Elastic.Apm.Extensions.Hosting/HostBuilderExtensions.cs
  test/Elastic.Apm.Extensions.Hosting.Tests/HostBuilderExtensionTests.cs
Labels: agent-dotnet, bug

#1052 Moving stack trace capturing away from application thread
  src/Elastic.Apm/Filters/SpanStackTraceCapturingFilter.cs
  src/Elastic.Apm/Model/Span.cs
  src/Elastic.Apm/Report/PayloadSenderV2.cs
  test/Elastic.Apm.Tests/Mocks/MockPayloadSender.cs
  test/Elastic.Apm.Tests/StackTraceTests.cs
Labels: agent-dotnet, performance, v1.7.1

#1057 Add GetLabel method
  docs/public-api.asciidoc
  src/Elastic.Apm/Api/IExecutionSegment.cs
  src/Elastic.Apm/Model/NoopSpan.cs
  src/Elastic.Apm/Model/NoopTransaction.cs
  src/Elastic.Apm/Model/Span.cs
  src/Elastic.Apm/Model/Transaction.cs
  test/Elastic.Apm.Tests/HttpDiagnosticListenerTests.cs
  test/Elastic.Apm.Tests/LabelTests.cs
Labels: agent-dotnet, enhancement, v1.7.1

#1058 Simplify getting assembly version
  src/Elastic.Apm.Extensions.Hosting/HostBuilderExtensions.cs
Labels: agent-dotnet, refactoring, v1.7.1

#1069 Prepare release 1.7.1
  CHANGELOG.asciidoc
  src/Directory.Build.props
Labels: agent-dotnet
