Repository elastic/apm-agent-dotnet, pull requests merged in 2020-12, with the labels that each got.

#1055 Read request body only up to maximum length
  sample/SampleAspNetCoreApp/Controllers/HomeController.cs
  src/Elastic.Apm.AspNetCore/Extensions/RequestExtentions.cs
  test/Elastic.Apm.AspNetCore.Tests/BodyCapturingTests.cs
Labels: agent-dotnet, performance, v1.7.2

#1065 Introduce ServerUrl and deprecate ServerUrls
  docs/configuration.asciidoc
  docs/public-api.asciidoc
  sample/AspNetFullFrameworkSampleApp/Global.asax.cs
  src/Elastic.Apm/BackendComm/BackendCommUtils.cs
  src/Elastic.Apm/BackendComm/CentralConfig/CentralConfigFetcher.cs
  src/Elastic.Apm/Config/AbstractConfigurationReader.cs
  src/Elastic.Apm/Config/AbstractConfigurationWithEnvFallbackReader.cs
  src/Elastic.Apm/Config/ConfigConsts.cs
  src/Elastic.Apm/Config/ConfigSnapshotFromReader.cs
  src/Elastic.Apm/Config/EnvironmentConfigurationReader.cs
  src/Elastic.Apm/Config/IConfigurationReader.cs
  src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListenerImplBase.cs
  src/Elastic.Apm/Report/PayloadSenderV2.cs
  src/Elastic.Apm/ServerInfo/ApmServerInfoProvider.cs
  test/Elastic.Apm.AspNetCore.Tests/MicrosoftExtensionsConfigTests.cs
  test/Elastic.Apm.Tests/ConfigTests.cs
  test/Elastic.Apm.Tests/ConstructorTests.cs
  test/Elastic.Apm.Tests/Mocks/MockConfigSnapshot.cs
Labels: agent-dotnet, deprecation, v1.8.0

#1062 Build automation for performing common tasks
  .gitignore
  Directory.Build.props
  ElasticApmAgent.sln
  build.bat
  build.sh
  build/nuget-icon.png
  build/scripts/Build.fs
  build/scripts/Paths.fs
  build/scripts/ReleaseNotes.fs
  build/scripts/Targets.fs
  build/scripts/Tooling.fs
  build/scripts/Versioning.fs
  build/scripts/scripts.fsproj
  sample/AspNetFullFrameworkSampleApp/AspNetFullFrameworkSampleApp.csproj
  sample/Directory.Build.props
  src/Directory.Build.props
  src/Elastic.Apm.Elasticsearch/Elastic.Apm.Elasticsearch.csproj
  test/Elastic.Apm.Feature.Tests/Elastic.Apm.Feature.Tests.csproj
Labels: agent-dotnet, automation, v1.7.2

#1068 Add git info to benchmarks
  test/Elastic.Apm.PerfTests/Helpers/GitInfo.cs
  test/Elastic.Apm.PerfTests/Program.cs
Labels: agent-dotnet

#1041 Don't subscribe IDiagnosticsSubscriber in ApmAgentExtensions.Subscribe(...) when agent is disabled
  docs/public-api.asciidoc
  src/Elastic.Apm.SqlClient/SqlClientDiagnosticSubscriber.cs
  src/Elastic.Apm/Agent.cs
  src/Elastic.Apm/ApmAgentExtensions.cs
  src/Elastic.Apm/DiagnosticSource/HttpDiagnosticsSubscriber.cs
  src/Elastic.Apm/DiagnosticSource/IDiagnosticsSubscriber.cs
  test/Elastic.Apm.Tests/EnabledAndRecordingTests.cs
Labels: agent-dotnet, refactoring, v1.7.2

#1048 Support for more k8s cgroup path patterns
  src/Elastic.Apm/Helpers/SystemInfoHelper.cs
  test/Elastic.Apm.DockerTests/ContainerIdCalculationTests.cs
Labels: agent-dotnet, enhancement, v1.7.2

#1056 Get the inner exception when capturing HttpUnhandledException
  sample/AspNetFullFrameworkSampleApp/AspNetFullFrameworkSampleApp.csproj
  sample/AspNetFullFrameworkSampleApp/Controllers/DatabaseController.cs
  sample/AspNetFullFrameworkSampleApp/Controllers/HomeController.cs
  sample/AspNetFullFrameworkSampleApp/WebformsException.aspx
  sample/AspNetFullFrameworkSampleApp/WebformsException.aspx.cs
  src/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs
  src/Elastic.Apm.AspNetFullFramework/OpenIdClaimTypes.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/ErrorsTests.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/TestsBase.cs
Labels: agent-dotnet, enhancement, v1.7.2

#1081 Fix NullRef on NoopTransaction.Custom
  src/Elastic.Apm/Model/NoopSpan.cs
  src/Elastic.Apm/Model/NoopTransaction.cs
  test/Elastic.Apm.Tests/EnabledAndRecordingTests.cs
Labels: agent-dotnet

#1088 [Doc] Fix TryGetLabel label typo
  docs/public-api.asciidoc
Labels: agent-dotnet

#1063 Add support for StackExchange.Redis
  CHANGELOG.asciidoc
  ElasticApmAgent.sln
  docs/setup.asciidoc
  docs/supported-technologies.asciidoc
  sample/StackExchangeRedisSample/Program.cs
  sample/StackExchangeRedisSample/StackExchangeRedisSample.csproj
  src/Elastic.Apm.StackExchange.Redis/ConnectionMultiplexerExtensions.cs
  src/Elastic.Apm.StackExchange.Redis/Elastic.Apm.StackExchange.Redis.csproj
  src/Elastic.Apm.StackExchange.Redis/ElasticApmProfiler.cs
  src/Elastic.Apm/Agent.cs
  src/Elastic.Apm/Api/ApiConstants.cs
  src/Elastic.Apm/Model/Span.cs
  src/Elastic.Apm/Model/Transaction.cs
  test/Elastic.Apm.StackExchange.Redis.Tests/ConnectionMultiplexerExtensionTests.cs
  test/Elastic.Apm.StackExchange.Redis.Tests/DockerFactAttribute.cs
  test/Elastic.Apm.StackExchange.Redis.Tests/Elastic.Apm.StackExchange.Redis.Tests.csproj
  test/Elastic.Apm.StackExchange.Redis.Tests/ProfilingSessionTests.cs
  test/Elastic.Apm.Tests/BasicAgentTests.cs
Labels: agent-dotnet, enhancement, v1.8.0

#1078 Fix: ASP.NET Core, enabled=false in appsetting does not disable public Agent API
  ElasticApmAgent.sln
  sample/SampleAspNetCoreApp/Controllers/HomeController.cs
  src/Elastic.Apm.AspNetCore/ApmMiddlewareExtension.cs
  src/Elastic.Apm.Extensions.Hosting/NetCoreLogger.cs
  src/Elastic.Apm/Agent.cs
  test/Elastic.Apm.AspNetCore.Static.Tests/ConfigTests.cs
  test/Elastic.Apm.AspNetCore.Static.Tests/Elastic.Apm.AspNetCore.Static.Tests.csproj
  test/Elastic.Apm.AspNetCore.Static.Tests/TestConfigs/appsettings_agentdisabled.json
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreBasicTests.cs
  test/Elastic.Apm.AspNetCore.Tests/Helper.cs
  test/Elastic.Apm.Tests/BasicAgentTests.cs
Labels: agent-dotnet, bug

#1090 only package projects explicitly marked <IsPackable>true</IsPackable>
  build/scripts/scripts.fsproj
  sample/Directory.Build.props
  sample/HttpListenerSample/HttpListenerSample.csproj
  src/Elastic.Apm.AspNetCore/Elastic.Apm.AspNetCore.csproj
  src/Elastic.Apm.AspNetFullFramework/Elastic.Apm.AspNetFullFramework.csproj
  src/Elastic.Apm.Elasticsearch/Elastic.Apm.Elasticsearch.csproj
  src/Elastic.Apm.EntityFramework6/Elastic.Apm.EntityFramework6.csproj
  src/Elastic.Apm.EntityFrameworkCore/Elastic.Apm.EntityFrameworkCore.csproj
  src/Elastic.Apm.Extensions.Hosting/Elastic.Apm.Extensions.Hosting.csproj
  src/Elastic.Apm.GrpcClient/Elastic.Apm.GrpcClient.csproj
  src/Elastic.Apm.NetCoreAll/Elastic.Apm.NetCoreAll.csproj
  src/Elastic.Apm.SqlClient/Elastic.Apm.SqlClient.csproj
  src/Elastic.Apm/Elastic.Apm.csproj
  src/ElasticApmStartupHook/ElasticApmStartupHook.csproj
  test/Directory.Build.props
Labels: agent-dotnet

#1083 [META 388] Add support for Azure App Service Cloud metadata
  src/Elastic.Apm/Cloud/AzureAppServiceMetadataProvider.cs
  src/Elastic.Apm/Cloud/CloudMetadataProviderCollection.cs
  src/Elastic.Apm/Helpers/EnvironmentHelper.cs
  test/Elastic.Apm.Tests/Cloud/AzureAppServiceMetadataProviderTests.cs
  test/Elastic.Apm.Tests/Cloud/CloudMetadataProviderCollectionTests.cs
Labels: agent-dotnet, enhancement, v1.8.0

#1092 Remove IConfigSnapshot parameter from CollectRequestBody
  src/Elastic.Apm.AspNetCore/ApmMiddleware.cs
  src/Elastic.Apm.AspNetCore/DiagnosticListener/AspNetCoreDiagnosticListener.cs
  src/Elastic.Apm.AspNetCore/DiagnosticListener/AspNetCoreErrorDiagnosticListener.cs
  src/Elastic.Apm.AspNetCore/Extensions/TransactionExtensions.cs
  src/Elastic.Apm.AspNetCore/WebRequestTransactionCreator.cs
Labels: agent-dotnet

#1082 Make SanitizeFieldNames config live changeable through central config
  src/Elastic.Apm/Api/Constraints/SanitizeAttribute.cs
  src/Elastic.Apm/Api/Request.cs
  src/Elastic.Apm/BackendComm/CentralConfig/CentralConfigFetcher.cs
  src/Elastic.Apm/BackendComm/CentralConfig/CentralConfigReader.cs
  src/Elastic.Apm/BackendComm/CentralConfig/CentralConfigResponseParser.cs
  src/Elastic.Apm/Filters/HeaderDictionarySanitizerFilter.cs
  src/Elastic.Apm/Filters/TransactionIgnoreUrlsFilter.cs
  src/Elastic.Apm/Report/PayloadSenderV2.cs
  src/Elastic.Apm/Report/Serialization/ElasticApmContractResolver.cs
  src/Elastic.Apm/Report/Serialization/HeaderDictionarySanitizerConverter.cs
  src/Elastic.Apm/Report/Serialization/PayloadItemSerializer.cs
  test/Elastic.Apm.AspNetCore.Tests/SanitizeFieldNamesTests.cs
  test/Elastic.Apm.Tests/LabelTests.cs
  test/Elastic.Apm.Tests/Mocks/MockPayloadSender.cs
  test/Elastic.Apm.Tests/Mocks/SerializerMockPayloadSender.cs
  test/Elastic.Apm.Tests/SerializationTests.cs
Labels: agent-dotnet

#1093 Add diff build target
  ElasticApmAgent.sln
  README.md
  build/README.md
  build/scripts/Targets.fs
  build/scripts/Tooling.fs
  dotnet-tools.json
Labels: agent-dotnet

#1087 Make transaction_ignore_urls central config compatible
  docs/configuration.asciidoc
  src/Elastic.Apm/Api/Request.cs
  src/Elastic.Apm/BackendComm/CentralConfig/CentralConfigFetcher.cs
  src/Elastic.Apm/BackendComm/CentralConfig/CentralConfigReader.cs
  src/Elastic.Apm/BackendComm/CentralConfig/CentralConfigResponseParser.cs
  src/Elastic.Apm/Filters/TransactionIgnoreUrlsFilter.cs
  src/Elastic.Apm/Report/PayloadSenderV2.cs
  test/Elastic.Apm.AspNetCore.Tests/TransactionIgnoreUrlsTest.cs
  test/Elastic.Apm.Tests/Mocks/MockPayloadSenderWithFilters.cs
Labels: agent-dotnet

#1095 Add private readonly IConfiguration variable
  docs/configuration.asciidoc
Labels: agent-dotnet

#1040 Add .NET 5 to Elastic.Apm.Tests
  .ci/docker/sdk-linux/Dockerfile
  .ci/windows/msbuild-tools.ps1
  .ci/windows/msbuild.bat
  .ci/windows/test-tools.ps1
  .ci/windows/tools.ps1
  Directory.Build.props
  global.json
  src/Elastic.Apm.SqlClient/SqlClientDiagnosticSubscriber.cs
  test/Elastic.Apm.SqlClient.Tests/Elastic.Apm.SqlClient.Tests.csproj
  test/Elastic.Apm.Tests/Elastic.Apm.Tests.csproj
  test/Elastic.Apm.Tests/MetricsTests.cs
Labels: agent-dotnet, automated testing, ci, v1.7.2

#1102 Check port is available when creating LocalServer
  test/Elastic.Apm.AspNetCore.Static.Tests/ConfigTests.cs
  test/Elastic.Apm.Tests/HttpDiagnosticListenerTests.cs
  test/Elastic.Apm.Tests/LoggerTests.cs
  test/Elastic.Apm.Tests/Mocks/LocalServer.cs
Labels: agent-dotnet, flaky test

#1096 Update log level based on central configuration and support "off" configuration
  src/Elastic.Apm/BackendComm/CentralConfig/CentralConfigFetcher.cs
  src/Elastic.Apm/Config/AbstractConfigurationReader.cs
  src/Elastic.Apm/Logging/ConsoleLogger.cs
  src/Elastic.Apm/Logging/IApmLogger.cs
  src/Elastic.Apm/Logging/LogLevelSwitch.cs
  test/Elastic.Apm.AspNetCore.Tests/TransactionNameTests.cs
  test/Elastic.Apm.Tests/BackendCommTests/CentralConfig/CentralConfigFetcherTests.cs
  test/Elastic.Apm.Tests/LoggerTests.cs
  test/Elastic.Apm.Tests/TestHelpers/LineWriterToLoggerAdaptor.cs
  test/Elastic.Apm.Tests/TestHelpers/LoggingTestBase.cs
Labels: agent-dotnet, enhancement, v1.8.0

#1012 Serialize payload to stream
  src/Elastic.Apm/Report/PayloadSenderV2.cs
  src/Elastic.Apm/Report/Serialization/PayloadItemSerializer.cs
  test/Elastic.Apm.Tests/BackendCommTests/CentralConfig/CentralConfigFetcherTests.cs
  test/Elastic.Apm.Tests/FilterTests.cs
  test/Elastic.Apm.Tests/LabelTests.cs
  test/Elastic.Apm.Tests/Mocks/InMemoryBlockingLogger.cs
  test/Elastic.Apm.Tests/Mocks/SerializerMockPayloadSender.cs
  test/Elastic.Apm.Tests/SerializationTests.cs
Labels: agent-dotnet, performance, v1.7.2

#1101 Wait for payload sender to queue events in tests
  Jenkinsfile
  src/Elastic.Apm/Api/Context.cs
  src/Elastic.Apm/Report/PayloadSenderV2.cs
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreBasicTests.cs
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreDiagnosticListenerTest.cs
  test/Elastic.Apm.AspNetCore.Tests/SanitizeFieldNamesTests.cs
  test/Elastic.Apm.AspNetCore.Tests/TraceIdWithActivityTests.cs
  test/Elastic.Apm.AspNetCore.Tests/TransactionIgnoreUrlsTest.cs
  test/Elastic.Apm.AspNetCore.Tests/TransactionNameTests.cs
  test/Elastic.Apm.Tests/ActivityIntegrationTests.cs
  test/Elastic.Apm.Tests/ApiTests/ApiTests.cs
  test/Elastic.Apm.Tests/ApiTests/ConvenientApiSpanTests.cs
  test/Elastic.Apm.Tests/ApiTests/ConvenientApiTransactionTests.cs
  test/Elastic.Apm.Tests/BackendCommTests/CentralConfig/CentralConfigFetcherTests.cs
  test/Elastic.Apm.Tests/EnabledAndRecordingTests.cs
  test/Elastic.Apm.Tests/ErrorTests.cs
  test/Elastic.Apm.Tests/HttpDiagnosticListenerTests.cs
  test/Elastic.Apm.Tests/Mocks/MockPayloadSender.cs
  test/Elastic.Apm.Tests/Mocks/SerializerMockPayloadSender.cs
  test/Elastic.Apm.Tests/TransactionIgnoreUrlsTests.cs
  test/Elastic.Apm.Tests/TransactionSamplingTests.cs
Labels: agent-dotnet

#1104 Add Microsoft.NET.Sdk.Razor package reference for ASP.NET Core 2.2
  .ci/windows/msbuild.bat
  sample/SampleAspNetCoreApp/SampleAspNetCoreApp.csproj
Labels: agent-dotnet
