Repository elastic/apm-agent-dotnet, pull requests merged in 2020-06, with the labels that each got.

#870 ci: run benchmark on a PR basis if comment
  Jenkinsfile
Labels: automation, ci

#329 Elasticsearch Client Instrumentation
  ElasticApmAgent.sln
  ElasticApmAgent.sln.DotSettings
  README.md
  sample/AspNetFullFrameworkSampleApp/AspNetFullFrameworkSampleApp.csproj
  sample/ElasticsearchSample/ElasticsearchSample.csproj
  sample/ElasticsearchSample/Program.cs
  src/Elastic.Apm.Elasticsearch/AuditDiagnosticsListener.cs
  src/Elastic.Apm.Elasticsearch/Elastic.Apm.Elasticsearch.csproj
  src/Elastic.Apm.Elasticsearch/ElasticsearchDiagnosticsListenerBase.cs
  src/Elastic.Apm.Elasticsearch/ElasticsearchDiagnosticsSubscriber.cs
  src/Elastic.Apm.Elasticsearch/HttpConnectionDiagnosticsListener.cs
  src/Elastic.Apm.Elasticsearch/RequestPipelineDiagnosticsListener.cs
  src/Elastic.Apm.Elasticsearch/SerializerDiagnosticsListener .cs
  src/Elastic.Apm.EntityFrameworkCore/EfCoreDiagnosticsSubscriber.cs
  src/Elastic.Apm/Agent.cs
  src/Elastic.Apm/Api/ApiConstants.cs
  src/Elastic.Apm/Elastic.Apm.csproj
  test/Elastic.Apm.Elasticsearch.Tests/Elastic.Apm.Elasticsearch.Tests.csproj
  test/Elastic.Apm.Elasticsearch.Tests/VirtualElasticsearchTests.cs
  test/Elastic.Apm.Feature.Tests/Elastic.Apm.Feature.Tests.csproj
  test/Elastic.Apm.Tests/BasicAgentTests.cs
  test/Elastic.Apm.Tests/Mocks/TestAgentComponents.cs
Labels: discuss, enhancement

#875 docs: Improve LogLevel docs
  .gitignore
  docs/configuration.asciidoc
Labels: docs

#891 [ci] opbeans requires tags with format v<major>.<minor>.<patch>
  Jenkinsfile
Labels: automation, ci
