Repository elastic/apm-agent-dotnet, pull requests merged in 2020-05, with the labels that each got.

#843 ci: timeout tweaks and no docker CI builds
  .ci/docker/buildtools-windows/Dockerfile
  .ci/docker/buildtools-windows/README.md
  Jenkinsfile
Labels: automation, bug, ci

#846 docs: Keep troubleshooting on one page
  docs/troubleshooting.asciidoc
Labels: docs

#864 ci: deploy to feedz.io
  Jenkinsfile
Labels: automation, ci
