Repository elastic/apm-agent-dotnet, pull requests merged in 2020-03, with the labels that each got.

#744 ci(jenkins): force the reinstall
  .ci/windows/msbuild-tools.ps1
Labels: automation

#723 ci(jenkins): Install VS2019Professional in the Windows CI Workers
  .ci/windows/msbuild-tools.ps1
  .ci/windows/msbuild.bat
Labels: automation, ci

#764 ci(jenkins): fix issues with target framework in linux/windows
  test/Elastic.Apm.SqlClient.Tests/Elastic.Apm.SqlClient.Tests.csproj
  test/Elastic.Apm.Tests/Elastic.Apm.Tests.csproj
Labels: automation, bug, ci

#763 ci(jenkins): enable test reporting for all the test stages
  Jenkinsfile
Labels: automation, ci, enhancement

#767 ci(jenkins): use JUnit testlogger to support multi-platform projects
  .ci/docker/sdk-linux/Dockerfile
  .ci/linux/convert.sh
  .ci/linux/test.sh
  .ci/windows/convert.ps1
  .ci/windows/test-iis.bat
  .ci/windows/test-tools.ps1
  .ci/windows/test.bat
  .ci/windows/testnet461.bat
  Jenkinsfile
Labels: automation, ci

#765 ci(jenkins): coverlet support in Linux
  .ci/docker/sdk-linux/README.md
  .ci/linux/test.sh
  Jenkinsfile
  coverlet.runsettings
  test/Elastic.Apm.AspNetCore.Tests/Elastic.Apm.AspNetCore.Tests.csproj
  test/Elastic.Apm.AspNetFullFramework.Tests/Elastic.Apm.AspNetFullFramework.Tests.csproj
  test/Elastic.Apm.DockerTests/Elastic.Apm.DockerTests.csproj
  test/Elastic.Apm.EntityFrameworkCore.Tests/Elastic.Apm.EntityFrameworkCore.Tests.csproj
  test/Elastic.Apm.Feature.Tests/Elastic.Apm.Feature.Tests.csproj
  test/Elastic.Apm.SqlClient.Tests/Elastic.Apm.SqlClient.Tests.csproj
  test/Elastic.Apm.Tests/Elastic.Apm.Tests.csproj
Labels: automation, ci

#770 ci(jenkins): apm-integration-testing stage earlier
  Jenkinsfile
Labels: automation, ci

#781 ci(jenkins): refactor remove sample projects
  .ci/linux/build.sh
  .ci/linux/remove-projects.sh
  .ci/linux/test.sh
Labels: automation

#790 docs: Add link to Agent/Server compatibility
  docs/intro.asciidoc
Labels: docs

#793 ci(jenkins): disable stages for only docs
  Jenkinsfile
Labels: automation
