Repository elastic/apm-agent-dotnet, pull requests merged in 2020-04, with the labels that each got.

#816 Increase timeout of Jenkins to 75 minutes
  Jenkinsfile
Labels: automation, ci

#817 ci(docs): docs folder to filter
  Jenkinsfile
Labels: automation, ci, docs

#813 docs: add dynamic badge
  docs/configuration.asciidoc
  docs/images/dynamic-config.svg
Labels: docs

#826 ci(jenkins): opbeans bump from the tag releases
  Jenkinsfile
Labels: automation
