Repository elastic/apm-agent-dotnet, pull requests merged in 2021-04, with the labels that each got.

#1225 Add instrumentation for Azure Service Bus
  .ci/docker/sdk-linux/Dockerfile
  .ci/linux/deploy.sh
  .ci/windows/test-tools.ps1
  .gitignore
  ElasticApmAgent.sln
  build/terraform/azure/service_bus/test_resources.tf
  docs/configuration.asciidoc
  docs/setup.asciidoc
  docs/supported-technologies.asciidoc
  sample/Elastic.Apm.Azure.ServiceBus.Sample/Elastic.Apm.Azure.ServiceBus.Sample.csproj
  sample/Elastic.Apm.Azure.ServiceBus.Sample/Program.cs
  src/Elastic.Apm.AspNetCore/DiagnosticListener/AspNetCoreDiagnosticListener.cs
  src/Elastic.Apm.Azure.ServiceBus/AzureMessagingServiceBusDiagnosticListener.cs
  src/Elastic.Apm.Azure.ServiceBus/AzureMessagingServiceBusDiagnosticsSubscriber.cs
  src/Elastic.Apm.Azure.ServiceBus/Elastic.Apm.Azure.ServiceBus.csproj
  src/Elastic.Apm.Azure.ServiceBus/MicrosoftAzureServiceBusDiagnosticListener.cs
  src/Elastic.Apm.Azure.ServiceBus/MicrosoftAzureServiceBusDiagnosticsSubscriber.cs
  src/Elastic.Apm.Azure.ServiceBus/ServiceBus.cs
  src/Elastic.Apm.Elasticsearch/ElasticsearchDiagnosticsListenerBase.cs
  src/Elastic.Apm.NetCoreAll/ApmMiddlewareExtension.cs
  src/Elastic.Apm.NetCoreAll/Elastic.Apm.NetCoreAll.csproj
  src/Elastic.Apm.NetCoreAll/HostBuilderExtensions.cs
  src/Elastic.Apm.SqlClient/SqlClientDiagnosticListener.cs
  src/Elastic.Apm.StackExchange.Redis/ElasticApmProfiler.cs
  src/Elastic.Apm/Api/ApiConstants.cs
  src/Elastic.Apm/ApmAgentExtensions.cs
  src/Elastic.Apm/BackendComm/CentralConfig/CentralConfigFetcher.cs
  src/Elastic.Apm/BackendComm/CentralConfig/CentralConfigReader.cs
  src/Elastic.Apm/BackendComm/CentralConfig/CentralConfigResponseParser.cs
  src/Elastic.Apm/Config/AbstractConfigurationReader.cs
  src/Elastic.Apm/Config/AbstractConfigurationWithEnvFallbackReader.cs
  src/Elastic.Apm/Config/ConfigConsts.cs
  src/Elastic.Apm/Config/ConfigSnapshotFromReader.cs
  src/Elastic.Apm/Config/EnvironmentConfigurationReader.cs
  src/Elastic.Apm/Config/IConfigurationReader.cs
  src/Elastic.Apm/Elastic.Apm.csproj
  src/Elastic.Apm/Model/ExecutionSegmentCommon.cs
  src/Elastic.Apm/Reflection/CascadePropertyFetcher.cs
  src/Elastic.Apm/Reflection/ExpressionBuilder.cs
  src/Elastic.Apm/Reflection/PropertyFetcher.cs
  src/Elastic.Apm/Reflection/PropertyFetcherCollection.cs
  test/Elastic.Apm.Azure.ServiceBus.Tests/Azure/AzureCredentials.cs
  test/Elastic.Apm.Azure.ServiceBus.Tests/Azure/AzureCredentialsFactAttribute.cs
  test/Elastic.Apm.Azure.ServiceBus.Tests/Azure/AzureServiceBusTestEnvironment.cs
  test/Elastic.Apm.Azure.ServiceBus.Tests/Azure/QueueScope.cs
  test/Elastic.Apm.Azure.ServiceBus.Tests/Azure/TopicScope.cs
  test/Elastic.Apm.Azure.ServiceBus.Tests/AzureMessagingServiceBusDiagnosticListenerTests.cs
  test/Elastic.Apm.Azure.ServiceBus.Tests/Elastic.Apm.Azure.ServiceBus.Tests.csproj
  test/Elastic.Apm.Azure.ServiceBus.Tests/MicrosoftAzureServiceBusDiagnosticListenerTests.cs
  test/Elastic.Apm.Azure.ServiceBus.Tests/Terraform/TerraformResourceException.cs
  test/Elastic.Apm.Azure.ServiceBus.Tests/Terraform/TerraformResources.cs
  test/Elastic.Apm.Benchmarks/PropertyFetcherBenchmark.cs
  test/Elastic.Apm.Tests.Utilities/Elastic.Apm.Tests.Utilities.csproj
  test/Elastic.Apm.Tests.Utilities/MockConfigSnapshot.cs
  test/Elastic.Apm.Tests.Utilities/SolutionPaths.cs
  test/Elastic.Apm.Tests/BackendCommTests/CentralConfig/CentralConfigFetcherTests.cs
  test/Elastic.Apm.Tests/ConstructorTests.cs
  test/Elastic.Apm.Tests/HelpersTests/PropertyFetcherTests.cs
Labels: enhancement, v1.9.0

#1252 Read recording key in AbstractConfigurationWithEnvFallbackReader
  src/Elastic.Apm/Config/AbstractConfigurationWithEnvFallbackReader.cs
  test/Elastic.Apm.Tests/ConfigTests.cs
Labels: bug, v1.10.0

#1248 clarify the globallabels format
  docs/configuration.asciidoc
Labels: agent-dotnet, docs, v1.10.0

#1247 Azure storage integration
  .ci/linux/deploy.sh
  ElasticApmAgent.sln
  build/terraform/azure/storage/test_resources.tf
  docs/setup.asciidoc
  docs/supported-technologies.asciidoc
  src/Elastic.Apm.Azure.Storage/AzureBlobStorageDiagnosticListener.cs
  src/Elastic.Apm.Azure.Storage/AzureBlobStorageDiagnosticsSubscriber.cs
  src/Elastic.Apm.Azure.Storage/AzureFileShareStorageDiagnosticListener.cs
  src/Elastic.Apm.Azure.Storage/AzureFileShareStorageDiagnosticsSubscriber.cs
  src/Elastic.Apm.Azure.Storage/AzureQueueStorageDiagnosticListener.cs
  src/Elastic.Apm.Azure.Storage/AzureQueueStorageDiagnosticsSubscriber.cs
  src/Elastic.Apm.Azure.Storage/Elastic.Apm.Azure.Storage.csproj
  src/Elastic.Apm.NetCoreAll/ApmMiddlewareExtension.cs
  src/Elastic.Apm.NetCoreAll/Elastic.Apm.NetCoreAll.csproj
  src/Elastic.Apm.NetCoreAll/HostBuilderExtensions.cs
  src/Elastic.Apm/Api/ApiConstants.cs
  src/Elastic.Apm/Elastic.Apm.csproj
  test/Elastic.Apm.Azure.ServiceBus.Tests/Azure/AzureServiceBusTestEnvironment.cs
  test/Elastic.Apm.Azure.ServiceBus.Tests/AzureMessagingServiceBusDiagnosticListenerTests.cs
  test/Elastic.Apm.Azure.ServiceBus.Tests/MicrosoftAzureServiceBusDiagnosticListenerTests.cs
  test/Elastic.Apm.Azure.Storage.Tests/AzureBlobStorageDiagnosticListenerTests.cs
  test/Elastic.Apm.Azure.Storage.Tests/AzureFileShareStorageDiagnosticListenerTests.cs
  test/Elastic.Apm.Azure.Storage.Tests/AzureQueueStorageDiagnosticListenerTests.cs
  test/Elastic.Apm.Azure.Storage.Tests/AzureStorageTestEnvironment.cs
  test/Elastic.Apm.Azure.Storage.Tests/BlobContainerScope.cs
  test/Elastic.Apm.Azure.Storage.Tests/Elastic.Apm.Azure.Storage.Tests.csproj
  test/Elastic.Apm.Azure.Storage.Tests/FileShareScope.cs
  test/Elastic.Apm.Tests.Utilities/Azure/AzureCredentials.cs
  test/Elastic.Apm.Tests.Utilities/Azure/AzureCredentialsFactAttribute.cs
  test/Elastic.Apm.Tests.Utilities/Elastic.Apm.Tests.Utilities.csproj
  test/Elastic.Apm.Tests.Utilities/Terraform/TerraformResourceException.cs
  test/Elastic.Apm.Tests.Utilities/Terraform/TerraformResources.cs
Labels: agent-dotnet, enhancement, v1.10.0

#1257 synchronize schema spec
  src/Elastic.Apm.Specification/specs/transaction.json
Labels: agent-dotnet, automation

#1260 synchronize schema spec
  src/Elastic.Apm.Specification/specs/error.json
  src/Elastic.Apm.Specification/specs/metadata.json
  src/Elastic.Apm.Specification/specs/transaction.json
Labels: agent-dotnet, automation

#1259 Move error capturing to Error event handler
  src/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs
Labels: agent-dotnet, bug, v1.10.0

#1262 Revert "Update dotnet sdk 5.0 docker image"
  .ci/docker/sdk-linux/Dockerfile
Labels: agent-dotnet

#1266 Update configuration.asciidoc
  docs/configuration.asciidoc
Labels: agent-dotnet, docs

#1268 Avoid array allocation in DiagnosticInitializer
  src/Elastic.Apm.AspNetCore/DiagnosticListener/AspNetCoreDiagnosticSubscriber.cs
  src/Elastic.Apm.AspNetCore/DiagnosticListener/AspNetCoreErrorDiagnosticsSubscriber.cs
  src/Elastic.Apm.Azure.ServiceBus/AzureMessagingServiceBusDiagnosticsSubscriber.cs
  src/Elastic.Apm.Azure.ServiceBus/MicrosoftAzureServiceBusDiagnosticsSubscriber.cs
  src/Elastic.Apm.Azure.Storage/AzureBlobStorageDiagnosticsSubscriber.cs
  src/Elastic.Apm.Azure.Storage/AzureFileShareStorageDiagnosticsSubscriber.cs
  src/Elastic.Apm.Azure.Storage/AzureQueueStorageDiagnosticsSubscriber.cs
  src/Elastic.Apm.EntityFrameworkCore/EfCoreDiagnosticsSubscriber.cs
  src/Elastic.Apm.GrpcClient/GrpcClientDiagnosticSubscriber.cs
  src/Elastic.Apm.SqlClient/SqlClientDiagnosticSubscriber.cs
  src/Elastic.Apm/DiagnosticSource/DiagnosticInitializer.cs
  src/Elastic.Apm/DiagnosticSource/HttpDiagnosticsSubscriber.cs
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreBasicTests.cs
Labels: agent-dotnet

#1270 Update configuration.asciidoc
  docs/configuration.asciidoc
Labels: agent-dotnet

#1269 Update CloudProviderSteps.cs
  test/Elastic.Apm.Feature.Tests/CloudProviderSteps.cs
Labels: agent-dotnet

#1265 fix third party middleware unable to obtain Request.Form Data bug
  src/Elastic.Apm.AspNetCore/Extensions/RequestExtentions.cs
Labels: agent-dotnet

#1215 Add MongoDb support
  .ci/linux/deploy.sh
  .ci/windows/dotnet.bat
  .ci/windows/prepare-test.bat
  ElasticApmAgent.sln
  docs/setup.asciidoc
  docs/supported-technologies.asciidoc
  src/Directory.Build.props
  src/Directory.Build.targets
  src/Elastic.Apm.MongoDb/Constants.cs
  src/Elastic.Apm.MongoDb/DiagnosticSource/MongoDiagnosticListener.cs
  src/Elastic.Apm.MongoDb/Elastic.Apm.MongoDb.csproj
  src/Elastic.Apm.MongoDb/EventPayload.cs
  src/Elastic.Apm.MongoDb/LICENSE
  src/Elastic.Apm.MongoDb/LICENSE_LOCAL
  src/Elastic.Apm.MongoDb/MongoDbDiagnosticsSubscriber.cs
  src/Elastic.Apm.MongoDb/MongoDbEventSubscriber.cs
  src/Elastic.Apm.MongoDb/MongoListener.cs
  src/Elastic.Apm.MongoDb/NOTICE
  src/Elastic.Apm.NetCoreAll/ApmMiddlewareExtension.cs
  src/Elastic.Apm.NetCoreAll/Elastic.Apm.NetCoreAll.csproj
  src/Elastic.Apm.NetCoreAll/HostBuilderExtensions.cs
  src/Elastic.Apm/Elastic.Apm.csproj
  src/Elastic.Apm/NOTICE
  test/Elastic.Apm.MongoDb.Tests/Elastic.Apm.MongoDb.Tests.csproj
  test/Elastic.Apm.MongoDb.Tests/Fixture/IMongoConfiguration.cs
  test/Elastic.Apm.MongoDb.Tests/Fixture/MongoFixture.cs
  test/Elastic.Apm.MongoDb.Tests/LICENSE
  test/Elastic.Apm.MongoDb.Tests/MongoApmTests.cs
  test/Elastic.Apm.MongoDb.Tests/mongo.replicaset.yml
  test/Elastic.Apm.Tests.Utilities/Elastic.Apm.Tests.Utilities.csproj
Labels: agent-dotnet, enhancement, v1.10.0

#1277 Implement Error exception cause
  src/Elastic.Apm/Api/CapturedException.cs
  src/Elastic.Apm/Helpers/StacktraceHelper.cs
  src/Elastic.Apm/Model/ExecutionSegmentCommon.cs
  test/Elastic.Apm.Tests/ErrorTests.cs
Labels: agent-dotnet, enhancement, v1.10.0

#1258 Create HTTP spans for known services
  src/Elastic.Apm.Azure.Storage/AzureBlobStorageDiagnosticListener.cs
  src/Elastic.Apm.Azure.Storage/AzureBlobStorageDiagnosticsSubscriber.cs
  src/Elastic.Apm.Azure.Storage/AzureFileShareStorageDiagnosticListener.cs
  src/Elastic.Apm.Azure.Storage/AzureQueueStorageDiagnosticListener.cs
  src/Elastic.Apm.Azure.Storage/BlobUrl.cs
  src/Elastic.Apm.Azure.Storage/MicrosoftAzureBlobStorageTracer.cs
  src/Elastic.Apm/Agent.cs
  src/Elastic.Apm/AgentComponents.cs
  src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListenerCoreImpl.cs
  src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListenerImplBase.cs
  src/Elastic.Apm/DiagnosticListeners/HttpTraceConfiguration.cs
  src/Elastic.Apm/DiagnosticListeners/IHttpSpanTracer.cs
  src/Elastic.Apm/DiagnosticSource/HttpDiagnosticsSubscriber.cs
  src/Elastic.Apm/Model/InstrumentationFlag.cs
  src/Elastic.Apm/Model/Span.cs
  test/Elastic.Apm.Azure.Storage.Tests/AzureBlobStorageDiagnosticListenerTests.cs
  test/Elastic.Apm.Azure.Storage.Tests/BlobStorageTestsBase.cs
  test/Elastic.Apm.Azure.Storage.Tests/Elastic.Apm.Azure.Storage.Tests.csproj
  test/Elastic.Apm.Azure.Storage.Tests/MicrosoftAzureBlobStorageTracerTests.cs
  test/Elastic.Apm.Tests/HttpDiagnosticListenerTests.cs
Labels: agent-dotnet

#1272 Update TestEnvironment.Docker dependencies
  ElasticApmAgent.sln
  test/Elastic.Apm.DatabaseTests.Common/DatabaseFixture.cs
  test/Elastic.Apm.DatabaseTests.Common/Elastic.Apm.DatabaseTests.Common.projitems
  test/Elastic.Apm.DatabaseTests.Common/Elastic.Apm.DatabaseTests.Common.shproj
  test/Elastic.Apm.SqlClient.Tests/EfCoreWithMsSqlTests.cs
  test/Elastic.Apm.SqlClient.Tests/Elastic.Apm.SqlClient.Tests.csproj
  test/Elastic.Apm.SqlClient.Tests/SqlClientListenerTests.cs
  test/Elastic.Apm.SqlClient.Tests/SqlServerCollection.cs
  test/Elastic.Apm.SqlClient.Tests/SqlServerFixture.cs
Labels: agent-dotnet
