Repository elastic/apm-agent-dotnet, pull requests merged in 2021-05, with the labels that each got.

#1275 Internalize Ben.Demystifier
  src/Elastic.Apm/Elastic.Apm.csproj
  src/Elastic.Apm/Filters/SpanStackTraceCapturingFilter.cs
  src/Elastic.Apm/Helpers/StacktraceHelper.cs
  src/Elastic.Apm/Libraries/Ben.Demystifier/EnhancedStackFrame.cs
  src/Elastic.Apm/Libraries/Ben.Demystifier/EnhancedStackTrace.Frames.cs
  src/Elastic.Apm/Libraries/Ben.Demystifier/EnhancedStackTrace.cs
  src/Elastic.Apm/Libraries/Ben.Demystifier/Enumerable/EnumerableIList.cs
  src/Elastic.Apm/Libraries/Ben.Demystifier/Enumerable/EnumeratorIList.cs
  src/Elastic.Apm/Libraries/Ben.Demystifier/Enumerable/IEnumerableIList.cs
  src/Elastic.Apm/Libraries/Ben.Demystifier/ExceptionExtensions.cs
  src/Elastic.Apm/Libraries/Ben.Demystifier/Internal/ILReader.cs
  src/Elastic.Apm/Libraries/Ben.Demystifier/Internal/PortablePdbReader.cs
  src/Elastic.Apm/Libraries/Ben.Demystifier/Internal/ReflectionHelper.cs
  src/Elastic.Apm/Libraries/Ben.Demystifier/ResolvedMethod.cs
  src/Elastic.Apm/Libraries/Ben.Demystifier/ResolvedParameter.cs
  src/Elastic.Apm/Libraries/Ben.Demystifier/StringBuilderExtentions.cs
  src/Elastic.Apm/Libraries/Ben.Demystifier/TypeNameHelper.cs
  src/Elastic.Apm/Libraries/Ben.Demystifier/ValueTupleResolvedParameter.cs
  src/Elastic.Apm/NOTICE
  test/Elastic.Apm.Tests/StackTraceTests.cs
Labels: agent-dotnet

#1286 Sanitize HTTP headers when the agent reads them
  src/Elastic.Apm.AspNetCore/WebRequestTransactionCreator.cs
  src/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs
  src/Elastic.Apm/Elastic.Apm.csproj
  src/Elastic.Apm/Filters/ErrorContextSanitizerFilter.cs
  src/Elastic.Apm/Filters/HeaderDictionarySanitizerFilter.cs
  src/Elastic.Apm/Model/Error.cs
  src/Elastic.Apm/Report/PayloadSenderV2.cs
  test/Elastic.Apm.AspNetCore.Tests/SanitizeFieldNamesTests.cs
  test/Elastic.Apm.Tests.Utilities/MockPayloadSender.cs
Labels: agent-dotnet

#1290 Add configured hostname
  src/Elastic.Apm/Api/System.cs
  src/Elastic.Apm/Helpers/SystemInfoHelper.cs
  test/Elastic.Apm.Tests/SerializationTests.cs
  test/Elastic.Apm.Tests/SystemInfoHelperTests.cs
Labels: agent-dotnet, bug, v1.10.0

#1292 Update dynamic values from central configuration
  src/Elastic.Apm/BackendComm/CentralConfig/CentralConfigReader.cs
  src/Elastic.Apm/Config/AbstractConfigurationReader.cs
Labels: agent-dotnet, bug, v1.10.0

#1293 Add charset to editorconfig
  .editorconfig
Labels: agent-dotnet

#1291 Use DotNet.Testcontainers to start MongoDb docker image
  src/Elastic.Apm.MongoDb/LICENSE
  test/Elastic.Apm.MongoDb.Tests/Elastic.Apm.MongoDb.Tests.csproj
  test/Elastic.Apm.MongoDb.Tests/Fixture/MongoDbTestcontainer.cs
  test/Elastic.Apm.MongoDb.Tests/Fixture/MongoDbTestcontainerConfiguration.cs
  test/Elastic.Apm.MongoDb.Tests/Fixture/MongoFixture.cs
  test/Elastic.Apm.MongoDb.Tests/mongo.replicaset.yml
Labels: agent-dotnet

#1297 Fix stacktrace limit length
  src/Elastic.Apm/Helpers/StacktraceHelper.cs
Labels: agent-dotnet

#1300 Add src/Elastic.Apm.MongoDb/LICENSE to .gitignore
  .gitignore
  src/Elastic.Apm.MongoDb/LICENSE
Labels: agent-dotnet

#1304 Fix traceparent header docs typo
  docs/configuration.asciidoc
Labels: agent-dotnet, docs

#1284 Use storage account in destination.service.resource
  src/Elastic.Apm.Azure.Storage/AzureBlobStorageDiagnosticListener.cs
  src/Elastic.Apm.Azure.Storage/AzureFileShareStorageDiagnosticListener.cs
  src/Elastic.Apm.Azure.Storage/AzureQueueStorageDiagnosticListener.cs
  src/Elastic.Apm.Azure.Storage/BlobUrl.cs
  src/Elastic.Apm.Azure.Storage/MicrosoftAzureBlobStorageTracer.cs
  src/Elastic.Apm.MongoDb/LICENSE
  test/Elastic.Apm.Azure.Storage.Tests/AzureFileShareStorageDiagnosticListenerTests.cs
  test/Elastic.Apm.Azure.Storage.Tests/BlobStorageTestsBase.cs
Labels: agent-dotnet

#1306 Do not capture HTTP child spans for Elasticsearch
  src/Elastic.Apm.Elasticsearch/ElasticsearchDiagnosticsListenerBase.cs
  src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListenerImplBase.cs
  src/Elastic.Apm/Model/InstrumentationFlag.cs
  test/Elastic.Apm.Elasticsearch.Tests/Elastic.Apm.Elasticsearch.Tests.csproj
  test/Elastic.Apm.Elasticsearch.Tests/ElasticsearchFixture.cs
  test/Elastic.Apm.Elasticsearch.Tests/ElasticsearchTestContainer.cs
  test/Elastic.Apm.Elasticsearch.Tests/ElasticsearchTestContainerConfiguration.cs
  test/Elastic.Apm.Elasticsearch.Tests/ElasticsearchTests.cs
Labels: agent-dotnet

#1299 Fix SanitizeFieldNamesTests
  src/Elastic.Apm/Filters/ErrorContextSanitizerFilter.cs
  src/Elastic.Apm/Filters/HeaderDictionarySanitizerFilter.cs
  test/Elastic.Apm.AspNetCore.Tests/SanitizeFieldNamesTests.cs
Labels: agent-dotnet

#1308 Create receive messaging span when inside transaction
  src/Elastic.Apm.Azure.ServiceBus/AzureMessagingServiceBusDiagnosticListener.cs
  src/Elastic.Apm.Azure.ServiceBus/MicrosoftAzureServiceBusDiagnosticListener.cs
  test/Elastic.Apm.Azure.ServiceBus.Tests/AzureMessagingServiceBusDiagnosticListenerTests.cs
  test/Elastic.Apm.Azure.ServiceBus.Tests/MicrosoftAzureServiceBusDiagnosticListenerTests.cs
Labels: agent-dotnet, bug, v1.10.0

#1288 Use TraceLogger as default logger in ASP.NET Full Framework
  docs/troubleshooting.asciidoc
  sample/AspNetFullFrameworkSampleApp/App_Start/LoggingConfig.cs
  sample/AspNetFullFrameworkSampleApp/Global.asax.cs
  src/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs
  src/Elastic.Apm/Config/AbstractConfigurationReader.cs
  src/Elastic.Apm/Config/ConfigConsts.cs
  src/Elastic.Apm/Logging/ConsoleLogger.cs
  src/Elastic.Apm/Logging/TraceLogger.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/HttpContextCurrentExecutionSegmentsContainerTests.cs
  test/Elastic.Apm.Tests.Utilities/TestingConfig.cs
Labels: agent-dotnet, enhancement, v1.10.0

#1312 Skip running Elasticsearch docker test when docker not available
  test/Elastic.Apm.AspNetFullFramework.Tests/TestsBase.cs
  test/Elastic.Apm.Elasticsearch.Tests/ElasticsearchTests.cs
  test/Elastic.Apm.StackExchange.Redis.Tests/ProfilingSessionTests.cs
  test/Elastic.Apm.Tests.Utilities/Docker/DockerFactAttribute.cs
Labels: agent-dotnet

#1301 fix: use .NET native SDK for build and test
  Jenkinsfile
Labels: agent-dotnet, bug, ci

#1305 Use Logger to log exception in AgentComponents initialization
  src/Elastic.Apm/AgentComponents.cs
Labels: agent-dotnet, bug, v1.10.0

#1298 Capture errors with startup hook auto instrumentation
  docs/setup.asciidoc
  sample/Elastic.Apm.StartupHook.Sample/Controllers/HomeController.cs
  src/Elastic.Apm.AspNetCore/DiagnosticListener/AspNetCoreDiagnosticListener.cs
  src/Elastic.Apm.AspNetCore/DiagnosticListener/AspNetCoreDiagnosticSubscriber.cs
  src/Elastic.Apm.StartupHook.Loader/Loader.cs
  src/ElasticApmAgentStartupHook/StartupHook.cs
  src/ElasticApmAgentStartupHook/StartupHookLogger.cs
  test/Elastic.Apm.StartupHook.Tests/StartupHookTests.cs
Labels: agent-dotnet, bug, v1.10.0

#1311 Fix nullref in Elastic.Apm.Extensions.Logging
  src/Elastic.Apm.Extensions.Logging/ApmErrorLogger.cs
  src/Elastic.Apm/Helpers/StacktraceHelper.cs
  test/Elastic.Apm.Extensions.Logging.Tests/CaptureApmErrorsTests.cs
Labels: agent-dotnet

#1314 Prepare release v.1.10.0
  CHANGELOG.asciidoc
  src/Directory.Build.props
Labels: agent-dotnet

#1318 Update setup.asciidoc - fix typo in MongoDb setup
  docs/setup.asciidoc
Labels: agent-dotnet
