Repository elastic/apm-agent-dotnet, pull requests merged in 2021-06, with the labels that each got.

#1316 Don't package Elastic.Apm.Specification
  src/Elastic.Apm.Specification/Elastic.Apm.Specification.csproj
Labels: agent-dotnet

#1320 synchronize schema spec
  src/Elastic.Apm.Specification/specs/metricset.json
Labels: agent-dotnet, automation

#1324 Update context.destination.address
  src/Elastic.Apm.Azure.Storage/BlobUrl.cs
  test/Elastic.Apm.Azure.Storage.Tests/AzureFileShareStorageDiagnosticListenerTests.cs
  test/Elastic.Apm.Azure.Storage.Tests/AzureQueueStorageDiagnosticListenerTests.cs
  test/Elastic.Apm.Azure.Storage.Tests/AzureStorageTestEnvironment.cs
  test/Elastic.Apm.Azure.Storage.Tests/BlobStorageTestsBase.cs
Labels: agent-dotnet, v1.10.1

#1327 Update docs
  docs/configuration.asciidoc
Labels: agent-dotnet, docs

#1326 Mark MicrosoftAzureBlobStorageTracer internal
  src/Elastic.Apm.Azure.Storage/MicrosoftAzureBlobStorageTracer.cs
Labels: agent-dotnet, breaking change, bug, v1.10.1

#1325 Update README
  README.md
Labels: agent-dotnet

#1328 fix spacing and cross references in docs
  docs/troubleshooting.asciidoc
  docs/upgrading.asciidoc
Labels: agent-dotnet, docs

#1302 Prefer W3C traceparent over elastic-apm-traceparent
  src/Elastic.Apm.AspNetCore/WebRequestTransactionCreator.cs
  test/Elastic.Apm.AspNetCore.Tests/DistributedTracingAspNetCoreTests.cs
Labels: agent-dotnet, v1.11.0

#1319 Documenting how to list 3rd party dependencies
  CONTRIBUTING.md
Labels: agent-dotnet

#1295 Update editorconfig naming rules
  .editorconfig
Labels: agent-dotnet

#1307 Update iis README
  .ci/docker/iis/Dockerfile
  .ci/docker/iis/README.md
  .ci/windows/msbuild.bat
Labels: agent-dotnet

#1335 [JJBB] increase shallow clone and tweak jjbb setup
  .ci/jobs/defaults.yml
Labels: agent-dotnet

#1334 Clarify ASP.NET getting started content
  docs/setup.asciidoc
Labels: agent-dotnet, v1.10.0

#1337 [1.10] Clarify ASP.NET getting started content (#1334)
  docs/setup.asciidoc
Labels: agent-dotnet, backport, docs

#1336 [1.x] Clarify ASP.NET getting started content (#1334)
  docs/setup.asciidoc
Labels: agent-dotnet, backport, docs

#1332 Add EOL for LICENSE and NOTICE
  .editorconfig
Labels: agent-dotnet

#1339 [ci] reduce archive artifacts
  Jenkinsfile
Labels: Team:Automation, agent-dotnet, automation, ci

#1310 Implement config to ignore the sampled flag in traceparent
  docs/configuration.asciidoc
  src/Elastic.Apm/BackendComm/CentralConfig/CentralConfigFetcher.cs
  src/Elastic.Apm/Config/AbstractConfigurationReader.cs
  src/Elastic.Apm/Config/AbstractConfigurationWithEnvFallbackReader.cs
  src/Elastic.Apm/Config/ConfigConsts.cs
  src/Elastic.Apm/Config/ConfigSnapshotFromReader.cs
  src/Elastic.Apm/Config/EnvironmentConfigurationReader.cs
  src/Elastic.Apm/Config/IConfigurationReader.cs
  src/Elastic.Apm/Model/Transaction.cs
  test/Elastic.Apm.AspNetCore.Tests/DistributedTracingAspNetCoreTests.cs
  test/Elastic.Apm.Tests.Utilities/MockConfigSnapshot.cs
  test/Elastic.Apm.Tests/ConstructorTests.cs
Labels: agent-dotnet, v1.11.0

#1338 Log cloud metadata provider failures at trace level
  src/Elastic.Apm/Cloud/AwsCloudMetadataProvider.cs
  src/Elastic.Apm/Cloud/AzureAppServiceMetadataProvider.cs
  src/Elastic.Apm/Cloud/AzureCloudMetadataProvider.cs
  src/Elastic.Apm/Cloud/GcpCloudMetadataProvider.cs
Labels: agent-dotnet

#1342 Add CosmosDb support - new
  ElasticApmAgent.sln
  build/terraform/azure/cosmosdb/test_resources.tf
  src/Elastic.Apm.Azure.CosmosDb/AzureCosmosDbDiagnosticsSubscriber.cs
  src/Elastic.Apm.Azure.CosmosDb/AzureCosmosDbTracer.cs
  src/Elastic.Apm.Azure.CosmosDb/Elastic.Apm.Azure.CosmosDb.csproj
  src/Elastic.Apm/Api/ApiConstants.cs
  src/Elastic.Apm/ApmAgentExtensions.cs
  src/Elastic.Apm/Elastic.Apm.csproj
  test/Elastic.Apm.Azure.CosmosDb.Tests/AzureCosmosDbTestEnvironment.cs
  test/Elastic.Apm.Azure.CosmosDb.Tests/DocumentItem.cs
  test/Elastic.Apm.Azure.CosmosDb.Tests/Elastic.Apm.Azure.CosmosDb.Tests.csproj
  test/Elastic.Apm.Azure.CosmosDb.Tests/MicrosoftAzureCosmosTests.cs
  test/Elastic.Apm.Azure.CosmosDb.Tests/MicrosoftAzureDocumentDbTests.cs
  test/Elastic.Apm.Tests.Utilities/Elastic.Apm.Tests.Utilities.csproj
Labels: agent-dotnet

#1345 synchronize schema spec
  src/Elastic.Apm.Specification/specs/span.json
Labels: agent-dotnet, automation

#1271 Breakdown metrics
  docs/metrics.asciidoc
  src/Elastic.Apm/AgentComponents.cs
  src/Elastic.Apm/Api/Tracer.cs
  src/Elastic.Apm/Metrics/IMetricsProvider.cs
  src/Elastic.Apm/Metrics/MetricSet.cs
  src/Elastic.Apm/Metrics/MetricsCollector.cs
  src/Elastic.Apm/Metrics/MetricsProvider/BreakdownMetricsProvider.cs
  src/Elastic.Apm/Metrics/MetricsProvider/CgroupMetricsProvider.cs
  src/Elastic.Apm/Metrics/MetricsProvider/FreeAndTotalMemoryProvider.cs
  src/Elastic.Apm/Metrics/MetricsProvider/GcMetricsProvider.cs
  src/Elastic.Apm/Metrics/MetricsProvider/ProcessTotalCpuTimeProvider.cs
  src/Elastic.Apm/Metrics/MetricsProvider/ProcessWorkingSetAndVirtualMemoryProvider.cs
  src/Elastic.Apm/Metrics/MetricsProvider/SystemTotalCpuProvider.cs
  src/Elastic.Apm/Model/Span.cs
  src/Elastic.Apm/Model/SpanTimerKey.cs
  src/Elastic.Apm/Model/Transaction.cs
  src/Elastic.Apm/Report/Serialization/MetricSetConverter.cs
  test/Elastic.Apm.Benchmarks/MetricsBenchmarks.cs
  test/Elastic.Apm.Tests.Utilities/MockPayloadSender.cs
  test/Elastic.Apm.Tests/BreakdownTests.cs
  test/Elastic.Apm.Tests/Metrics/CgroupMetricsProviderTests.cs
  test/Elastic.Apm.Tests/MetricsTests.cs
  test/Elastic.Apm.Tests/SamplerTests.cs
  test/Elastic.Apm.Tests/SerializationTests.cs
Labels: agent-dotnet

#1331 Create transactions for Azure Service Bus Processors
  src/Elastic.Apm.Azure.ServiceBus/AzureMessagingServiceBusDiagnosticListener.cs
  src/Elastic.Apm.Azure.ServiceBus/MicrosoftAzureServiceBusDiagnosticListener.cs
  test/Elastic.Apm.Azure.ServiceBus.Tests/Azure/QueueScope.cs
  test/Elastic.Apm.Azure.ServiceBus.Tests/AzureMessagingServiceBusDiagnosticListenerTests.cs
  test/Elastic.Apm.Azure.ServiceBus.Tests/MicrosoftAzureServiceBusDiagnosticListenerTests.cs
Labels: agent-dotnet, enhancement, v1.10.1

#1348 Prepare release
  .ci/linux/deploy.sh
  CHANGELOG.asciidoc
  src/Directory.Build.props
Labels: agent-dotnet
