Repository elastic/apm-agent-dotnet, pull requests merged in 2021-08, with the labels that each got.

#1356 Better logging in PayloadSenderV2 on task cancellation
  src/Elastic.Apm/BackendComm/BackendCommComponentBase.cs
  src/Elastic.Apm/Helpers/ExceptionUtils.cs
  src/Elastic.Apm/Model/Metadata.cs
  src/Elastic.Apm/Report/PayloadSenderV2.cs
Labels: agent-dotnet, refactoring

#1358 Propagate Trace context in exit spans
  src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListenerImplBase.cs
  test/Elastic.Apm.Elasticsearch.Tests/TraceContextTests.cs
Labels: agent-dotnet

#1366 Filter Jenkins branches
  .ci/jobs/defaults.yml
Labels: agent-dotnet

#1367 Make sure BreakdownMetricsProvider prints 1K warning only once per collection
  src/Elastic.Apm/Metrics/MetricsProvider/BreakdownMetricsProvider.cs
  test/Elastic.Apm.Tests/BreakdownTests.cs
Labels: agent-dotnet

#1362 Unset parentId if TraceContextIgnoreSampledFalse is active
  src/Elastic.Apm/Model/Transaction.cs
  test/Elastic.Apm.AspNetCore.Tests/DistributedTracingAspNetCoreTests.cs
Labels: agent-dotnet

#1368 Use 10K limit for CaptureBody similar to the Java agent
  src/Elastic.Apm.AspNetCore/Consts.cs
Labels: agent-dotnet

#1365 Update SystemInfoHelper.cs
  src/Elastic.Apm/Helpers/SystemInfoHelper.cs
Labels: agent-dotnet

#1374 Get Command and Key for StackExchange.Redis spans
  src/Elastic.Apm.StackExchange.Redis/ElasticApmProfiler.cs
  src/Elastic.Apm/Reflection/ExpressionBuilder.cs
  test/Elastic.Apm.StackExchange.Redis.Tests/ProfilingSessionTests.cs
Labels: enhancement, v1.12.0

#1377 Cleanup Azure resource groups
  Jenkinsfile
  test/Elastic.Apm.Azure.CosmosDb.Tests/AzureCosmosDbTestEnvironment.cs
  test/Elastic.Apm.Azure.ServiceBus.Tests/Azure/AzureServiceBusTestEnvironment.cs
  test/Elastic.Apm.Azure.Storage.Tests/AzureStorageTestEnvironment.cs
  test/Elastic.Apm.Tests.Utilities/Azure/AzureResourceException.cs
  test/Elastic.Apm.Tests.Utilities/Azure/AzureResources.cs
Labels: agent-dotnet

#1373 Small improvements
  src/Elastic.Apm/Metrics/MetricsProvider/BreakdownMetricsProvider.cs
  src/Elastic.Apm/Model/DbSpanCommon.cs
Labels: agent-dotnet

#1370 synchronize schema spec
  src/Elastic.Apm.Specification/specs/metadata.json
Labels: automation, agent-dotnet

#1473 Add Cosmos Db integrations to documentation
  docs/setup.asciidoc
  docs/supported-technologies.asciidoc
Labels: docs, agent-dotnet, v1.11.0

#1474 Add CosmosDB integration to NetCoreAll
  src/Elastic.Apm.NetCoreAll/ApmMiddlewareExtension.cs
  src/Elastic.Apm.NetCoreAll/Elastic.Apm.NetCoreAll.csproj
  src/Elastic.Apm.NetCoreAll/HostBuilderExtensions.cs
Labels: agent-dotnet
