Repository elastic/apm-agent-dotnet, pull requests merged in 2021-02, with the labels that each got.

#1159 Update public-api.asciidoc
  docs/public-api.asciidoc
Labels: agent-dotnet

#1163 Send destination info for embedded databases
  src/Elastic.Apm.SqlClient/SqlEventListener.cs
  src/Elastic.Apm/Model/DbSpanCommon.cs
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreBasicTests.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/DbSpanTests.cs
Labels: agent-dotnet

#1166 Mark LogLevel as dynamic in the config list
  docs/configuration.asciidoc
Labels: agent-dotnet

#1148 Fix scoped logger naming in GcMetricsProvider
  src/Elastic.Apm/Metrics/MetricsProvider/GcMetricsProvider.cs
Labels: agent-dotnet, bug, v1.7.2

#1162 Document "Never crash" approach
  CONTRIBUTING.md
Labels: agent-dotnet

#1168 docs: align config descriptions
  docs/configuration.asciidoc
Labels: agent-dotnet, docs

#1140 Remove coverlet.msbuild
  .ci/windows/msbuild.bat
  .ci/windows/test-iis.bat
  .ci/windows/test-tools.ps1
  .ci/windows/test.bat
  .ci/windows/testnet461.bat
  sample/SampleAspNetCoreApp/SampleAspNetCoreApp.csproj
  sample/WebApiSample/WebApiSample.csproj
  test/Directory.Build.props
  test/Elastic.Apm.AspNetCore.Static.Tests/Elastic.Apm.AspNetCore.Static.Tests.csproj
  test/Elastic.Apm.AspNetCore.Tests/Elastic.Apm.AspNetCore.Tests.csproj
  test/Elastic.Apm.Tests/Metrics/CgroupMetricsProviderTests.cs
  xunit.runner.json
Labels: agent-dotnet

#1177 DotnetProject.cs - handle path with space in it
  test/Elastic.Apm.StartupHook.Tests/DotnetProject.cs
Labels: agent-dotnet

#1174 [CI] Use the releaseNotification step
  Jenkinsfile
Labels: agent-dotnet, ci

#1179 [Doc] Adding some notes about disabled agent
  docs/configuration.asciidoc
  docs/public-api.asciidoc
Labels: agent-dotnet

#1181 Add StackExchange.Redis to releasable packages
  .ci/linux/deploy.sh
  README.md
Labels: agent-dotnet, v1.8.0

#1182 fix warnings
  test/Elastic.Apm.Extensions.Logging.Tests/CaptureApmErrorsTests.cs
  test/Elastic.Apm.Tests/ApiTests/ConvenientApiTransactionTests.cs
Labels: agent-dotnet

#1185 Skip duplicate when performing dotnet nuget push
  .ci/linux/deploy.sh
Labels: agent-dotnet

#1196 Add GCHeapStats_V2
  src/Elastic.Apm/Metrics/MetricsProvider/GcMetricsProvider.cs
Labels: agent-dotnet

#1186 Update Elasticsearch sample
  docs/supported-technologies.asciidoc
  sample/ElasticsearchSample/ElasticsearchSample.csproj
  sample/ElasticsearchSample/Program.cs
Labels: agent-dotnet

#1180 Add support for self signed certs
  docs/configuration.asciidoc
  src/Elastic.Apm/BackendComm/BackendCommUtils.cs
  src/Elastic.Apm/BackendComm/CentralConfig/CentralConfigFetcher.cs
  src/Elastic.Apm/Config/AbstractConfigurationReader.cs
  src/Elastic.Apm/Config/AbstractConfigurationWithEnvFallbackReader.cs
  src/Elastic.Apm/Config/ConfigConsts.cs
  src/Elastic.Apm/Config/ConfigSnapshotFromReader.cs
  src/Elastic.Apm/Config/EnvironmentConfigurationReader.cs
  src/Elastic.Apm/Config/IConfigurationReader.cs
  test/Elastic.Apm.Tests.MockApmServer/Elastic.Apm.Tests.MockApmServer.csproj
  test/Elastic.Apm.Tests.MockApmServer/InternalsVisibleTo.cs
  test/Elastic.Apm.Tests.MockApmServer/MockApmServer.cs
  test/Elastic.Apm.Tests.MockApmServer/cert.pfx
  test/Elastic.Apm.Tests.Utilities/MockConfigSnapshot.cs
  test/Elastic.Apm.Tests.Utilities/SolutionPaths.cs
  test/Elastic.Apm.Tests/ConfigTests.cs
  test/Elastic.Apm.Tests/ConstructorTests.cs
  test/Elastic.Apm.Tests/Elastic.Apm.Tests.csproj
  test/Elastic.Apm.Tests/ServerCertificateTests.cs
Labels: agent-dotnet, enhancement, v1.9.0

#1199 GC Metric tests: Also cover GenXSize metrics
  test/Elastic.Apm.Tests/MetricsTests.cs
Labels: agent-dotnet

#1198 Add TargetFramework NET5.0 to Elastic.Apm.AspNetCore & co
  sample/SampleAspNetCoreApp/SampleAspNetCoreApp.csproj
  sample/SampleAspNetCoreApp/Startup.cs
  sample/WebApiSample/Startup.cs
  sample/WebApiSample/WebApiSample.csproj
  src/Elastic.Apm.AspNetCore/ApmMiddlewareExtension.cs
  src/Elastic.Apm.AspNetCore/Elastic.Apm.AspNetCore.csproj
  src/Elastic.Apm.NetCoreAll/Elastic.Apm.NetCoreAll.csproj
  test/Elastic.Apm.AspNetCore.Static.Tests/Elastic.Apm.AspNetCore.Static.Tests.csproj
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreBasicTests.cs
  test/Elastic.Apm.AspNetCore.Tests/DistributedTracingAspNetCoreTests.cs
  test/Elastic.Apm.AspNetCore.Tests/Elastic.Apm.AspNetCore.Tests.csproj
Labels: agent-dotnet

#1192 Lazily access the agent in ElasticApmProfiler
  src/Elastic.Apm.StackExchange.Redis/ConnectionMultiplexerExtensions.cs
  src/Elastic.Apm.StackExchange.Redis/ElasticApmProfiler.cs
Labels: agent-dotnet, bug, v1.8.1

#1193 Runs tests in blame mode
  .ci/linux/test.sh
  .ci/windows/msbuild-tools.ps1
  .ci/windows/test.bat
  .ci/windows/testnet461.bat
  Jenkinsfile
  test/Elastic.Apm.AspNetCore.Tests/TraceIdWithActivityTests.cs
  test/Elastic.Apm.Tests.Utilities/LocalServer.cs
  test/Elastic.Apm.Tests.Utilities/MockPayloadSender.cs
  test/Elastic.Apm.Tests.Utilities/XUnit/CaptureRestoreActivityIdFormat.cs
  test/Elastic.Apm.Tests.Utilities/XUnit/XUnitLogger.cs
  test/Elastic.Apm.Tests/ActivityIntegrationTests.cs
  test/Elastic.Apm.Tests/ApiTests/ConvenientApiSpanTests.cs
  test/Elastic.Apm.Tests/ApiTests/ConvenientApiTransactionTests.cs
  test/Elastic.Apm.Tests/BackendCommTests/CentralConfig/CentralConfigFetcherTests.cs
  test/Elastic.Apm.Tests/ConfigTests.cs
  test/Elastic.Apm.Tests/ConstructorTests.cs
  test/Elastic.Apm.Tests/HttpDiagnosticListenerTests.cs
  test/Elastic.Apm.Tests/StackTraceTests.cs
Labels: agent-dotnet, automation, ci

#1201 Move InternalsVisibleTo into project files
  Directory.Build.props
  src/Elastic.Apm.AspNetCore/ApmMiddleware.cs
  src/Elastic.Apm.AspNetCore/Elastic.Apm.AspNetCore.csproj
  src/Elastic.Apm.AspNetFullFramework/Elastic.Apm.AspNetFullFramework.csproj
  src/Elastic.Apm.AspNetFullFramework/InternalsVisibleTo.cs
  src/Elastic.Apm.Extensions.Hosting/Elastic.Apm.Extensions.Hosting.csproj
  src/Elastic.Apm.Extensions.Hosting/NetCoreLogger.cs
  src/Elastic.Apm.Extensions.Logging/ApmErrorLoggingProvider.cs
  src/Elastic.Apm.Extensions.Logging/Elastic.Apm.Extensions.Logging.csproj
  src/Elastic.Apm.GrpcClient/Elastic.Apm.GrpcClient.csproj
  src/Elastic.Apm.GrpcClient/GrpcClientDiagnosticSubscriber.cs
  src/Elastic.Apm/Agent.cs
  src/Elastic.Apm/Elastic.Apm.csproj
  test/Elastic.Apm.AspNetCore.Tests/Elastic.Apm.AspNetCore.Tests.csproj
  test/Elastic.Apm.AspNetCore.Tests/Helper.cs
  test/Elastic.Apm.Tests.MockApmServer/Elastic.Apm.Tests.MockApmServer.csproj
  test/Elastic.Apm.Tests.MockApmServer/InternalsVisibleTo.cs
  test/Elastic.Apm.Tests.Utilities/Elastic.Apm.Tests.Utilities.csproj
  test/Elastic.Apm.Tests.Utilities/InternalsVisibleTo.cs
  test/Elastic.Apm.Tests/BasicAgentTests.cs
  test/Elastic.Apm.Tests/Elastic.Apm.Tests.csproj
Labels: agent-dotnet

#1202 Update editorconfig
  .editorconfig
Labels: agent-dotnet

#1206 Prepare 1.8.1 release
  CHANGELOG.asciidoc
  docs/upgrading.asciidoc
  src/Directory.Build.props
Labels: agent-dotnet

#1207 ci: do not interpolate values
  Jenkinsfile
Labels: agent-dotnet, bug, ci

#1205 [Doc] Improve docs on stack trace capturing
  docs/configuration.asciidoc
  docs/troubleshooting.asciidoc
Labels: agent-dotnet
