Repository elastic/apm-agent-dotnet, pull requests merged in 2021-11, with the labels that each got.

#1515 Ignore duplicate Diagnostic listener subscriptions
  src/Elastic.Apm.AspNetCore/DiagnosticListener/AspNetCoreDiagnosticSubscriber.cs
  src/Elastic.Apm.AspNetCore/DiagnosticListener/AspNetCoreErrorDiagnosticsSubscriber.cs
  src/Elastic.Apm.Azure.ServiceBus/AzureMessagingServiceBusDiagnosticsSubscriber.cs
  src/Elastic.Apm.Azure.ServiceBus/MicrosoftAzureServiceBusDiagnosticsSubscriber.cs
  src/Elastic.Apm.Azure.Storage/AzureBlobStorageDiagnosticsSubscriber.cs
  src/Elastic.Apm.Azure.Storage/AzureCoreDiagnosticListener.cs
  src/Elastic.Apm.Azure.Storage/AzureFileShareStorageDiagnosticsSubscriber.cs
  src/Elastic.Apm.Azure.Storage/AzureQueueStorageDiagnosticsSubscriber.cs
  src/Elastic.Apm.Elasticsearch/ElasticsearchDiagnosticsSubscriber.cs
  src/Elastic.Apm.EntityFrameworkCore/EfCoreDiagnosticListener.cs
  src/Elastic.Apm.EntityFrameworkCore/EfCoreDiagnosticsSubscriber.cs
  src/Elastic.Apm.GrpcClient/GrpcClientDiagnosticSubscriber.cs
  src/Elastic.Apm.MongoDb/MongoDbDiagnosticsSubscriber.cs
  src/Elastic.Apm.SqlClient/SqlClientDiagnosticListener.cs
  src/Elastic.Apm.SqlClient/SqlClientDiagnosticSubscriber.cs
  src/Elastic.Apm/Agent.cs
  src/Elastic.Apm/AgentComponents.cs
  src/Elastic.Apm/DiagnosticListeners/DiagnosticListenerBase.cs
  src/Elastic.Apm/DiagnosticSource/DiagnosticInitializer.cs
  src/Elastic.Apm/DiagnosticSource/HttpDiagnosticsSubscriber.cs
  src/Elastic.Apm/DiagnosticSource/IDiagnosticListener.cs
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreBasicTests.cs
  test/Elastic.Apm.SqlClient.Tests/SqlClientListenerTests.cs
  test/Elastic.Apm.Tests/DiagnosticSource/DiagnosticListenerTests.cs
Labels: agent-dotnet

#1538 Collect .NET Framework GC metrics only when filtering supported
  src/Elastic.Apm/Metrics/MetricsProvider/GcMetricsProvider.cs
Labels: bug, agent-dotnet, v1.12.0

#1536 Improve Performance counter handling
  docs/metrics.asciidoc
  src/Elastic.Apm/Metrics/MetricsProvider/SystemTotalCpuProvider.cs
Labels: bug, agent-dotnet, v1.12.0

#1528 Platform detection: Handle .NET 6
  src/Elastic.Apm.SqlClient/SqlClientDiagnosticSubscriber.cs
  src/Elastic.Apm/Api/Service.cs
  src/Elastic.Apm/Helpers/PlatformDetection.cs
  src/Elastic.Apm/Metrics/MetricsProvider/GcMetricsProvider.cs
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreBasicTests.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/MetadataTests.cs
  test/Elastic.Apm.Tests/HelpersTests/PlatformDetectionTests.cs
  test/Elastic.Apm.Tests/HttpDiagnosticListenerTests.cs
  test/Elastic.Apm.Tests/MetricsTests.cs
  test/Elastic.Apm.Tests/NetCoreAndNet5Fact.cs
  test/Elastic.Apm.Tests/NetCoreAndNetFact.cs
Labels: agent-dotnet

#1543 synchronize schema spec
  src/Elastic.Apm.Specification/specs/error.json
Labels: automation, agent-dotnet

#1546 Update profiler auto instrumentation docs
  docs/integrations.asciidoc
  docs/setup-auto-instrumentation.asciidoc
  docs/supported-technologies.asciidoc
  src/Elastic.Apm.Profiler.IntegrationsGenerator/Program.cs
Labels: agent-dotnet

#1542 Use Traceparent binary format name for Kafka integration
  src/Elastic.Apm.Profiler.Managed/Integrations/Kafka/KafkaHelper.cs
  src/Elastic.Apm/DistributedTracing/TraceContext.cs
  test/Elastic.Apm.Profiler.Managed.Tests/Kafka/KafkaTests.cs
Labels: agent-dotnet

#1550 Tidy up docs
  docs/setup-auto-instrumentation.asciidoc
Labels: agent-dotnet

#1540 Stop recording transaction metrics
  src/Elastic.Apm/Metrics/MetricsProvider/BreakdownMetricsProvider.cs
  test/Elastic.Apm.Tests.MockApmServer/MetricsAssertValid.cs
  test/Elastic.Apm.Tests/BreakdownTests.cs
Labels: agent-dotnet

#1518 Implement User-Agent spec for transport
  src/Elastic.Apm/BackendComm/BackendCommUtils.cs
  test/Elastic.Apm.Feature.Tests/ApiKeySteps.cs
  test/Elastic.Apm.Feature.Tests/CloudProviderSteps.cs
  test/Elastic.Apm.Feature.Tests/ConfigurationSteps.cs
  test/Elastic.Apm.Feature.Tests/Features/user_agent.feature
  test/Elastic.Apm.Feature.Tests/OutcomeSteps.cs
  test/Elastic.Apm.Feature.Tests/PayloadCollector.cs
  test/Elastic.Apm.Feature.Tests/TestConfiguration.cs
  test/Elastic.Apm.Feature.Tests/UserAgentSteps.cs
  test/Elastic.Apm.Tests/BackendCommTests/PayloadSenderTests.cs
Labels: automation, agent-dotnet

#1511 Implement DroppedSpanStats
  sample/AspNetFullFrameworkSampleApp/Controllers/DatabaseController.cs
  src/Elastic.Apm.Azure.ServiceBus/AzureMessagingServiceBusDiagnosticListener.cs
  src/Elastic.Apm.Azure.ServiceBus/MicrosoftAzureServiceBusDiagnosticListener.cs
  src/Elastic.Apm.GrpcClient/GrpcClientDiagnosticListener.cs
  src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListenerImplBase.cs
  src/Elastic.Apm/Helpers/UrlUtils.cs
  src/Elastic.Apm/Model/DbSpanCommon.cs
  src/Elastic.Apm/Model/DroppedSpanStats.cs
  src/Elastic.Apm/Model/Span.cs
  src/Elastic.Apm/Model/Transaction.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/HttpContextCurrentExecutionSegmentsContainerTests.cs
  test/Elastic.Apm.Azure.ServiceBus.Tests/AzureMessagingServiceBusDiagnosticListenerTests.cs
  test/Elastic.Apm.Azure.ServiceBus.Tests/MicrosoftAzureServiceBusDiagnosticListenerTests.cs
  test/Elastic.Apm.Benchmarks/DroppedSpansStats.cs
  test/Elastic.Apm.Tests/ApiTests/ExitSpanTests.cs
  test/Elastic.Apm.Tests/DroppedSpansStatsTests.cs
Labels: agent-dotnet

#1555 Documentation improvements
  docs/integrations.asciidoc
  docs/packages.asciidoc
  docs/public-api.asciidoc
  docs/setup-auto-instrumentation.asciidoc
  docs/supported-technologies.asciidoc
  src/Elastic.Apm.Profiler.IntegrationsGenerator/Program.cs
  src/Elastic.Apm.Profiler.IntegrationsGenerator/Target.cs
  src/Elastic.Apm.Profiler.Managed.Core/InstrumentAttribute.cs
  src/Elastic.Apm.Profiler.Managed/Integrations/AdoNet/AdoNetTypeNames.cs
  src/Elastic.Apm.Profiler.Managed/Integrations/AspNet/ElasticApmModuleIntegration.cs
Labels: agent-dotnet, v1.12.0

#1548 Add auto instrumentation for RabbitMQ
  ElasticApmAgent.sln
  Makefile.toml
  docs/integrations.asciidoc
  sample/RabbitMqSample/Program.cs
  sample/RabbitMqSample/RabbitMqSample.csproj
  src/Elastic.Apm.Profiler.Managed/ExecutionSegmentExtensions.cs
  src/Elastic.Apm.Profiler.Managed/Integrations/RabbitMq/BasicDeliverIntegration.cs
  src/Elastic.Apm.Profiler.Managed/Integrations/RabbitMq/BasicGetIntegration.cs
  src/Elastic.Apm.Profiler.Managed/Integrations/RabbitMq/BasicPublishIntegration.cs
  src/Elastic.Apm.Profiler.Managed/Integrations/RabbitMq/ContextPropagation.cs
  src/Elastic.Apm.Profiler.Managed/Integrations/RabbitMq/IBasicGetResult.cs
  src/Elastic.Apm.Profiler.Managed/Integrations/RabbitMq/IBasicProperties.cs
  src/Elastic.Apm.Profiler.Managed/Integrations/RabbitMq/IBody.cs
  src/Elastic.Apm.Profiler.Managed/Integrations/RabbitMq/RabbitMQIntegration.cs
  src/Elastic.Apm.Profiler.Managed/Logger.cs
  src/Elastic.Apm.Profiler.Managed/integrations.yml
  src/Elastic.Apm/Helpers/TimeUtils.cs
  src/Elastic.Apm/Model/Span.cs
  test/Elastic.Apm.Profiler.Managed.Tests/RabbitMq/RabbitMqFixture.cs
  test/Elastic.Apm.Profiler.Managed.Tests/RabbitMq/RabbitMqTests.cs
  test/Elastic.Apm.Tests.MockApmServer/AssertValidExtensions.cs
Labels: enhancement, agent-dotnet, v1.12.0

#1549 Add IgnoreMessageQueues support for Kafka integration
  sample/KafkaSample/Consumer.cs
  sample/KafkaSample/Program.cs
  src/Elastic.Apm.Profiler.Managed/CallTarget/Handlers/EndMethodHandler`1.cs
  src/Elastic.Apm.Profiler.Managed/Integrations/Kafka/KafkaConstants.cs
  src/Elastic.Apm.Profiler.Managed/Integrations/Kafka/KafkaConsumerCloseIntegration.cs
  src/Elastic.Apm.Profiler.Managed/Integrations/Kafka/KafkaConsumerConsumeIntegration.cs
  src/Elastic.Apm.Profiler.Managed/Integrations/Kafka/KafkaConsumerDisposeIntegration.cs
  src/Elastic.Apm.Profiler.Managed/Integrations/Kafka/KafkaConsumerUnsubscribeIntegration.cs
  src/Elastic.Apm.Profiler.Managed/Integrations/Kafka/KafkaHeadersCollection.cs
  src/Elastic.Apm.Profiler.Managed/Integrations/Kafka/KafkaIntegration.cs
  src/Elastic.Apm.Profiler.Managed/Integrations/Kafka/KafkaProduceAsyncIntegration.cs
  src/Elastic.Apm.Profiler.Managed/Integrations/Kafka/KafkaProduceSyncDeliveryHandlerIntegration.cs
  src/Elastic.Apm.Profiler.Managed/Integrations/Kafka/KafkaProduceSyncIntegration.cs
  test/Elastic.Apm.Profiler.Managed.Tests/Kafka/KafkaTests.cs
  test/Elastic.Apm.Tests.MockApmServer/AssertValidExtensions.cs
Labels: agent-dotnet, v1.12.0

#1557 Handle enabled/recording=false on Tracer.CaptureError
  src/Elastic.Apm/Api/Tracer.cs
  src/Elastic.Apm/BackendComm/BackendCommComponentBase.cs
  test/Elastic.Apm.Tests/EnabledAndRecordingTests.cs
Labels: bug, agent-dotnet

#1560 Prepare for 1.12.0 release
  CHANGELOG.asciidoc
  build/scripts/Build.fs
  docs/integrations.asciidoc
  docs/supported-technologies.asciidoc
  docs/upgrading.asciidoc
  src/Directory.Build.props
  src/Elastic.Apm.Profiler.IntegrationsGenerator/Program.cs
  src/Elastic.Apm.Profiler.Managed/integrations.yml
  src/elastic_apm_profiler/Cargo.toml
  src/elastic_apm_profiler/README
Labels: agent-dotnet

#1564 Set span context destination service name and type to empty string
  src/Elastic.Apm/Api/Destination.cs
  test/Elastic.Apm.Tests/SerializationTests.cs
Labels: bug, agent-dotnet, v1.12.1

#1565 Prepare release 1.12.1
  CHANGELOG.asciidoc
  src/Directory.Build.props
  src/elastic_apm_profiler/Cargo.toml
Labels: agent-dotnet

#1567 bump versions in integrations.yml
  src/Elastic.Apm.Profiler.Managed/integrations.yml
Labels: agent-dotnet

#1568 Add documentation for environment variables for Windows services
  docs/configuration.asciidoc
Labels: docs, agent-dotnet

#1569 Add CosmosDb package to README
  README.md
Labels: agent-dotnet

#1576 Add trace log with callstack in Agent.Setup
  src/Elastic.Apm/Agent.cs
Labels: agent-dotnet

#1554 Test major.minor version only when asserting framework version
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreBasicTests.cs
Labels: agent-dotnet
