Repository elastic/apm-agent-dotnet, pull requests merged in 2021-01, with the labels that each got.

#1108 Fix flaky tests
  test/Elastic.Apm.Tests/HttpDiagnosticListenerTests.cs
  test/Elastic.Apm.Tests/LabelTests.cs
  test/Elastic.Apm.Tests/Mocks/TestLogger.cs
Labels: agent-dotnet

#1107 Add SourceLink and XML documentation to all packages
  src/Directory.Build.props
  src/Elastic.Apm.AspNetCore/Extensions/ListExtensions.cs
  src/Elastic.Apm.AspNetCore/Extensions/RequestExtentions.cs
  src/Elastic.Apm/Agent.cs
  src/Elastic.Apm/Api/DistributedTracingData.cs
  src/Elastic.Apm/Api/Http.cs
  src/Elastic.Apm/Api/IExecutionSegment.cs
  src/Elastic.Apm/Api/ITracer.cs
  src/Elastic.Apm/DistributedTracing/TraceContext.cs
  src/Elastic.Apm/Helpers/TimeExtensions.cs
  src/Elastic.Apm/Metrics/MetricsProvider/FreeAndTotalMemoryProvider.cs
Labels: agent-dotnet

#1097 Use ConfigureAwait(false)
  src/Elastic.Apm/BackendComm/BackendCommComponentBase.cs
  src/Elastic.Apm/BackendComm/CentralConfig/CentralConfigFetcher.cs
  src/Elastic.Apm/Helpers/ExceptionUtils.cs
  src/Elastic.Apm/Report/PayloadSenderV2.cs
  test/Elastic.Apm.Tests/LoggerTests.cs
  test/Elastic.Apm.Tests/Mocks/InMemoryBlockingLogger.cs
Labels: agent-dotnet

#1112 Update Specification attributes for MockApmServer
  test/Elastic.Apm.Tests.MockApmServer/ErrorDto.cs
  test/Elastic.Apm.Tests.MockApmServer/MetadataDto.cs
  test/Elastic.Apm.Tests.MockApmServer/MetricSetDto.cs
  test/Elastic.Apm.Tests.MockApmServer/SpanDto.cs
  test/Elastic.Apm.Tests.MockApmServer/TransactionDto.cs
Labels: agent-dotnet

#1111 Add XML docs to IConfigurationReader
  src/Elastic.Apm/Config/IConfigurationReader.cs
Labels: agent-dotnet

#1105 Fix compile warnings
  sample/StackExchangeRedisSample/StackExchangeRedisSample.csproj
  test/Elastic.Apm.Grpc.Tests/Elastic.Apm.Grpc.Tests.csproj
  test/Elastic.Apm.Grpc.Tests/GrpcTests.cs
  test/Elastic.Apm.Grpc.Tests/SampleAppHostBuilder.cs
  test/Elastic.Apm.Grpc.Tests/Services/GreeterService.cs
  test/Elastic.Apm.StackExchange.Redis.Tests/Elastic.Apm.StackExchange.Redis.Tests.csproj
Labels: agent-dotnet

#1115 Access Request.InputStream only when SOAP header present
  sample/AspNetFullFrameworkSampleApp/App_Start/WebApiConfig.cs
  sample/AspNetFullFrameworkSampleApp/Asmx/Health.asmx.cs
  sample/AspNetFullFrameworkSampleApp/Controllers/WebApiController.cs
  src/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs
  src/Elastic.Apm.AspNetFullFramework/Extensions/SoapRequest.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/Soap/SoapParsingTests.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/Soap/SoapRequestTests.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/WebApiTests.cs
Labels: agent-dotnet, bug, v1.7.2

#1091 Only add AspNetCoreErrorDiagnosticsSubscriber if not present
  src/Elastic.Apm.AspNetCore/ApmMiddlewareExtension.cs
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreBasicTests.cs
Labels: agent-dotnet

#1118 Fix GrpcClientDiagnosticListener memory issue
  src/Elastic.Apm.GrpcClient/GrpcClientDiagnosticListener.cs
  src/Elastic.Apm.GrpcClient/GrpcClientDiagnosticSubscriber.cs
  test/Elastic.Apm.Grpc.Tests/GrpcTests.cs
Labels: agent-dotnet, bug

#1124 Ensure ETW session is deleted when GcMetricsProvider is disposed
  src/Elastic.Apm/Metrics/MetricsProvider/GcMetricsProvider.cs
  test/Elastic.Apm.Tests/MetricsTests.cs
Labels: agent-dotnet, bug, v1.7.2

#1123 Update bug report
  .github/ISSUE_TEMPLATE/Bug_report.md
Labels: agent-dotnet

#1125 Add assembly redirect for System.Runtime.CompilerServices.Unsafe
  sample/AspNetFullFrameworkSampleApp/Web.config
Labels: agent-dotnet

#1133 [CI] Enable slack notifications for releases
  Jenkinsfile
Labels: agent-dotnet, automation, ci

#1137 Set _isConfigured flag also with implicit agent initialization
  ElasticApmAgent.sln
  src/Elastic.Apm/Agent.cs
  test/Elastic.Apm.StaticExplicitInitialization.Tests/Elastic.Apm.StaticExplicitInitialization.Tests.csproj
  test/Elastic.Apm.StaticExplicitInitialization.Tests/StaticImplicitInitializationTests.cs
  test/Elastic.Apm.StaticImplicitInitialization.Tests/Elastic.Apm.StaticImplicitInitialization.Tests.csproj
  test/Elastic.Apm.StaticImplicitInitialization.Tests/ImplicitInitializationTests.cs
  test/Elastic.Apm.Tests.Utilities/InternalsVisibleTo.cs
Labels: agent-dotnet

#1139 fix doc markup
  docs/public-api.asciidoc
Labels: agent-dotnet

#1141 Add link to Stack Exchange redis in get started TOC
  docs/setup.asciidoc
Labels: docs, v1.8.0

#1142 [DOCS] Fixes link typo in Get started section
  docs/setup.asciidoc
Labels: agent-dotnet, docs

#1109 Fix nullref in MetricsCollector with custom IConfigurationReader
  src/Elastic.Apm/Helpers/WildcardMatcher.cs
  src/Elastic.Apm/Metrics/MetricsCollector.cs
  test/Elastic.Apm.Tests/MetricsTests.cs
  test/Elastic.Apm.Tests/WildcardMatcherTests.cs
Labels: agent-dotnet

#1143 GitHub action to automatically add milestoned issues to the project
  .github/workflows/addToProject.yml
Labels: agent-dotnet

#1138 Allow ElasticApmStartupHook to work with System.Diagnostics.DiagnosticSource 4 and 5
  .ci/linux/build.sh
  .ci/linux/deploy.sh
  .ci/linux/release.sh
  .ci/windows/msbuild.bat
  .ci/windows/test-iis.bat
  .ci/windows/test-tools.ps1
  .ci/windows/testnet461.bat
  ElasticApmAgent.sln
  Jenkinsfile
  build.sh
  build/docker/Dockerfile
  build/scripts/Build.fs
  build/scripts/Targets.fs
  build/scripts/Tooling.fs
  build/scripts/Versioning.fs
  build/scripts/scripts.fsproj
  docs/setup.asciidoc
  docs/troubleshooting.asciidoc
  sample/AspNetFullFrameworkSampleApp/AspNetFullFrameworkSampleApp.csproj
  src/Directory.Build.props
  src/Elastic.Apm.AspNetFullFramework/Elastic.Apm.AspNetFullFramework.csproj
  src/Elastic.Apm.AspNetFullFramework/Elastic.Apm.AspNetFullFramework.nuspec
  src/Elastic.Apm.StartupHook.Loader/Elastic.Apm.StartupHook.Loader.csproj
  src/Elastic.Apm.StartupHook.Loader/Loader.cs
  src/Elastic.Apm/Elastic.Apm.csproj
  src/ElasticApmAgentStartupHook/ElasticApmAgentStartupHook.csproj
  src/ElasticApmAgentStartupHook/README.md
  src/ElasticApmAgentStartupHook/StartupHook.cs
  src/ElasticApmStartupHook/ElasticApmStartupHook.csproj
  src/ElasticApmStartupHook/README.md
  src/ElasticApmStartupHook/StartupHook.cs
  test/Elastic.Apm.Tests.Utilities/InMemoryBlockingLogger.cs
  test/Elastic.Apm.Tests/BackendCommTests/CentralConfig/CentralConfigFetcherTests.cs
Labels: agent-dotnet

#1122 Expose creating agent components for ASP.NET Full Framework
  docs/setup.asciidoc
  src/Elastic.Apm.AspNetFullFramework/AgentDependencies.cs
  src/Elastic.Apm.AspNetFullFramework/AspNetVersion.cs
  src/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs
  src/Elastic.Apm.AspNetFullFramework/FullFrameworkAgentComponents.cs
Labels: bug, v1.7.2

#1149 Update dotnet sdk 5.0 docker image
  .ci/docker/sdk-linux/Dockerfile
Labels: agent-dotnet, ci, v1.7.2
