Repository elastic/apm-agent-dotnet, pull requests merged in 2021-03, with the labels that each got.

#1208 synchronize schema spec
  src/Elastic.Apm.Specification/specs/error.json
  src/Elastic.Apm.Specification/specs/metadata.json
  src/Elastic.Apm.Specification/specs/metricset.json
  src/Elastic.Apm.Specification/specs/span.json
  src/Elastic.Apm.Specification/specs/transaction.json
Labels: agent-dotnet, automation

#931 test: synchronizing gherkin spec
  test/Elastic.Apm.Feature.Tests/ApiKeySteps.cs
  test/Elastic.Apm.Feature.Tests/Features/api_key.feature
Labels: automation

#1175 test: synchronizing gherkin spec
  src/Elastic.Apm.AspNetCore/Elastic.Apm.AspNetCore.csproj
  src/Elastic.Apm.AspNetCore/WebRequestTransactionCreator.cs
  src/Elastic.Apm.GrpcClient/GrpcClientDiagnosticListener.cs
  src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListenerImplBase.cs
  src/Elastic.Apm/Helpers/GrpcHelper.cs
  src/Elastic.Apm/Model/ExecutionSegmentCommon.cs
  src/Elastic.Apm/Model/Span.cs
  src/Elastic.Apm/Model/Transaction.cs
  test/Elastic.Apm.Feature.Tests/Elastic.Apm.Feature.Tests.csproj
  test/Elastic.Apm.Feature.Tests/Features/outcome.feature
  test/Elastic.Apm.Feature.Tests/OutcomeSteps.cs
Labels: agent-dotnet, automation

#1189 Get transaction name from Web API controller route template
  .ci/windows/msbuild-tools.ps1
  sample/AspNetFullFrameworkSampleApp/AspNetFullFrameworkSampleApp.csproj
  sample/AspNetFullFrameworkSampleApp/Controllers/AttributeRoutingWebApiController.cs
  src/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs
  src/Elastic.Apm/Reflection/ExpressionBuilder.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/TestsBase.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/TransactionNameTests.cs
Labels: agent-dotnet, enhancement, v1.9.0

#1216 [Doc] Document clr.gc.time
  docs/metrics.asciidoc
Labels: agent-dotnet

#1219 [Doc] Fix GC time doc
  docs/metrics.asciidoc
Labels: agent-dotnet

#1161 Handling exceptions in the agent
  docs/troubleshooting.asciidoc
  src/Elastic.Apm.AspNetCore/DiagnosticListener/AspNetCoreDiagnosticListener.cs
  src/Elastic.Apm.AspNetCore/DiagnosticListener/AspNetCoreErrorDiagnosticListener.cs
  src/Elastic.Apm.AspNetCore/WebRequestTransactionCreator.cs
  src/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs
  src/Elastic.Apm.Elasticsearch/AuditDiagnosticsListener.cs
  src/Elastic.Apm.Elasticsearch/ElasticsearchDiagnosticsListenerBase.cs
  src/Elastic.Apm.Elasticsearch/ElasticsearchDiagnosticsSubscriber.cs
  src/Elastic.Apm.Elasticsearch/HttpConnectionDiagnosticsListener.cs
  src/Elastic.Apm.Elasticsearch/RequestPipelineDiagnosticsListener.cs
  src/Elastic.Apm.Elasticsearch/SerializerDiagnosticsListener .cs
  src/Elastic.Apm.EntityFrameworkCore/EfCoreDiagnosticListener.cs
  src/Elastic.Apm.GrpcClient/GrpcClientDiagnosticListener.cs
  src/Elastic.Apm.SqlClient/SqlClientDiagnosticListener.cs
  src/Elastic.Apm/Agent.cs
  src/Elastic.Apm/AgentComponents.cs
  src/Elastic.Apm/DiagnosticListeners/DiagnosticListenerBase.cs
  src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListenerCoreImpl.cs
  src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListenerFullFrameworkImpl.cs
  src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListenerImplBase.cs
Labels: agent-dotnet, v1.9.0

#1224 Skip packer cache on ARM
  .ci/packer_cache.sh
Labels: agent-dotnet, automation, ci

#1218 Make sure the TraceEventSession is stopped in GcMetricsProvider
  src/Elastic.Apm/Metrics/MetricsCollector.cs
  src/Elastic.Apm/Metrics/MetricsProvider/GcMetricsProvider.cs
  test/Elastic.Apm.Tests/MetricsTests.cs
Labels: agent-dotnet

#1229 Allow custom registration of Redis ElasticApmProfiler
  src/Elastic.Apm.StackExchange.Redis/ElasticApmProfiler.cs
Labels: agent-dotnet

#1240 CI: use the withAzureCredentials step
  Jenkinsfile
Labels: agent-dotnet, automation, ci

#1228 Use current activity if there is one
  src/Elastic.Apm.AspNetCore/WebRequestTransactionCreator.cs
  src/Elastic.Apm/Model/Transaction.cs
Labels: agent-dotnet, bug, v1.9.0

#1147 Propagate sample rate through tracestate
  sample/ApiSamples/ApiSamples.csproj
  sample/ApiSamples/Program.cs
  src/Elastic.Apm.AspNetCore/WebRequestTransactionCreator.cs
  src/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs
  src/Elastic.Apm/Api/DistributedTracingData.cs
  src/Elastic.Apm/Config/IConfigurationReader.cs
  src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListenerCoreImpl.cs
  src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListenerFullFrameworkImpl.cs
  src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListenerImplBase.cs
  src/Elastic.Apm/DistributedTracing/TraceContext.cs
  src/Elastic.Apm/DistributedTracing/TraceState.cs
  src/Elastic.Apm/Model/Span.cs
  src/Elastic.Apm/Model/Transaction.cs
  src/Elastic.Apm/Sampler.cs
  test/Elastic.Apm.Tests/DistributedTracing/DistributedTracingTests.cs
  test/Elastic.Apm.Tests/DistributedTracing/TraceStateTests.cs
  test/Elastic.Apm.Tests/ErrorTests.cs
Labels: agent-dotnet, enhancement, v1.9.0

#1245 Wait and retry applying IIS changes
  test/Elastic.Apm.AspNetFullFramework.Tests/IisAdministration.cs
Labels: agent-dotnet

#1243 Change NetCoreFact to NetCoreAndNet5Fact
  test/Elastic.Apm.Tests/HttpDiagnosticListenerTests.cs
  test/Elastic.Apm.Tests/NetCoreAndNet5Fact.cs
  test/Elastic.Apm.Tests/NetCoreFact.cs
Labels: agent-dotnet

#1249 Bump version to 1.9.0 and add changelog
  CHANGELOG.asciidoc
  src/Directory.Build.props
Labels: agent-dotnet

#1221 test: synchronizing gherkin spec
  src/Elastic.Apm/Cloud/AzureAppServiceMetadataProvider.cs
  src/Elastic.Apm/Cloud/CloudMetadataProviderCollection.cs
  src/Elastic.Apm/Helpers/EnvironmentHelper.cs
  src/Elastic.Apm/Helpers/EnvironmentVariables.cs
  src/Elastic.Apm/Report/PayloadSenderV2.cs
  test/Elastic.Apm.Feature.Tests/CloudProviderSteps.cs
  test/Elastic.Apm.Feature.Tests/Elastic.Apm.Feature.Tests.csproj
  test/Elastic.Apm.Feature.Tests/Features/azure_app_service_metadata.feature
  test/Elastic.Apm.Tests.Utilities/TestEnvironmentVariables.cs
Labels: agent-dotnet, automation
