Repository elastic/apm-agent-dotnet, pull requests merged in 2021-09, with the labels that each got.

#1471 Sanitize Central config request URI and headers in logs
  src/Elastic.Apm/Api/Http.cs
  src/Elastic.Apm/Api/Request.cs
  src/Elastic.Apm/BackendComm/BackendCommUtils.cs
  src/Elastic.Apm/BackendComm/CentralConfig/CentralConfigFetcher.cs
  src/Elastic.Apm/BackendComm/CentralConfig/CentralConfigResponseParser.cs
  src/Elastic.Apm/Consts.cs
  src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListenerImplBase.cs
  src/Elastic.Apm/Helpers/Sanitization.cs
  src/Elastic.Apm/Report/PayloadSenderV2.cs
  test/Elastic.Apm.AspNetCore.Tests/SanitizeFieldNamesTests.cs
  test/Elastic.Apm.Tests.Utilities/TestLogger.cs
  test/Elastic.Apm.Tests/BackendCommTests/CentralConfig/CentralConfigFetcherTests.cs
  test/Elastic.Apm.Tests/BackendCommTests/PayloadSenderTests.cs
  test/Elastic.Apm.Tests/HttpDiagnosticListenerTests.cs
Labels: bug, agent-dotnet, v1.12.0

#1478 synchronize schema spec
  src/Elastic.Apm.Specification/specs/error.json
  src/Elastic.Apm.Specification/specs/span.json
  src/Elastic.Apm.Specification/specs/transaction.json
Labels: automation, agent-dotnet

#1481 Use Kubernetes pod id determined from cgroup file
  src/Elastic.Apm/AgentComponents.cs
  src/Elastic.Apm/Helpers/SystemInfoHelper.cs
  test/Elastic.Apm.Docker.Tests/ContainerIdCalculationTests.cs
  test/Elastic.Apm.Tests/BackendCommTests/CentralConfig/CentralConfigFetcherTests.cs
  test/Elastic.Apm.Tests/SerializationTests.cs
  test/Elastic.Apm.Tests/SystemInfoHelperTests.cs
Labels: bug, agent-dotnet, v1.12.0

#1472 Honor Transaction.Outcome set by public API in auto instrumentation
  sample/SampleAspNetCoreApp/Controllers/HomeController.cs
  src/Elastic.Apm.AspNetCore/WebRequestTransactionCreator.cs
  src/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs
  src/Elastic.Apm/Model/ExecutionSegmentCommon.cs
  src/Elastic.Apm/Model/Transaction.cs
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreBasicTests.cs
Labels: bug, agent-dotnet

#1487 ADO.NET instrumentation flags
  src/Elastic.Apm/AgentComponents.cs
  src/Elastic.Apm/Elastic.Apm.csproj
  src/Elastic.Apm/Helpers/StringExtensions.cs
  src/Elastic.Apm/Model/DbSpanCommon.cs
  src/Elastic.Apm/Model/ExecutionSegmentCommon.cs
  src/Elastic.Apm/Model/InstrumentationFlag.cs
Labels: agent-dotnet

#1488 Prepare release 1.11.1
  CHANGELOG.asciidoc
  build/scripts/ReleaseNotes.fs
  src/Directory.Build.props
Labels: agent-dotnet

#1489 Extend regex to cover betas and release tags
  .ci/jobs/defaults.yml
Labels: agent-dotnet

#1491 synchronize schema spec
  src/Elastic.Apm.Specification/specs/error.json
  src/Elastic.Apm.Specification/specs/transaction.json
Labels: automation, agent-dotnet

#1492 Remove deprecated Socket.Encrypted
  src/Elastic.Apm.AspNetCore/WebRequestTransactionCreator.cs
  src/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs
  src/Elastic.Apm/Api/Request.cs
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreBasicTests.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/TestsBase.cs
  test/Elastic.Apm.Tests/ApiTests/ConvenientApiTransactionTests.cs
Labels: agent-dotnet

#1497 [CI] use obltGitHubComments
  Jenkinsfile
Labels: automation, agent-dotnet

#1499 synchronize schema spec
  src/Elastic.Apm.Specification/specs/error.json
  src/Elastic.Apm.Specification/specs/metadata.json
  src/Elastic.Apm.Specification/specs/span.json
  src/Elastic.Apm.Specification/specs/transaction.json
Labels: automation, agent-dotnet

#1490 CgroupMetricsProvider: Only query on Linux, just log on other OSs
  src/Elastic.Apm/Metrics/MetricsProvider/CgroupMetricsProvider.cs
  test/Elastic.Apm.Tests/Metrics/CgroupMetricsProviderTests.cs
Labels: agent-dotnet
