Repository elastic/apm-agent-dotnet, pull requests merged in 2022-11, with the labels that each got.

#1752 test: synchronizing gherkin spec
  src/Elastic.Apm/Api/ApiConstants.cs
  src/Elastic.Apm/Helpers/StringExtensions.cs
  src/Elastic.Apm/OpenTelemetry/ElasticActivityListener.cs
  test/Elastic.Apm.Feature.Tests/Features/otel_bridge.feature
  test/Elastic.Apm.Feature.Tests/OpenTelemetryBridgeStepDefinitions.cs
Labels: automation, agent-dotnet

#1892 CentralConfig: handle MaxAge header with less than 5 sec according to spec
  src/Elastic.Apm/BackendComm/CentralConfig/CentralConfigurationResponseParser.cs
  test/Elastic.Apm.Tests/BackendCommTests/CentralConfig/CentralConfigResponseParserTests.cs
Labels: agent-dotnet

#1897 Add basic agent logging preamble
  src/Elastic.Apm/AgentComponents.cs
  src/Elastic.Apm/Logging/ConsoleLogger.cs
  src/Elastic.Apm/Logging/TraceLogger.cs
Labels: agent-dotnet

#1894 Change conditionals to NET5_0_OR_GREATER
  sample/Elastic.Apm.StartupHook.Sample/Startup.cs
  sample/SampleAspNetCoreApp/Startup.cs
  sample/WebApiSample/Startup.cs
  src/Elastic.Apm/AgentComponents.cs
  src/Elastic.Apm/Libraries/Newtonsoft.Json/Serialization/DefaultContractResolver.cs
  src/Elastic.Apm/Libraries/Newtonsoft.Json/Serialization/JsonTypeReflector.cs
  src/Elastic.Apm/OpenTelemetry/ElasticActivityListener.cs
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreBasicTests.cs
  test/Elastic.Apm.AspNetCore.Tests/DistributedTracingAspNetCoreTests.cs
  test/Elastic.Apm.Tests/ConfigTests.cs
  test/Elastic.Apm.Tests/OpenTelemetryTests.cs
Labels: agent-dotnet

#1905 Avoid NRE during startup hook init
  src/ElasticApmAgentStartupHook/StartupHook.cs
Labels: agent-dotnet

#1859 Verify spans in MockPayloadSender using json-spec information
  test/Elastic.Apm.Grpc.Tests/GrpcTests.cs
  test/Elastic.Apm.Tests.Utilities/MockPayloadSender.cs
Labels: agent-dotnet

#1907 Publish docker image with agent
  .ci/linux/build_docker.sh
  .ci/linux/push_docker.sh
  Jenkinsfile
Labels: agent-dotnet

#1927 Avoid panic in file-logging setup
  src/elastic_apm_profiler/src/profiler/env.rs
  src/elastic_apm_profiler/src/profiler/mod.rs
Labels: agent-dotnet

#1928 synchronize schema spec
  src/Elastic.Apm.Specification/specs/span.json
Labels: automation, agent-dotnet

#1922 Use Span timing instead of cumulative SqlCommand statistics
  src/Elastic.Apm.SqlClient/SqlClientDiagnosticListener.cs
  test/Elastic.Apm.SqlClient.Tests/SqlClientListenerTests.cs
Labels: agent-dotnet, community, triage

#1931 test: synchronizing json spec
  test/Elastic.Apm.Tests.Utilities/TestResources/json-specs/service_resource_inference.json
  test/Elastic.Apm.Tests/ServiceResourceTests.cs
Labels: automation, agent-dotnet

#1924 Patching/Fixed CWE-755 Improper Handling of Exceptional Conditions
  test/Elastic.Apm.Azure.Storage.Tests/Elastic.Apm.Azure.Storage.Tests.csproj
Labels: agent-dotnet, community

#1917 Add .NET 7 support
  .ci/windows/tools.ps1
  Jenkinsfile
  global.json
  sample/SampleAspNetCoreApp/SampleAspNetCoreApp.csproj
  sample/WebApiSample/WebApiSample.csproj
  src/Elastic.Apm/Elastic.Apm.csproj
  test/Elastic.Apm.AspNetCore.Static.Tests/ConfigTests.cs
  test/Elastic.Apm.AspNetCore.Static.Tests/Elastic.Apm.AspNetCore.Static.Tests.csproj
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreBasicTests.cs
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreDiagnosticListenerTest.cs
  test/Elastic.Apm.AspNetCore.Tests/Elastic.Apm.AspNetCore.Tests.csproj
  test/Elastic.Apm.AspNetCore.Tests/SanitizeFieldNamesTests.cs
  test/Elastic.Apm.AspNetCore.Tests/TransactionIgnoreUrlsTest.cs
  test/Elastic.Apm.AspNetCore.Tests/TransactionNameTests.cs
  test/Elastic.Apm.Extensions.Hosting.Tests/Elastic.Apm.Extensions.Hosting.Tests.csproj
  test/Elastic.Apm.Extensions.Logging.Tests/Elastic.Apm.Extensions.Logging.Tests.csproj
  test/Elastic.Apm.Grpc.Tests/GrpcTests.cs
  test/Elastic.Apm.StaticExplicitInitialization.Tests/Elastic.Apm.StaticExplicitInitialization.Tests.csproj
  test/Elastic.Apm.StaticImplicitInitialization.Tests/Elastic.Apm.StaticImplicitInitialization.Tests.csproj
  test/Elastic.Apm.Tests.Utilities/Elastic.Apm.Tests.Utilities.csproj
  test/Elastic.Apm.Tests.Utilities/XUnit/MemberData.cs
  test/Elastic.Apm.Tests/Elastic.Apm.Tests.csproj
  test/Elastic.Apm.Tests/HelpersTests/AgentTimerTests.cs
Labels: agent-dotnet

#1930 Improve SOAP action parsing
  Directory.Build.props
  src/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs
  src/Elastic.Apm.AspNetFullFramework/Extensions/SoapRequest.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/Soap/SoapParsingTests.cs
Labels: agent-dotnet
