Repository elastic/apm-agent-dotnet, pull requests merged in 2022-05, with the labels that each got.

#1693 ci: avoid interpolation
  Jenkinsfile
Labels: agent-dotnet

#1694 Add DisableTestFact
  test/Elastic.Apm.Tests.Utilities/Azure/AzureCredentialsFactAttribute.cs
  test/Elastic.Apm.Tests.Utilities/XUnit/DisabledTestFact.cs
Labels: agent-dotnet

#1695 Prepare release 1.15
  CHANGELOG.asciidoc
  Jenkinsfile
  src/Directory.Build.props
  src/elastic_apm_profiler/Cargo.toml
  test/Elastic.Apm.Elasticsearch.Tests/VirtualElasticsearchTests.cs
  test/Elastic.Apm.Profiler.Managed.Tests/AdoNet/SqliteCommandTests.cs
  test/Elastic.Apm.Profiler.Managed.Tests/BasicTests.cs
  test/Elastic.Apm.Profiler.Managed.Tests/ExcludeTests.cs
  test/Elastic.Apm.Tests/Metrics/CgroupMetricsProviderTests.cs
  test/Elastic.Apm.Tests/OpenTelemetryTests.cs
Labels: agent-dotnet

#1698 jjbb: support tag releases started with v and fix opbeans branch creation
  .ci/jobs/defaults.yml
  Jenkinsfile
Labels: agent-dotnet

#1699 Add Span links
  sample/OpenTelemetrySample/OTSamples.cs
  src/Elastic.Apm/Api/IExecutionSegment.cs
  src/Elastic.Apm/Api/ITracer.cs
  src/Elastic.Apm/Api/Links.cs
  src/Elastic.Apm/Api/Tracer.cs
  src/Elastic.Apm/Model/NoopSpan.cs
  src/Elastic.Apm/Model/NoopTransaction.cs
  src/Elastic.Apm/Model/Span.cs
  src/Elastic.Apm/Model/Transaction.cs
  src/Elastic.Apm/OpenTelemetry/ElasticActivityListener.cs
  test/Elastic.Apm.Tests/ApiTests/ApiTests.cs
  test/Elastic.Apm.Tests/ApiTests/ConvenientApiSpanTests.cs
  test/Elastic.Apm.Tests/ApiTests/ConvenientApiTransactionTests.cs
  test/Elastic.Apm.Tests/OpenTelemetryTests.cs
Labels: agent-dotnet

#1703 Deadlock on shut down
  src/Elastic.Apm/Report/PayloadSenderV2.cs
  test/Elastic.Apm.Tests/BackendCommTests/PayloadSenderTests.cs
Labels: agent-dotnet

#1702 Enable AzureCredentialsFactAttribute
  Jenkinsfile
  test/Elastic.Apm.Tests.Utilities/Azure/AzureCredentialsFactAttribute.cs
Labels: agent-dotnet

#1708 Check for nul when constructing UTF16 string
  src/elastic_apm_profiler/src/interfaces/imetadata_assembly_import.rs
Labels: agent-dotnet

#1706 synchronize schema spec
  src/Elastic.Apm.Specification/specs/error.json
  src/Elastic.Apm.Specification/specs/span.json
  src/Elastic.Apm.Specification/specs/transaction.json
Labels: automation, agent-dotnet

#1711 A compression-eligible span must not be buffered on an already ended parent
  src/Elastic.Apm/Model/Span.cs
  test/Elastic.Apm.Tests/SpanCompressionTests.cs
Labels: agent-dotnet

#1707 ci: use withTerraformEnv
  .ci/windows/test-tools.ps1
  Jenkinsfile
Labels: automation, agent-dotnet, Team:Automation

#1715 Handle HTTP404 with valid route data
  sample/SampleAspNetCoreApp/Controllers/HomeController.cs
  src/Elastic.Apm.AspNetCore/WebRequestTransactionCreator.cs
  test/Elastic.Apm.AspNetCore.Tests/TransactionNameTests.cs
Labels: agent-dotnet

#1713 synchronize schema spec
  src/Elastic.Apm.Specification/specs/error.json
  src/Elastic.Apm.Specification/specs/span.json
  src/Elastic.Apm.Specification/specs/transaction.json
Labels: automation, agent-dotnet

#1723 Handle transaction Name with 404
  src/Elastic.Apm.AspNetCore/WebRequestTransactionCreator.cs
Labels: agent-dotnet

#1719 Adapt span compression defaults to spec
  src/Elastic.Apm/Config/ConfigConsts.cs
  src/Elastic.Apm/Model/Span.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/TestsBase.cs
  test/Elastic.Apm.Azure.Storage.Tests/BlobStorageTestsBase.cs
  test/Elastic.Apm.Elasticsearch.Tests/VirtualElasticsearchTests.cs
  test/Elastic.Apm.Tests/SpanCompressionTests.cs
Labels: agent-dotnet

#1725 Update SystemTotalCpuProvider.cs
  src/Elastic.Apm/Metrics/MetricsProvider/SystemTotalCpuProvider.cs
Labels: agent-dotnet
