Repository elastic/apm-agent-dotnet, pull requests merged in 2022-12, with the labels that each got.

#1933 Enable DOTNET_STARTUP_HOOKS for .NET 7
  build/scripts/scripts.fsproj
  sample/Elastic.Apm.StartupHook.Sample/Elastic.Apm.StartupHook.Sample.csproj
  sample/Elastic.Apm.StartupHook.Sample/README.md
  src/ElasticApmAgentStartupHook/StartupHook.cs
  test/Elastic.Apm.StartupHook.Tests/StartupHookTests.cs
Labels: agent-dotnet

#1934 Fixed default for TraceContinuationStrategy
  docs/configuration.asciidoc
Labels: agent-dotnet, community, triage

#1938 Prepare Release 1.19.0
  CHANGELOG.asciidoc
  src/Directory.Build.props
  src/elastic_apm_profiler/Cargo.toml
Labels: agent-dotnet

#1939 Fix typo
  RELEASING.md
Labels: agent-dotnet

#1940 Mark current dev version as alpha
  RELEASING.md
  build/scripts/Build.fs
  src/Directory.Build.props
  src/Elastic.Apm.Profiler.IntegrationsGenerator/Elastic.Apm.Profiler.IntegrationsGenerator.csproj
  src/elastic_apm_profiler/Cargo.toml
Labels: agent-dotnet

#1942 Fix flaky tests
  test/Elastic.Apm.Grpc.Tests/Elastic.Apm.Grpc.Tests.csproj
  test/Elastic.Apm.Grpc.Tests/GrpcTests.cs
  test/Elastic.Apm.Grpc.Tests/SampleAppHostBuilder.cs
Labels: agent-dotnet

#1935 Support for `Elastic.Clients.Elasticsearch`
  ElasticApmAgent.sln
  src/Elastic.Apm.Azure.CosmosDb/AzureCosmosDbTracer.cs
  src/Elastic.Apm.Azure.Storage/MicrosoftAzureBlobStorageTracer.cs
  src/Elastic.Apm/AgentComponents.cs
  src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListenerImplBase.cs
  src/Elastic.Apm/DiagnosticListeners/IHttpSpanTracer.cs
  src/Elastic.Apm/Elastic.Apm.csproj
  src/Elastic.Apm/OpenTelemetry/ElasticActivityListener.cs
  src/Elastic.Apm/OpenTelemetry/ElasticSearchHttpNonTracer.cs
  test/Elastic.Apm.Tests.Utilities/Elastic.Apm.Tests.Utilities.csproj
  test/Elastic.Clients.Elasticsearch.Tests/Elastic.Clients.Elasticsearch.Tests.csproj
  test/Elastic.Clients.Elasticsearch.Tests/ElasticsearchTestFixture.cs
  test/Elastic.Clients.Elasticsearch.Tests/ElasticsearchTests.cs
  test/Elastic.Clients.Elasticsearch.Tests/README.md
Labels: agent-dotnet

#1955 Change default APM Server URL to "http://127.0.0.1:8200"
  src/Elastic.Apm/Config/ConfigConsts.cs
Labels: agent-dotnet

#1954 Implement logging premable spec
  sample/ApiSamples/ApiSamples.csproj
  sample/ApiSamples/Program.cs
  sample/SampleAspNetCoreApp/appsettings.json
  src/Elastic.Apm/AgentComponents.cs
  src/Elastic.Apm/Config/AbstractConfigurationWithEnvFallbackReader.cs
  src/Elastic.Apm/Config/ConfigConsts.cs
  src/Elastic.Apm/Config/ConfigurationKeyValue.cs
  src/Elastic.Apm/Config/ConfigurationMetaData.cs
  src/Elastic.Apm/Config/EnvironmentConfigurationReader.cs
  test/Elastic.Apm.Tests/Config/ConfigTests.cs
  test/Elastic.Apm.Tests/Config/ConfigurationMetaDataTests.cs
  test/Elastic.Apm.Tests/DroppedSpansStatsTests.cs
  test/Elastic.Apm.Tests/Elastic.Apm.Tests.csproj
Labels: agent-dotnet

#1957 Test ElasticsearchDiagnosticsSubscriber with the new client
  test/Elastic.Clients.Elasticsearch.Tests/Elastic.Clients.Elasticsearch.Tests.csproj
  test/Elastic.Clients.Elasticsearch.Tests/ElasticsearchTests.cs
Labels: agent-dotnet

#1950 Continue implementation of Azure Functions spec
  sample/Elastic.AzureFunctionApp.Isolated/local.settings.json
  src/Elastic.Apm.AspNetCore/WebRequestTransactionCreator.cs
  src/Elastic.Apm.Azure.Functions/ApmMiddleware.cs
  src/Elastic.Apm/AgentComponents.cs
  src/Elastic.Apm/Api/Request.cs
  src/Elastic.Apm/Cloud/AzureAppServiceMetadataProvider.cs
  src/Elastic.Apm/Cloud/AzureFunctionsMetadataProvider.cs
  src/Elastic.Apm/Cloud/CloudMetadataProviderCollection.cs
  src/Elastic.Apm/Cloud/EnvironmentBasedAzureMetadataHelper.cs
  src/Elastic.Apm/Features/AgentFeatures.cs
  src/Elastic.Apm/Features/AgentFeaturesProvider.cs
  src/Elastic.Apm/Helpers/SystemInfoHelper.cs
  src/Elastic.Apm/Helpers/UrlUtils.cs
  test/Elastic.Apm.Azure.Functions.Tests/AzureFunctionsTestFixture.cs
  test/Elastic.Apm.Azure.Functions.Tests/AzureFunctionsTests.cs
  test/Elastic.Apm.Azure.Functions.Tests/Elastic.Apm.Azure.Functions.Tests.csproj
  test/Elastic.Apm.Profiler.Managed.Tests/ExcludeTests.cs
  test/Elastic.Apm.Tests.MockApmServer/AssertValidExtensions.cs
  test/Elastic.Apm.Tests/ApiTests/UrlTests.cs
  test/Elastic.Apm.Tests/Cloud/AzureAppServiceMetadataProviderTests.cs
  test/Elastic.Apm.Tests/Cloud/AzureFunctionsMetadataProviderTests.cs
  test/Elastic.Apm.Tests/Cloud/CloudMetadataProviderCollectionTests.cs
  test/Elastic.Apm.Tests/ConstructorTests.cs
  test/Elastic.Apm.Tests/Features/AgentFeaturesProviderTests.cs
  test/Elastic.Apm.Tests/SystemInfoHelperTests.cs
  test/Elastic.Apm.Tests/Utilities/AgentFeaturesProviderScope.cs
Labels: agent-dotnet

#1961 Prevent discarding of agent components if agent is disabled
  src/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs
Labels: agent-dotnet

#1962 synchronize schema spec
  src/Elastic.Apm.Specification/specs/metadata.json
Labels: automation, agent-dotnet

#1953 chore: Update Testcontainers for .NET to version 2.3.0
  sample/StackExchangeRedisSample/Program.cs
  sample/StackExchangeRedisSample/StackExchangeRedisSample.csproj
  test/Elastic.Apm.Elasticsearch.Tests/Elastic.Apm.Elasticsearch.Tests.csproj
  test/Elastic.Apm.Elasticsearch.Tests/ElasticsearchFixture.cs
  test/Elastic.Apm.MongoDb.Tests/Elastic.Apm.MongoDb.Tests.csproj
  test/Elastic.Apm.MongoDb.Tests/Fixture/MongoDbTestcontainer.cs
  test/Elastic.Apm.MongoDb.Tests/Fixture/MongoDbTestcontainerConfiguration.cs
  test/Elastic.Apm.MongoDb.Tests/Fixture/MongoFixture.cs
  test/Elastic.Apm.Profiler.Managed.Tests/AdoNet/AdoNetTestData.cs
  test/Elastic.Apm.Profiler.Managed.Tests/AdoNet/OracleManagedDataAccessCommandTests.cs
  test/Elastic.Apm.Profiler.Managed.Tests/AdoNet/OracleManagedDataAccessCoreCommandTests.cs
  test/Elastic.Apm.Profiler.Managed.Tests/AdoNet/OracleSqlFixture.cs
  test/Elastic.Apm.Profiler.Managed.Tests/Elastic.Apm.Profiler.Managed.Tests.csproj
  test/Elastic.Apm.SqlClient.Tests/Elastic.Apm.SqlClient.Tests.csproj
  test/Elastic.Apm.StackExchange.Redis.Tests/Elastic.Apm.StackExchange.Redis.Tests.csproj
  test/Elastic.Apm.StackExchange.Redis.Tests/ProfilingSessionTests.cs
  test/Elastic.Clients.Elasticsearch.Tests/Elastic.Clients.Elasticsearch.Tests.csproj
  test/Elastic.Clients.Elasticsearch.Tests/ElasticsearchTestFixture.cs
  test/Elastic.Clients.Elasticsearch.Tests/ElasticsearchTests.cs
Labels: agent-dotnet, community, triage
