Repository elastic/apm-agent-dotnet, pull requests merged in 2022-10, with the labels that each got.

#1848 Make build warning-free (treat as errors from now on)
  Directory.Build.props
  build/scripts/scripts.fsproj
Labels: agent-dotnet

#1847 Use json-specs/w3c_distributed_tracing.json test input
  src/Elastic.Apm/DistributedTracing/TraceContext.cs
  src/Elastic.Apm/DistributedTracing/TraceState.cs
  test/Elastic.Apm.Tests.Utilities/JsonFileDataAttribute.cs
  test/Elastic.Apm.Tests/DistributedTracing/DistributedTracingTests.cs
Labels: agent-dotnet

#1850 Use debug log level when dropping spans
  src/Elastic.Apm/Model/Transaction.cs
Labels: agent-dotnet

#1853 Publish artifacts in CI on non-PRs
  Jenkinsfile
Labels: agent-dotnet

#1852 Use json-specs/sql_token_examples.json test input
  test/Elastic.Apm.Tests/DbSpanNameTests.cs
Labels: agent-dotnet

#1851 Use json-specs/wildcard_matcher_tests.json test input
  test/Elastic.Apm.Tests/WildcardMatcherTests.cs
Labels: agent-dotnet

#1857 Make HttpCallWithResponseForbidden more stable
  sample/AspNetFullFrameworkSampleApp/Controllers/HomeController.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/ErrorsTests.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/TestsBase.cs
Labels: agent-dotnet

#1862 Use ConcurrentQueue in InMemoryBlockingLogger
  test/Elastic.Apm.Tests.Utilities/InMemoryBlockingLogger.cs
Labels: agent-dotnet

#1863 Move json-spec TestResources into into Elastic.Apm.Tests.Utilities
  test/Elastic.Apm.Tests.Utilities/Elastic.Apm.Tests.Utilities.csproj
  test/Elastic.Apm.Tests.Utilities/TestResources/json-specs/cgroup_parsing.json
  test/Elastic.Apm.Tests.Utilities/TestResources/json-specs/service_resource_inference.json
  test/Elastic.Apm.Tests.Utilities/TestResources/json-specs/span_types.json
  test/Elastic.Apm.Tests.Utilities/TestResources/json-specs/sql_signature_examples.json
  test/Elastic.Apm.Tests.Utilities/TestResources/json-specs/sql_token_examples.json
  test/Elastic.Apm.Tests.Utilities/TestResources/json-specs/w3c_distributed_tracing.json
  test/Elastic.Apm.Tests.Utilities/TestResources/json-specs/wildcard_matcher_tests.json
Labels: agent-dotnet

#1832 #1825 agent windows auth from config
  docs/configuration.asciidoc
  src/Elastic.Apm/BackendComm/BackendCommUtils.cs
  src/Elastic.Apm/BackendComm/CentralConfig/CentralConfigurationFetcher.cs
  src/Elastic.Apm/Config/AbstractConfigurationReader.cs
  src/Elastic.Apm/Config/AbstractConfigurationWithEnvFallbackReader.cs
  src/Elastic.Apm/Config/ConfigConsts.cs
  src/Elastic.Apm/Config/ConfigurationSnapshotFromReader.cs
  src/Elastic.Apm/Config/EnvironmentConfigurationReader.cs
  src/Elastic.Apm/Config/IConfigurationReader.cs
  test/Elastic.Apm.AspNetCore.Tests/MicrosoftExtensionsConfigTests.cs
  test/Elastic.Apm.Feature.Tests/TestConfiguration.cs
  test/Elastic.Apm.Tests.Utilities/MockConfiguration.cs
  test/Elastic.Apm.Tests/ConstructorTests.cs
Labels: agent-dotnet

#1864 Move custom .NET SQL parsing tests to Benchmark project
  test/Elastic.Apm.Benchmarks/Elastic.Apm.Benchmarks.csproj
  test/Elastic.Apm.Benchmarks/SignatureParserBenchmark.cs
  test/Elastic.Apm.Benchmarks/TestResources/db/sql_signature_examples.json
  test/Elastic.Apm.Tests/DbSpanNameTests.cs
Labels: agent-dotnet

#1868 CI: Build docker image with the profiler
  .ci/linux/build_docker.sh
  .dockerignore
  Dockerfile
  Jenkinsfile
Labels: agent-dotnet

#1870 Fix locale-dependent test issue
  test/Elastic.Apm.Tests/BackendCommTests/CentralConfig/CentralConfigResponseParserTests.cs
Labels: agent-dotnet

#1871 Update docs to reflect support for .NET 5+
  docs/setup-auto-instrumentation.asciidoc
  docs/setup-dotnet-net-core.asciidoc
  docs/setup.asciidoc
Labels: agent-dotnet

#1873 Remove ignored file Elastic.Apm.MongoDb/LICENSE
  src/Elastic.Apm.MongoDb/LICENSE
Labels: agent-dotnet

#1872 Include test in .NET versions >= 5
  test/Elastic.Apm.Tests/Elastic.Apm.Tests.csproj
  test/Elastic.Apm.Tests/ServerCertificateTests.cs
Labels: agent-dotnet

#1874 Prepare Release 1.18.0
  CHANGELOG.asciidoc
  src/Directory.Build.props
  src/elastic_apm_profiler/Cargo.toml
Labels: agent-dotnet

#1867 Improve handling of multiple agent initialization
  src/Elastic.Apm.Profiler.Managed/AutoInstrumentation.cs
  src/Elastic.Apm/Agent.cs
  src/Elastic.Apm/Elastic.Apm.csproj
  test/Elastic.Apm.StaticExplicitInitialization.Tests/StaticImplicitInitializationTests.cs
  test/Elastic.Apm.StaticImplicitInitialization.Tests/ImplicitInitializationTests.cs
  test/Elastic.Apm.Tests.Utilities/Elastic.Apm.Tests.Utilities.csproj
Labels: agent-dotnet

#1878 EOL table has been moved to central EOL Policy page
  docs/upgrading.asciidoc
Labels: agent-dotnet

#1858 Use json-specs/service_resource_inference.json test input
  src/Elastic.Apm/Model/Span.cs
  test/Elastic.Apm.AspNetCore.Tests/AspNetCoreBasicTests.cs
  test/Elastic.Apm.Tests/ApiTests/ExitSpanTests.cs
  test/Elastic.Apm.Tests/ServiceResourceTests.cs
Labels: agent-dotnet

#1882 Fix transaction trace id not aligned when transaction is created from OTel bridge without parent
  sample/OpenTelemetrySample/OTSamples.cs
  src/Elastic.Apm/Api/Tracer.cs
  test/Elastic.Apm.Tests/OpenTelemetryTests.cs
Labels: agent-dotnet, community, triage

#1883 Add readme file to test/Elastic.Apm.Feature.Tests
  test/Elastic.Apm.Feature.Tests/README.md
Labels: agent-dotnet

#1887 Add test which asserts the traceId is the same on a root activity and the corresponding transaction
  test/Elastic.Apm.Tests/OpenTelemetryTests.cs
Labels: agent-dotnet

#1888 Add README regarding json-spec files
  test/Elastic.Apm.Tests.Utilities/README.md
Labels: agent-dotnet

#1884 synchronize schema spec
  src/Elastic.Apm.Specification/specs/error.json
  src/Elastic.Apm.Specification/specs/span.json
  src/Elastic.Apm.Specification/specs/transaction.json
Labels: automation, agent-dotnet

#1877 Enable CloudMetadataProvider on Azure Functions
  src/Elastic.Apm/Cloud/AzureAppServiceMetadataProvider.cs
  src/Elastic.Apm/Cloud/AzureFunctionsMetadataProvider.cs
  src/Elastic.Apm/Cloud/CloudMetadataProviderCollection.cs
  src/Elastic.Apm/Cloud/EnvironmentBasedAzureMetadataProvider.cs
  test/Elastic.Apm.Tests/Cloud/AzureFunctionsMetadataProviderTests.cs
  test/Elastic.Apm.Tests/Cloud/CloudMetadataProviderCollectionTests.cs
Labels: agent-dotnet
