Repository elastic/apm-agent-dotnet, pull requests merged in 2023-10, with the labels that each got.

#2194 Document IIS minimum requirements.
  docs/setup-asp-dot-net.asciidoc
  docs/troubleshooting.asciidoc
Labels: docs, agent-dotnet

#2195 Document IIS minimum requirments (backport to 1.x)
  docs/setup-asp-dot-net.asciidoc
  docs/troubleshooting.asciidoc
Labels: docs, agent-dotnet

#2192 Add note to profiler logs
  docs/setup-auto-instrumentation.asciidoc
Labels: agent-dotnet

#2193 json-specs: cgroup_parsing has been removed
  .ci/updatecli.d/update-json-specs.yml
  test/Elastic.Apm.Tests.Utilities/TestResources/json-specs/container_metadata_discovery.json
Labels: agent-dotnet

#2198 Update high watermark settings for Elasticsearch Integration tests
  .github/workflows/test-linux.yml
  test/instrumentations/Elastic.Clients.Elasticsearch.Tests/Elastic.Clients.Elasticsearch.Tests.csproj
  test/instrumentations/Elastic.Clients.Elasticsearch.Tests/ElasticsearchTestFixture.cs
  test/instrumentations/Elastic.Clients.Elasticsearch.Tests/ElasticsearchTests.cs
  test/instrumentations/Elastic.Clients.Elasticsearch.Tests/xunit.runner.json
Labels: agent-dotnet

#2197 [Automation] Update JSON specs
  test/Elastic.Apm.Tests.Utilities/TestResources/json-specs/container_metadata_discovery.json
Labels: automation, agent-dotnet

#2199 re-enable profiler tests
  .github/workflows/test-linux.yml
  ElasticApmAgent.sln
  test/instrumentations/Elastic.Clients.Elasticsearch.Tests/Elastic.Clients.Elasticsearch.Tests.csproj
  test/instrumentations/Elastic.Clients.Elasticsearch.Tests/xunit.runner.json
  test/profiler/Elastic.Apm.Profiler.Managed.Tests/AdoNet/OracleManagedDataAccessCoreCommandTests.cs
  test/profiler/Elastic.Apm.Profiler.Managed.Tests/AdoNet/OracleSqlFixture.cs
  test/profiler/Elastic.Apm.Profiler.Managed.Tests/Elastic.Apm.Profiler.Managed.Tests.csproj
  test/xunit.runner.json
Labels: agent-dotnet

#2196 Support OnExecuteRequestStep available in new .NET versions for IIS modules.
  src/integrations/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs
  src/integrations/Elastic.Apm.AspNetFullFramework/HttpContextCurrentExecutionSegmentsContainer.cs
Labels: agent-dotnet

#2202 Add release notes for v1.25
  CHANGELOG.asciidoc
Labels: agent-dotnet

#2201 action: post-release steps
  .github/workflows/bootstrap/action.yml
  .github/workflows/release.yml
  RELEASING.md
Labels: ci, agent-dotnet

#2205 action(post-release): use fetch-depth, quoting and fix git commands
  .github/workflows/release.yml
Labels: agent-dotnet

#2208 Update auto intrumentation docs
  docs/setup-auto-instrumentation.asciidoc
  docs/supported-technologies.asciidoc
Labels: agent-dotnet
