Repository elastic/apm-agent-dotnet, pull requests merged in 2023-07, with the labels that each got.

#2130 Update api-opentelemetry.asciidoc
  docs/api-opentelemetry.asciidoc
Labels: agent-dotnet, community, triage

#2128 isolate azure tests
  .github/workflows/bootstrap/action.yml
  .github/workflows/test-linux.yml
  .github/workflows/test-windows.yml
  test/Elastic.Apm.Tests.Utilities/Azure/AzureCredentials.cs
  test/Elastic.Apm.Tests.Utilities/Terraform/TerraformResources.cs
Labels: agent-dotnet

#2067 Send domain name when detected
  src/Elastic.Apm/Helpers/SystemInfoHelper.cs
  src/instrumentations/Elastic.Apm.MongoDb/LICENSE
Labels: agent-dotnet

#2113 [Automation] Update Gherkin specs
  test/Elastic.Apm.Feature.Tests/Features/azure_app_service_metadata.feature
  test/Elastic.Apm.Feature.Tests/Features/azure_functions_metadata.feature
Labels: automation, agent-dotnet

#2109 Agent.Configuration now always points to ConfigurationStore's configuration
  src/Elastic.Apm/Agent.cs
  src/Elastic.Apm/AgentComponents.cs
  src/Elastic.Apm/ApmAgentExtensions.cs
  src/Elastic.Apm/Config/IConfiguration.cs
  src/Elastic.Apm/Config/IConfigurationReader.cs
  src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListenerImplBase.cs
  src/instrumentations/Elastic.Apm.Elasticsearch/ElasticsearchDiagnosticsSubscriber.cs
  src/instrumentations/Elastic.Apm.EntityFrameworkCore/EfCoreDiagnosticsSubscriber.cs
  src/instrumentations/Elastic.Apm.GrpcClient/GrpcClientDiagnosticSubscriber.cs
  src/instrumentations/Elastic.Apm.MongoDb/MongoDbDiagnosticsSubscriber.cs
  src/instrumentations/Elastic.Apm.SqlClient/SqlClientDiagnosticSubscriber.cs
  src/integrations/Elastic.Apm.AspNetCore/ApmMiddlewareExtension.cs
  src/integrations/Elastic.Apm.AspNetCore/DiagnosticListener/AspNetCoreDiagnosticSubscriber.cs
  src/integrations/Elastic.Apm.AspNetCore/DiagnosticListener/AspNetCoreErrorDiagnosticsSubscriber.cs
  src/integrations/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs
  src/integrations/Elastic.Apm.Extensions.Hosting/HostBuilderExtensions.cs
  src/integrations/Elastic.Apm.Extensions.Logging/ApmErrorLogger.cs
  test/Elastic.Apm.Tests/Config/ConfigTests.cs
  test/Elastic.Apm.Tests/MetricsTests.cs
  test/integrations/Elastic.Apm.AspNetCore.Tests/AspNetCoreBasicTests.cs
Labels: agent-dotnet

#2142 Fix #2141 reduce noise for stack frame capturing logging
  src/Elastic.Apm/Helpers/StacktraceHelper.cs
Labels: agent-dotnet

#2136 Log when we detect LegacyAspNetSynchronizationContext
  src/integrations/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs
Labels: agent-dotnet

#2143 Remove skipped assemblies test results prior to uploading as artifact
  .github/workflows/test-linux-reporter.yml
  .github/workflows/test/action.yml
  src/instrumentations/Elastic.Apm.MongoDb/LICENSE
Labels: agent-dotnet

#2144 ensure only build/output gets shared with docker builds
  .dockerignore
Labels: agent-dotnet
