Repository elastic/apm-agent-dotnet, pull requests merged in 2023-04, with the labels that each got.

#2041 Prevent sending activation_method in metadata for 8.7.0
  src/Elastic.Apm/BackendComm/BackendCommUtils.cs
  src/Elastic.Apm/Report/PayloadSenderV2.cs
  src/Elastic.Apm/ServerInfo/ElasticVersion.cs
  test/Elastic.Apm.Tests/BackendCommTests/ServiceActivationTests.cs
Labels: enhancement, v1.12.1

#2042 Prepare 1.21.0 release
  CHANGELOG.asciidoc
  src/Directory.Build.props
  src/elastic_apm_profiler/Cargo.toml
Labels: agent-dotnet

#2021 Remove *.NetCore.sln completely
  .ci/linux/remove-projects.sh
  .ci/linux/test.sh
  .ci/windows/test.bat
  .gitignore
  Jenkinsfile
  build/scripts/Build.fs
  build/scripts/Paths.fs
  build/scripts/Targets.fs
  sample/AspNetFullFrameworkSampleApp/AspNetFullFrameworkSampleApp.csproj
  sample/AspNetFullFrameworkSampleApp/WindowsReadme.md
  test/Elastic.Apm.AspNetFullFramework.Tests/Elastic.Apm.AspNetFullFramework.Tests.csproj
  test/Elastic.Apm.AspNetFullFramework.Tests/Program-NoFullFramework.cs
Labels: agent-dotnet

#2045 Fix snapshotty now release correctly calls profiler-zip
  .github/workflows/snapshoty.yml
Labels: agent-dotnet

#2044 Bump version post 1.21.0 release
  src/Directory.Build.props
  src/elastic_apm_profiler/Cargo.toml
Labels: agent-dotnet

#2049 Increase logging if no jit target was found for integration method
  .editorconfig
  src/elastic_apm_profiler/src/profiler/mod.rs
Labels: agent-dotnet

#2051 Profiler docs: add note about server url and secret token
  docs/setup-auto-instrumentation.asciidoc
Labels: agent-dotnet

#2047 feat: Update Testcontainers for .NET to version 3.0.0
  sample/MySqlDataSample/MySqlDataSample.csproj
  sample/StackExchangeRedisSample/Program.cs
  sample/StackExchangeRedisSample/StackExchangeRedisSample.csproj
  test/Elastic.Apm.Elasticsearch.Tests/Elastic.Apm.Elasticsearch.Tests.csproj
  test/Elastic.Apm.Elasticsearch.Tests/ElasticsearchFixture.cs
  test/Elastic.Apm.Elasticsearch.Tests/ElasticsearchTestContainer.cs
  test/Elastic.Apm.Elasticsearch.Tests/ElasticsearchTestContainerConfiguration.cs
  test/Elastic.Apm.Elasticsearch.Tests/ElasticsearchTests.cs
  test/Elastic.Apm.EntityFramework6.Tests/Elastic.Apm.EntityFramework6.Tests.csproj
  test/Elastic.Apm.MongoDb.Tests/Elastic.Apm.MongoDb.Tests.csproj
  test/Elastic.Apm.MongoDb.Tests/Fixture/MongoDbTestcontainer.cs
  test/Elastic.Apm.MongoDb.Tests/Fixture/MongoDbTestcontainerConfiguration.cs
  test/Elastic.Apm.MongoDb.Tests/Fixture/MongoFixture.cs
  test/Elastic.Apm.Profiler.Managed.Tests/AdoNet/MySqlFixture.cs
  test/Elastic.Apm.Profiler.Managed.Tests/AdoNet/OracleSqlFixture.cs
  test/Elastic.Apm.Profiler.Managed.Tests/AdoNet/PostgreSqlFixture.cs
  test/Elastic.Apm.Profiler.Managed.Tests/AdoNet/SqlServerFixture.cs
  test/Elastic.Apm.Profiler.Managed.Tests/Elastic.Apm.Profiler.Managed.Tests.csproj
  test/Elastic.Apm.Profiler.Managed.Tests/Kafka/KafkaFixture.cs
  test/Elastic.Apm.Profiler.Managed.Tests/RabbitMq/RabbitMqFixture.cs
  test/Elastic.Apm.SqlClient.Tests/Elastic.Apm.SqlClient.Tests.csproj
  test/Elastic.Apm.SqlClient.Tests/SqlServerFixture.cs
  test/Elastic.Apm.StackExchange.Redis.Tests/Elastic.Apm.StackExchange.Redis.Tests.csproj
  test/Elastic.Apm.StackExchange.Redis.Tests/ProfilingSessionTests.cs
  test/Elastic.Clients.Elasticsearch.Tests/Elastic.Clients.Elasticsearch.Tests.csproj
  test/Elastic.Clients.Elasticsearch.Tests/ElasticsearchTestFixture.cs
  test/Elastic.Clients.Elasticsearch.Tests/ElasticsearchTests.cs
Labels: agent-dotnet, community, triage

#2050 Enable listening to Microsoft.Data.SqlClient.EventSource on .NET full framework
  Directory.Build.props
  ElasticApmAgent.sln
  sample/Sample.Microsoft.Data.SqlClient/Program.cs
  sample/Sample.Microsoft.Data.SqlClient/Sample.Microsoft.Data.SqlClient.csproj
  src/Elastic.Apm.SqlClient/SqlEventListener.cs
  src/Elastic.Apm/Elastic.Apm.csproj
Labels: agent-dotnet

#2057 Ensure rustup is called before release.sh
  Jenkinsfile
Labels: agent-dotnet

#2058 ensure we install cargo-make before release.sh
  Jenkinsfile
Labels: agent-dotnet

#2059 Move cargo installation for release inside dotnet context (which sets HOME)
  Jenkinsfile
Labels: agent-dotnet

#2060 Add logging to IHttpModule.EndRequest if transaction is null
  src/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs
  src/Elastic.Apm.AspNetFullFramework/HttpContextCurrentExecutionSegmentsContainer.cs
Labels: agent-dotnet

#2061 Bump 1.22.0 release and introduce release notes
  CHANGELOG.asciidoc
  src/Directory.Build.props
  src/elastic_apm_profiler/Cargo.toml
Labels: agent-dotnet

#2062 Bump version post 1.22.0 release
  src/Directory.Build.props
  src/elastic_apm_profiler/Cargo.toml
Labels: agent-dotnet
