Repository elastic/apm-agent-dotnet, pull requests merged in 2023-02, with the labels that each got.

#2005 Markes `span_stack_trace_min_duration` and `stack_trace_limit` dynamic
  docs/configuration.asciidoc
Labels: agent-dotnet

#2007 Fix sha source in updatecli update-specs.yml
  .ci/update-specs.yml
Labels: agent-dotnet, community, triage

#2008 Use composite action for updatecli workflow
  .github/workflows/update-specs.yml
Labels: agent-dotnet, community, triage

#1990 Fix CultureNotFoundException in SystemTotalCpuProvider
  src/Elastic.Apm/Elastic.Apm.csproj
  test/Elastic.Apm.Tests/Elastic.Apm.Tests.csproj
Labels: agent-dotnet

#2009 update rust and cargo make to latest, was getting installation errors for cargo make on older versions
  .ci/windows/tools.ps1
  Jenkinsfile
  src/Elastic.Apm.Profiler.Managed/integrations.yml
Labels: ci, agent-dotnet, v8.8.0

#1986 Allow solution to be build on non windows platforms again
  test/Elastic.Apm.AspNetFullFramework.Tests/Elastic.Apm.AspNetFullFramework.Tests.csproj
Labels: bug, agent-dotnet, v8.7.0

#2010 Add elastic_apm_profiler as not built project to solution
  ElasticApmAgent.sln
  src/elastic_apm_profiler/elastic_apm_profiler.csproj
  src/elastic_apm_profiler/src/lib.rs
Labels: agent-dotnet

#2012 Move to exlicit net461 assembly reference
  Directory.Build.props
Labels: agent-dotnet

#2014 Attempt to fix nullref found in #1999
  src/Elastic.Apm/Model/Span.cs
Labels: bug, agent-dotnet, v1.12.0

#2011 Address all code style errors
  ElasticApmAgent.sln.DotSettings
  sample/Elastic.Apm.StartupHook.Sample/Startup.cs
  src/Elastic.Apm.Profiler.Managed/CallTarget/Handlers/Continuations/TaskContinuationGenerator.cs
  src/Elastic.Apm/Libraries/.editorconfig
  src/Elastic.Apm/Libraries/Newtonsoft.Json/JsonConvert.cs
  src/Elastic.Apm/Libraries/Newtonsoft.Json/JsonSerializer.cs
  src/Elastic.Apm/Libraries/Newtonsoft.Json/Linq/JsonLoadSettings.cs
  test/Elastic.Apm.Profiler.Managed.Tests/DuckTyping/DuckIgnoreTests.cs
  test/Elastic.Apm.Profiler.Managed.Tests/DuckTyping/DuckIncludeTests.cs
  test/Elastic.Apm.Profiler.Managed.Tests/DuckTyping/ExceptionsTests.cs
  test/Elastic.Apm.Profiler.Managed.Tests/DuckTyping/Fields/ReferenceType/ReferenceTypeFieldTests.cs
  test/Elastic.Apm.Profiler.Managed.Tests/DuckTyping/Fields/TypeChaining/TypeChainingFieldTests.cs
  test/Elastic.Apm.Profiler.Managed.Tests/DuckTyping/Fields/ValueType/ValueTypeFieldTests.cs
  test/Elastic.Apm.Profiler.Managed.Tests/DuckTyping/Methods/MethodTests.cs
  test/Elastic.Apm.Profiler.Managed.Tests/DuckTyping/Methods/ProxiesDefinitions/ObscureDuckTypeVirtualClass.cs
  test/Elastic.Apm.Profiler.Managed.Tests/DuckTyping/ObscureObject.cs
  test/Elastic.Apm.Profiler.Managed.Tests/DuckTyping/Properties/ReferenceType/ReferenceTypePropertyTests.cs
  test/Elastic.Apm.Profiler.Managed.Tests/DuckTyping/Properties/TypeChaining/TypeChainingPropertyTests.cs
  test/Elastic.Apm.Profiler.Managed.Tests/DuckTyping/Properties/ValueType/ValueTypePropertyTests.cs
  test/Elastic.Apm.Profiler.Managed.Tests/DuckTyping/StructTests.cs
  test/Elastic.Apm.Profiler.Managed.Tests/DuckTyping/TypesTupleTests.cs
Labels: refactoring, agent-dotnet, v8.8.0

#2020 Ensure the generated netcore solution builds when running ./build.sh release
  Directory.Build.props
Labels: refactoring, agent-dotnet, v8.8.0

#2018 Capture the azure function delegate invoke exception on Transaction
  src/Elastic.Apm.Azure.Functions/ApmMiddleware.cs
Labels: agent-dotnet, v8.8.0

#1988 Suppport latest version of Microsoft.Data.SqlClient
  docs/integrations.asciidoc
  src/Elastic.Apm.Profiler.Managed/Integrations/AdoNet/AdoNetTypeNames.cs
  src/Elastic.Apm.Profiler.Managed/integrations.yml
  test/Elastic.Apm.SqlClient.Tests/Elastic.Apm.SqlClient.Tests.csproj
  test/Elastic.Apm.SqlClient.Tests/SqlServerFixture.cs
Labels: agent-dotnet

#2022 snapshoty github action still using an old version of rustc
  .github/workflows/snapshoty.yml
Labels: ci, agent-dotnet, v8.8.0

#2023 fix jenkins trigger not running jobs on v1.20.0 tag
  .ci/jobs/defaults.yml
Labels: agent-dotnet

#2025 Bump back to alpha post 1.20.0 release
  src/Directory.Build.props
  src/elastic_apm_profiler/Cargo.toml
Labels: agent-dotnet

#2026 Fix NRE in exception logging
  src/Elastic.Apm.MongoDb/DiagnosticSource/MongoDiagnosticListener.cs
Labels: agent-dotnet
