Repository elastic/apm-agent-dotnet, pull requests merged in 2023-05, with the labels that each got.

#2064 [Automation] Update Gherkin specs
  test/Elastic.Apm.Feature.Tests/Features/otel_bridge.feature
Labels: automation, agent-dotnet

#2055 Further configuration refactorings
  src/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs
  src/Elastic.Apm.AspNetFullFramework/ElasticApmModuleConfiguration.cs
  src/Elastic.Apm.AspNetFullFramework/Helper/ConfigHelper.cs
  src/Elastic.Apm.Azure.Functions/ApmMiddleware.cs
  src/Elastic.Apm.Extensions.Hosting/Config/ApmConfiguration.cs
  src/Elastic.Apm/AgentComponents.cs
  src/Elastic.Apm/BackendComm/CentralConfig/CentralConfiguration.cs
  src/Elastic.Apm/BackendComm/CentralConfig/CentralConfigurationFetcher.cs
  src/Elastic.Apm/BackendComm/CentralConfig/CentralConfigurationKeyValue.cs
  src/Elastic.Apm/BackendComm/CentralConfig/CentralConfigurationResponseParser.cs
  src/Elastic.Apm/BackendComm/CentralConfig/DynamicConfigurationOption.cs
  src/Elastic.Apm/BackendComm/CentralConfig/RuntimeConfigurationSnapshot.cs
  src/Elastic.Apm/Config/AbstractConfigurationReader.cs
  src/Elastic.Apm/Config/ConfigConsts.cs
  src/Elastic.Apm/Config/ConfigurationKeyValue.cs
  src/Elastic.Apm/Config/ConfigurationLogger.cs
  src/Elastic.Apm/Config/ConfigurationLoggingPreamble.cs
  src/Elastic.Apm/Config/ConfigurationOption.cs
  src/Elastic.Apm/Config/ConfigurationStore.cs
  src/Elastic.Apm/Config/EnvironmentConfiguration.cs
  src/Elastic.Apm/Config/FallbackToEnvironmentConfigurationBase.cs
  src/Elastic.Apm/Config/IConfigurationReader.cs
  src/Elastic.Apm/Consts.cs
  src/Elastic.Apm/Elastic.Apm.csproj
  test/Elastic.Apm.AspNetCore.Static.Tests/ConfigTests.cs
  test/Elastic.Apm.AspNetCore.Tests/ApmConfigurationTests.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/AppSettingsTests.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/CaptureHeadersConfigDisabledTest.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/CentralConfigTests.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/CustomEnvironmentViaSettings.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/CustomFlushInterval.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/CustomServiceNameSetViaSettings.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/CustomServiceNodeNameViaSettings.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/GlobalLabelsTests.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/MetricsTestsBase.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/SampleRate0Tests.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/TestsBase.cs
  test/Elastic.Apm.AspNetFullFramework.Tests/TransactionIgnoreUrlsTest.cs
  test/Elastic.Apm.Feature.Tests/TestConfiguration.cs
  test/Elastic.Apm.StartupHook.Tests/StartupHookTests.cs
  test/Elastic.Apm.Tests.Utilities/MockConfiguration.cs
  test/Elastic.Apm.Tests/BackendCommTests/CentralConfig/CentralConfigFetcherTests.cs
  test/Elastic.Apm.Tests/BackendCommTests/CentralConfig/CentralConfigResponseParserTests.cs
  test/Elastic.Apm.Tests/Config/ConfigTests.cs
  test/Elastic.Apm.Tests/Config/ConfigurationLoggingPreambleTests.cs
  test/Elastic.Apm.Tests/ConstructorTests.cs
  test/Elastic.Apm.Tests/MetricsTests.cs
Labels: breaking change, agent-dotnet

#1995 action: build and test on Linux GH runners
  .github/workflows/test-linux.yml
  .github/workflows/test-reporter.yml
  Jenkinsfile
Labels: automation, agent-dotnet, Team:Automation

#1992 action: release
  .github/workflows/release-main.yml
  .github/workflows/release.yml
  Jenkinsfile
Labels: automation, agent-dotnet, Team:Automation

#2040 Move IIS tests to github actions
  .ci/windows/testnet461.bat
  .github/.github.csproj
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/workflows/bootstrap/action.yml
  .github/workflows/test-iis.yml
  Directory.Build.props
  ElasticApmAgent.sln
  Jenkinsfile
  sample/ApiSamples/ApiSamples.csproj
  sample/AspNetFullFrameworkSampleApp/AspNetFullFrameworkSampleApp.csproj
  sample/Elastic.Apm.AdoNet/Elastic.Apm.AdoNet.csproj
  sample/MySqlDataSample/MySqlDataSample.csproj
  sample/NpgsqlSample/NpgsqlSample.csproj
  sample/OracleManagedDataAccessSample/OracleManagedDataAccessSample.csproj
  sample/SqlClientSample/SqlClientSample.csproj
  sample/SqliteSample/SqliteSample.csproj
  src/Elastic.Apm.AspNetFullFramework/Elastic.Apm.AspNetFullFramework.csproj
  src/Elastic.Apm.EntityFramework6/Elastic.Apm.EntityFramework6.csproj
  src/Elastic.Apm.Profiler.Managed.Core/Elastic.Apm.Profiler.Managed.Core.csproj
  src/Elastic.Apm.Profiler.Managed.Loader/Elastic.Apm.Profiler.Managed.Loader.csproj
  src/Elastic.Apm.Profiler.Managed.Loader/Startup.NetFramework.cs
  src/Elastic.Apm.Profiler.Managed/Elastic.Apm.Profiler.Managed.csproj
  src/Elastic.Apm.Specification/Elastic.Apm.Specification.csproj
  src/Elastic.Apm.SqlClient/Elastic.Apm.SqlClient.csproj
  src/Elastic.Apm/Elastic.Apm.csproj
  src/Elastic.Apm/Libraries/Newtonsoft.Json/Serialization/DynamicValueProvider.cs
  src/Elastic.Apm/Libraries/Newtonsoft.Json/Utilities/DynamicReflectionDelegateFactory.cs
  src/Elastic.Apm/Libraries/Newtonsoft.Json/Utilities/ILGeneratorExtensions.cs
  src/elastic_apm_profiler/src/profiler/managed.rs
  test/Directory.Build.props
  test/Elastic.Apm.AspNetFullFramework.Tests/Elastic.Apm.AspNetFullFramework.Tests.csproj
  test/Elastic.Apm.AspNetFullFramework.Tests/NoWebComponentTests.cs
  test/Elastic.Apm.Profiler.Managed.Tests/AdoNet/NpgSqlCommandTests.cs
  test/Elastic.Apm.Profiler.Managed.Tests/AdoNet/OracleManagedDataAccessCommandTests.cs
  test/Elastic.Apm.Profiler.Managed.Tests/ExcludeTests.cs
  test/Elastic.Apm.Profiler.Managed.Tests/ProfiledApplication.cs
  test/Elastic.Apm.SqlClient.Tests/Elastic.Apm.SqlClient.Tests.csproj
  test/Elastic.Apm.Tests.Utilities/Elastic.Apm.Tests.Utilities.csproj
  test/Elastic.Apm.Tests.Utilities/MockConfiguration.cs
  test/Elastic.Apm.Tests/Elastic.Apm.Tests.csproj
  test/Elastic.Apm.Tests/HttpDiagnosticListenerTests.cs
Labels: agent-dotnet

#2074 remove all stages from JenkinsFile
  Jenkinsfile
Labels: agent-dotnet

#2075 remove unreferenced .ci scripts
  .ci/linux/benchmark.sh
  .ci/linux/build.sh
  .ci/linux/codestyle.sh
  .ci/windows/dotnet.bat
  .ci/windows/msbuild-tools.ps1
  .ci/windows/msbuild.bat
  .ci/windows/prepare-test.bat
  .ci/windows/test.bat
  .ci/windows/testnet461.bat
  .github/workflows/test-linux.yml
Labels: agent-dotnet

#2076 fix code styling errors
  src/Elastic.Apm.MongoDb/LICENSE
  test/Elastic.Apm.Elasticsearch.Tests/ElasticsearchFixture.cs
  test/Elastic.Apm.MongoDb.Tests/Fixture/MongoFixture.cs
  test/Elastic.Apm.Profiler.Managed.Tests/AdoNet/MySqlFixture.cs
  test/Elastic.Apm.Profiler.Managed.Tests/AdoNet/OracleSqlFixture.cs
  test/Elastic.Apm.Profiler.Managed.Tests/AdoNet/PostgreSqlFixture.cs
  test/Elastic.Apm.Profiler.Managed.Tests/AdoNet/SqlServerFixture.cs
  test/Elastic.Apm.Profiler.Managed.Tests/Kafka/KafkaFixture.cs
  test/Elastic.Apm.Profiler.Managed.Tests/RabbitMq/RabbitMqFixture.cs
  test/Elastic.Apm.SqlClient.Tests/SqlServerFixture.cs
Labels: agent-dotnet

#2077 move release.yml to on release published trigger
  .github/workflows/release.yml
Labels: agent-dotnet

#2078 Make snapshotty reuse build artifacts.
  .github/workflows/snapshoty.yml
  .github/workflows/test-linux.yml
  .github/workflows/test-windows-core.yml
Labels: agent-dotnet

#2079 Fix release-main.yml
  .github/workflows/release-main.yml
Labels: agent-dotnet

#2081 update release-main.yml
  .github/workflows/release-main.yml
Labels: agent-dotnet

#2083 update test-reporter
  .github/workflows/test-reporter.yml
Labels: agent-dotnet

#2082 work on tests on CI
  .ci/linux/release.sh
  .ci/linux/test-profiler.sh
  .ci/linux/test-startuphooks.sh
  .ci/linux/test.sh
  .github/workflows/bootstrap/action.yml
  .github/workflows/install-dependencies/action.yml
  .github/workflows/release-main.yml
  .github/workflows/release.yml
  .github/workflows/test-iis.yml
  .github/workflows/test-linux.yml
  .github/workflows/test-windows-core.yml
  .github/workflows/test/action.yml
  RELEASING.md
  sample/AspNetFullFrameworkSampleApp/AspNetFullFrameworkSampleApp.csproj
  src/Elastic.Apm/BackendComm/BackendCommUtils.cs
  test/Elastic.Apm.AspNetCore.Static.Tests/Elastic.Apm.AspNetCore.Static.Tests.csproj
  test/Elastic.Apm.AspNetCore.Tests/Elastic.Apm.AspNetCore.Tests.csproj
  test/Elastic.Apm.AspNetFullFramework.Tests/Elastic.Apm.AspNetFullFramework.Tests.csproj
  test/Elastic.Apm.Azure.CosmosDb.Tests/Elastic.Apm.Azure.CosmosDb.Tests.csproj
  test/Elastic.Apm.Azure.Functions.Tests/Elastic.Apm.Azure.Functions.Tests.csproj
  test/Elastic.Apm.Azure.ServiceBus.Tests/Elastic.Apm.Azure.ServiceBus.Tests.csproj
  test/Elastic.Apm.Azure.Storage.Tests/Elastic.Apm.Azure.Storage.Tests.csproj
  test/Elastic.Apm.Docker.Tests/Elastic.Apm.Docker.Tests.csproj
  test/Elastic.Apm.Elasticsearch.Tests/Elastic.Apm.Elasticsearch.Tests.csproj
  test/Elastic.Apm.EntityFramework6.Tests/Elastic.Apm.EntityFramework6.Tests.csproj
  test/Elastic.Apm.EntityFrameworkCore.Tests/Elastic.Apm.EntityFrameworkCore.Tests.csproj
  test/Elastic.Apm.Extensions.Hosting.Tests/Elastic.Apm.Extensions.Hosting.Tests.csproj
  test/Elastic.Apm.Extensions.Hosting.Tests/HostBuilderExtensionTests.cs
  test/Elastic.Apm.Extensions.Logging.Tests/Elastic.Apm.Extensions.Logging.Tests.csproj
  test/Elastic.Apm.Feature.Tests/CloudProviderSteps.cs
  test/Elastic.Apm.Feature.Tests/Elastic.Apm.Feature.Tests.csproj
  test/Elastic.Apm.Feature.Tests/Features/otel_bridge.feature
  test/Elastic.Apm.Grpc.Tests/Elastic.Apm.Grpc.Tests.csproj
  test/Elastic.Apm.MongoDb.Tests/Elastic.Apm.MongoDb.Tests.csproj
  test/Elastic.Apm.Profiler.Managed.Tests/Elastic.Apm.Profiler.Managed.Tests.csproj
  test/Elastic.Apm.SqlClient.Tests/Elastic.Apm.SqlClient.Tests.csproj
  test/Elastic.Apm.StackExchange.Redis.Tests/Elastic.Apm.StackExchange.Redis.Tests.csproj
  test/Elastic.Apm.StartupHook.Tests/Elastic.Apm.StartupHook.Tests.csproj
  test/Elastic.Apm.StaticExplicitInitialization.Tests/Elastic.Apm.StaticExplicitInitialization.Tests.csproj
  test/Elastic.Apm.StaticImplicitInitialization.Tests/Elastic.Apm.StaticImplicitInitialization.Tests.csproj
  test/Elastic.Apm.Tests.Utilities/MockConfiguration.cs
  test/Elastic.Apm.Tests/BackendCommTests/CentralConfig/CentralConfigFetcherTests.cs
  test/Elastic.Apm.Tests/Elastic.Apm.Tests.csproj
  test/Elastic.Clients.Elasticsearch.Tests/Elastic.Clients.Elasticsearch.Tests.csproj
Labels: agent-dotnet

#2084 re-enable windows jobs
  .ci/windows/test-iis.bat
  .ci/windows/test-profiler.bat
  .ci/windows/test-startuphooks.bat
  .ci/windows/test-tools.ps1
  .ci/windows/tools.ps1
  .github/.editorconfig
  .github/workflows/install-dependencies/action.yml
  .github/workflows/release-main.yml
  .github/workflows/test-iis.yml
  .github/workflows/test-linux-reporter.yml
  .github/workflows/test-linux.yml
  .github/workflows/test-windows-core.yml
  .github/workflows/test-windows-reporter.yml
  .github/workflows/test-windows.yml
  .github/workflows/test/action.yml
  test/Elastic.Apm.Elasticsearch.Tests/ElasticsearchTests.cs
  test/Elastic.Apm.MongoDb.Tests/MongoApmTests.cs
  test/Elastic.Apm.SqlClient.Tests/EfCoreWithMsSqlTests.cs
  test/Elastic.Apm.SqlClient.Tests/SqlClientListenerTests.cs
  test/Elastic.Apm.StackExchange.Redis.Tests/ProfilingSessionTests.cs
  test/Elastic.Apm.Tests.Utilities/Elastic.Apm.Tests.Utilities.csproj
  test/Elastic.Apm.Tests.Utilities/TestEnvironment.cs
  test/Elastic.Apm.Tests.Utilities/XUnit/DisabledOnWindowsFact.cs
  test/Elastic.Clients.Elasticsearch.Tests/ElasticsearchTests.cs
Labels: agent-dotnet

#2085 Re-enable IIS tests and ensure the junit xml gets stored and reported
  .github/workflows/test-windows-iis.yml
Labels: agent-dotnet

#2088 use step-summary for test reporter
  .github/workflows/test-linux-reporter.yml
  .github/workflows/test-windows-iis-reporter.yml
  .github/workflows/test-windows-reporter.yml
Labels: agent-dotnet

#2090 Cache nuget installations
  .github/workflows/bootstrap/action.yml
  .github/workflows/release-main.yml
  .github/workflows/release.yml
  .github/workflows/test-linux.yml
  .github/workflows/test-windows-iis.yml
  .github/workflows/test-windows.yml
  Directory.Build.props
Labels: agent-dotnet

#2092 Remove PATH modification from build.bat
  build.bat
Labels: agent-dotnet

#2095 Fix relative output for Nuget Pack
  build/scripts/Paths.fs
Labels: agent-dotnet
