Repository elastic/apm-agent-dotnet, pull requests merged in 2023-01, with the labels that each got.

#1965 Fixed the broken Dockerfile
  docs/setup-auto-instrumentation.asciidoc
Labels: agent-dotnet, community, triage

#1963 synchronize schema spec
  src/Elastic.Apm.Specification/specs/span.json
  src/Elastic.Apm.Specification/specs/transaction.json
Labels: automation, agent-dotnet

#1960 Remove redundant header sanitization code
  src/Elastic.Apm.AspNetCore/WebRequestTransactionCreator.cs
  src/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs
  src/Elastic.Apm/Filters/HeaderDictionarySanitizerFilter.cs
  src/Elastic.Apm/Report/PayloadSenderV2.cs
  test/Elastic.Apm.Tests.Utilities/MockPayloadSender.cs
Labels: agent-dotnet

#1959 Implement latest Azure Functions spec changes
  sample/Elastic.AzureFunctionApp.Isolated/local.settings.json
  src/Elastic.Apm.Azure.Functions/ApmMiddleware.cs
  src/Elastic.Apm/Api/Cloud.cs
  src/Elastic.Apm/Cloud/AzureFunctionsMetadataProvider.cs
  src/Elastic.Apm/Config/AbstractConfigurationReader.cs
  test/Elastic.Apm.Azure.Functions.Tests/AzureFunctionsTestFixture.cs
  test/Elastic.Apm.Azure.Functions.Tests/AzureFunctionsTests.cs
  test/Elastic.Apm.Tests/Cloud/AzureFunctionsMetadataProviderTests.cs
Labels: agent-dotnet

#1975 test: synchronizing gherkin spec
  test/Elastic.Apm.Feature.Tests/CloudProviderSteps.cs
  test/Elastic.Apm.Feature.Tests/Features/azure_functions_metadata.feature
Labels: automation, agent-dotnet

#1978 Prepare Azure Functions NuGet package
  .ci/linux/deploy.sh
  src/Elastic.Apm.Azure.Functions/Elastic.Apm.Azure.Functions.csproj
Labels: agent-dotnet

#1926 Make sure PayloadSender uses up-to-date TLS
  src/Elastic.Apm/BackendComm/BackendCommUtils.cs
Labels: agent-dotnet

#1966 Document OTel bridge
  docs/api-opentelemetry.asciidoc
  docs/configuration.asciidoc
  docs/index.asciidoc
Labels: agent-dotnet

#1981 Doc: Setting up Azure Functions Tracing
  docs/images/azure-functions-configuration.png
  docs/setup-azure-functions.asciidoc
  docs/setup.asciidoc
Labels: agent-dotnet

#1972 Rename config to enable/disable OTel bridge
  src/Elastic.Apm/AgentComponents.cs
  src/Elastic.Apm/BackendComm/CentralConfig/CentralConfigurationFetcher.cs
  src/Elastic.Apm/Config/AbstractConfigurationReader.cs
  src/Elastic.Apm/Config/AbstractConfigurationWithEnvFallbackReader.cs
  src/Elastic.Apm/Config/ConfigConsts.cs
  src/Elastic.Apm/Config/ConfigurationMetaData.cs
  src/Elastic.Apm/Config/ConfigurationSnapshotFromReader.cs
  src/Elastic.Apm/Config/EnvironmentConfigurationReader.cs
  src/Elastic.Apm/Config/IConfigurationReader.cs
  test/Elastic.Apm.Feature.Tests/OpenTelemetryBridgeStepDefinitions.cs
  test/Elastic.Apm.Feature.Tests/TestConfiguration.cs
  test/Elastic.Apm.Tests.Utilities/MockConfiguration.cs
  test/Elastic.Apm.Tests/ConstructorTests.cs
  test/Elastic.Apm.Tests/OpenTelemetryTests.cs
  test/Elastic.Clients.Elasticsearch.Tests/ElasticsearchTests.cs
Labels: agent-dotnet

#1976 Set agent activation method
  src/Elastic.Apm/Api/Service.cs
  src/Elastic.Apm/Consts.cs
  src/Elastic.Apm/Elastic.Apm.csproj
  src/Elastic.Apm/Helpers/EnvironmentVariables.cs
  test/Elastic.Apm.Azure.Functions.Tests/AzureFunctionsTests.cs
  test/Elastic.Apm.Profiler.Managed.Tests/AspNetCore/AspNetCoreTests.cs
  test/Elastic.Apm.Profiler.Managed.Tests/BasicTests.cs
  test/Elastic.Apm.Profiler.Managed.Tests/Elastic.Apm.Profiler.Managed.Tests.csproj
  test/Elastic.Apm.StartupHook.Tests/StartupHookTests.cs
  test/Elastic.Apm.Tests/Extensions/EnvironmentVariablesExtensionsTests.cs
Labels: agent-dotnet

#1956 Support publishing a snapshot build
  .ci/snapshoty.yml
  Jenkinsfile
Labels: agent-dotnet

#1983 Make sure VCRuntime is linked statically
  docs/setup-auto-instrumentation.asciidoc
  src/elastic_apm_profiler/Cargo.toml
  src/elastic_apm_profiler/build.rs
Labels: agent-dotnet

#1968 Add support for the latest version OracleManagedDataAccess
  docs/integrations.asciidoc
  sample/MySqlDataSample/MySqlDataSample.csproj
  sample/OracleManagedDataAccessCoreSample/OracleManagedDataAccessCoreSample.csproj
  sample/SqlClientSample/SqlClientSample.csproj
  sample/SqliteSample/SqliteSample.csproj
  src/Elastic.Apm.Profiler.Managed/Integrations/AdoNet/AdoNetTypeNames.cs
  src/Elastic.Apm.Profiler.Managed/integrations.yml
  test/Elastic.Apm.Profiler.Managed.Tests/AdoNet/AdoNetTestData.cs
  test/Elastic.Apm.Profiler.Managed.Tests/Elastic.Apm.Profiler.Managed.Tests.csproj
Labels: agent-dotnet

#1993 Fix flaky test CollectGcMetrics
  test/Elastic.Apm.Tests/MetricsTests.cs
Labels: agent-dotnet

#1970 Improve agent supportability
  src/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs
  src/Elastic.Apm/AgentComponents.cs
  src/Elastic.Apm/BackendComm/BackendCommUtils.cs
  src/Elastic.Apm/Config/ProfilerLogConfig.cs
  src/Elastic.Apm/Helpers/LogLevelUtils.cs
  src/Elastic.Apm/Logging/ConsoleLogger.cs
  src/Elastic.Apm/Logging/TraceLogger.cs
  test/Elastic.Apm.Tests/Config/ProfilerLogConfigTests.cs
  test/Elastic.Apm.Tests/LoggerTests.cs
Labels: agent-dotnet

#2000 Fix doc for SpanCompressionSameKindMaxDuration
  docs/configuration.asciidoc
Labels: agent-dotnet

#1991 action: snapshoty
  .ci/snapshoty.yml
  .github/workflows/snapshoty.yml
  Jenkinsfile
  build.bat
Labels: agent-dotnet

#1994 action: opentelemetry exporter
  .github/workflows/opentelemetry.yml
Labels: automation, agent-dotnet, Team:Automation
