Repository elastic/apm-agent-dotnet, pull requests merged in 2024-02, with the labels that each got.

#2273 action: github secrets if no forked prs
  .github/workflows/test-windows.yml
Labels: agent-dotnet

#2272 Include process information in metadata stanza when emiting events to apm-server
  src/Elastic.Apm/Api/ProcessInformation.cs
  src/Elastic.Apm/Model/Metadata.cs
  src/Elastic.Apm/Report/PayloadSenderV2.cs
  test/Elastic.Apm.Tests.MockApmServer/MetadataDto.cs
Labels: agent-dotnet

#2275 action: disable tests targeting TestContainers Cloud if Forked PRs
  test/Elastic.Apm.Tests.Utilities/Docker/DockerFactAttribute.cs
  test/Elastic.Apm.Tests.Utilities/Docker/DockerTheoryAttribute.cs
  test/Elastic.Apm.Tests.Utilities/Docker/DockerUtils.cs
  test/Elastic.Apm.Tests.Utilities/TestEnvironment.cs
  test/Elastic.Apm.Tests.Utilities/XUnit/DisabledOnWindowsFact.cs
  test/Elastic.Apm.Tests.Utilities/XUnit/DockerAttributes.cs
  test/instrumentations/Elastic.Apm.Docker.Tests/BasicDockerTests.cs
  test/instrumentations/Elastic.Apm.Elasticsearch.Tests/ElasticsearchTests.cs
  test/instrumentations/Elastic.Apm.MongoDb.Tests/MongoApmTests.cs
  test/instrumentations/Elastic.Apm.SqlClient.Tests/EfCoreWithMsSqlTests.cs
  test/instrumentations/Elastic.Apm.SqlClient.Tests/SqlClientListenerTests.cs
  test/instrumentations/Elastic.Apm.StackExchange.Redis.Tests/ProfilingSessionTests.cs
  test/instrumentations/Elastic.Clients.Elasticsearch.Tests/ElasticsearchTests.cs
  test/profiler/Elastic.Apm.Profiler.Managed.Tests/AdoNet/MySqlCommandTests.cs
  test/profiler/Elastic.Apm.Profiler.Managed.Tests/AdoNet/NpgSqlCommandTests.cs
  test/profiler/Elastic.Apm.Profiler.Managed.Tests/AdoNet/OracleManagedDataAccessCommandTests.cs
  test/profiler/Elastic.Apm.Profiler.Managed.Tests/AdoNet/OracleManagedDataAccessCoreCommandTests.cs
  test/profiler/Elastic.Apm.Profiler.Managed.Tests/AdoNet/SqlCommandTests.cs
  test/profiler/Elastic.Apm.Profiler.Managed.Tests/Kafka/KafkaTests.cs
  test/profiler/Elastic.Apm.Profiler.Managed.Tests/RabbitMq/RabbitMqTests.cs
Labels: agent-dotnet

#2271 actions: fix tabs
  .github/workflows/test-windows-iis-reporter.yml
  .github/workflows/test-windows-reporter.yml
Labels: ci, agent-dotnet

#2267 #2266 Cleanup of packages thanks to Framework reference
  src/integrations/Elastic.Apm.AspNetCore/Elastic.Apm.AspNetCore.csproj
Labels: agent-dotnet, community, triage

#2270 github-action: use wildcards for discovering all the workflows
  .github/workflows/opentelemetry.yml
Labels: agent-dotnet

#2274 Limit memory usage when capturing SOAP request bodies
  src/integrations/Elastic.Apm.AspNetFullFramework/Extensions/SoapRequest.cs
Labels: agent-dotnet

#2276 Address a few synchronization issues in the codebase
  src/Elastic.Apm/ApmAgentExtensions.cs
  src/Elastic.Apm/Libraries/Newtonsoft.Json/Converters/BinaryConverter.cs
  src/profiler/Elastic.Apm.Profiler.Managed/DuckTyping/ILHelpersExtensions.cs
  src/profiler/Elastic.Apm.Profiler.Managed/Reflection/ModuleLookup.cs
Labels: agent-dotnet

#2277 Truncate unknown keys logging from central config parser
  src/Elastic.Apm/BackendComm/CentralConfig/CentralConfigurationResponseParser.cs
Labels: agent-dotnet

#2278 Ensure exposes default constants are readonly.
  src/Elastic.Apm/Config/ConfigConsts.cs
Labels: agent-dotnet

#2279 Remove RegexConverter, not used in serialization from and to apm-server
  src/Elastic.Apm/Libraries/Newtonsoft.Json/Converters/RegexConverter.cs
  src/Elastic.Apm/Libraries/Newtonsoft.Json/Serialization/DefaultContractResolver.cs
Labels: agent-dotnet

#2280 Cleanup some dead code and one instance of null propagation in tooling NOT userfacing code
  src/Elastic.Apm.Specification/Validator.cs
  src/integrations/Elastic.Apm.AspNetCore/Consts.cs
Labels: agent-dotnet

#2237 Reenable IIS tests
  .github/workflows/test-windows-iis.yml
  Directory.Build.props
  sample/Sample.Microsoft.Data.SqlClient/Sample.Microsoft.Data.SqlClient.csproj
Labels: agent-dotnet

#2264 Switch to Licence expression rather than file
  src/Directory.Build.props
Labels: agent-dotnet, community, triage

#2283 Fix #2248 duplicate key errors on dropped span stats update
  src/Elastic.Apm/Model/Transaction.cs
Labels: agent-dotnet

#2291 Update Rust
  .github/workflows/install-dependencies/action.yml
Labels: agent-dotnet

#2288 security: add permissions block to workflows
  .github/workflows/addToProject.yml
  .github/workflows/labeler.yml
  .github/workflows/test-linux-reporter.yml
  .github/workflows/test-windows-iis-reporter.yml
  .github/workflows/test-windows-reporter.yml
Labels: agent-dotnet

#2290 Fully implement the sanitization spec
  docs/configuration.asciidoc
  src/Elastic.Apm/Api/Request.cs
  src/Elastic.Apm/Filters/ErrorContextSanitizerFilter.cs
  src/Elastic.Apm/Filters/HeaderDictionarySanitizerFilter.cs
  src/Elastic.Apm/Filters/RequestCookieExtractionFilter.cs
  src/Elastic.Apm/Filters/Sanitization.cs
  src/Elastic.Apm/Filters/SpanStackTraceCapturingFilter.cs
  src/Elastic.Apm/Filters/TransactionIgnoreUrlsFilter.cs
  src/Elastic.Apm/Helpers/CookieHeaderParser.cs
  src/Elastic.Apm/Report/PayloadSenderV2.cs
  src/integrations/Elastic.Apm.AspNetCore/WebRequestTransactionCreator.cs
  test/Elastic.Apm.Tests.Utilities/MockPayloadSenderWithFilters.cs
  test/Elastic.Apm.Tests/HelpersTests/CookieHeaderParserTests.cs
  test/iis/AspNetFullFrameworkSampleApp/AspNetFullFrameworkSampleApp.csproj
  test/iis/AspNetFullFrameworkSampleApp/Controllers/HomeController.cs
  test/iis/AspNetFullFrameworkSampleApp/Views/Home/Cookies.cshtml
  test/iis/AspNetFullFrameworkSampleApp/Web.config
  test/iis/Elastic.Apm.AspNetFullFramework.Tests/README.md
  test/iis/Elastic.Apm.AspNetFullFramework.Tests/SanitizeFieldNamesTests.cs
  test/iis/Elastic.Apm.AspNetFullFramework.Tests/TestsBase.cs
  test/integrations/Elastic.Apm.AspNetCore.Tests/SanitizeFieldNamesTests.cs
  test/integrations/applications/SampleAspNetCoreApp/Controllers/HomeController.cs
  test/integrations/applications/SampleAspNetCoreApp/SampleAspNetCoreApp.csproj
  test/integrations/applications/SampleAspNetCoreApp/Views/Home/CookiePage.cshtml
  test/integrations/applications/SampleAspNetCoreApp/appsettings.json
Labels: agent-dotnet

#2294 Add release notes for 1.26.0
  CHANGELOG.asciidoc
Labels: agent-dotnet

#2295 Add write permissions to workflows
  .github/workflows/labeler.yml
  .github/workflows/test-windows-iis-reporter.yml
  .github/workflows/test-windows-reporter.yml
Labels: agent-dotnet

#2297 Bring docs folder up to date manually
  docs/configuration.asciidoc
  docs/images/classic-pipeline.png
  docs/images/integrated-pipeline.png
  docs/supported-technologies.asciidoc
  docs/troubleshooting.asciidoc
Labels: agent-dotnet

#2298 Refine agent initialization within ElasticApmModule
  src/Elastic.Apm/Helpers/DbgInstanceNameGenerator.cs
  src/integrations/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs
  test/Elastic.Apm.Tests/HelpersTests/DbgInstanceNameGeneratorTests.cs
Labels: agent-dotnet

#2299 Further logging refinements in ElasticApmModule
  src/Elastic.Apm/Logging/TraceLogger.cs
  src/integrations/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs
Labels: agent-dotnet
